force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/PMC_CPQ_Integration_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/fields/PMC_CPQ_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Endpoint__c</fullName>
    <description>This is used to store the Integration endpoint.</description>
    <label>Endpoint</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_SS_AccountSalesAreaRelationship__c/PMC_SS_AccountSalesAreaRelationship__c.object-meta.xml
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_SS_AccountSalesAreaRelationship__c/fields/PMC_SS_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SalesArea__c</fullName>
    <description>Master Detail relationship to Sales Area</description>
    <label>Sales Area</label>
    <referenceTo>PMC_SS_SalesArea__c</referenceTo>
    <relationshipName>AccountSalesAreRelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/PMC_SS_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area Object</description>
    <label>Sales Area</label>
    <nameField>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Get_Prices_Status__c.field-meta.xml
<CustomField>
    <fullName>Get_Prices_Status__c</fullName>
    <label>Get Prices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Elegible</fullName>
                <isActive>false</isActive>
                <label>Elegible</label>
            </value>
            <value>
                <fullName>Not Elegible</fullName>
                <isActive>false</isActive>
                <label>Not Elegible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SBQQ__Account__c</field>
            <operation>equals</operation>
            <valueField>PMC_SS_AccountSalesAreaRelationship__c.PMC_SS_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_FinalPricePerTon__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FinalPricePerTon__c</fullName>
    <label>Final Price Per Ton (Original)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_FinalPricePerTonne__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FinalPricePerTonne__c</fullName>
    <description>The Overall Final Price Per Tonne</description>
    <label>Final Price Per Tonne</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
    <relationshipLabel>CPQ Quote Lines</relationshipLabel>
    <relationshipName>PMC_CPQ_CPQQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PMC_CPQ_FetchLatestPriceBeforeSubmission.cls
/**@description Action Class invoked from the flow whenever Submit For Approval Button is clicked.
 *  @author Sai Shashank Poondla
 *  @storynumber GDASF-8480
 */
public without sharing class PMC_CPQ_FetchLatestPriceBeforeSubmission {
	/**
	 * @description This is the apex action that will be invoked from the flow.
	 * @param lstQuotes - list of quotes sent from the flow.
	 * @return getPriceResult - List of boolean results.
	 */
	@InvocableMethod(
		label='Get Price Callout on Submit for Approval'
		description='Triggers the CPI Interface to create quote, quote line and contract records in SAP'
		category='SBQQ__Quote__c'
	)
	public static List<Boolean> postInfoToCPI(List<SBQQ__Quote__c> lstQuotes) {
		try {
			return executeGetPriceCallout(lstQuotes);
		} catch (Exception e) {
			return new List<Boolean>{ false };
		}
	}

	/**
	 * @description This is the apex action that will be invoked from the LWC.
	 * @param lstQuotes - list of quotes sent from the LWC.
	 * @return getPriceResult - List of boolean results.
	 */
	@AuraEnabled(cacheable=false)
	public static List<Boolean> postInfoToCPIFromLWC(List<SBQQ__Quote__c> lstQuotes) {
		return executeGetPriceCallout(lstQuotes);
	}

	/**
	 * @description Common method that contains the actual logic for both flow and LWC calls.
	 * @param lstQuotes - list of quotes.
	 * @return getPriceResult - List of boolean results.
	 */
	private static List<Boolean> executeGetPriceCallout(List<SBQQ__Quote__c> lstQuotes) {
		Map<String, Schema.SObjectField> fieldMap = SBQQ__Quote__c.sObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).fields.getMap();

		// Get all of the fields on the object
		Set<String> setFieldNames = fieldMap.keySet();
		list<String> lstFieldNames = new List<String>(setFieldNames);
		//Get price return
		List<Boolean> getPriceResult = new List<Boolean>();

		// Dynamic Query String. - Additional Record Tye details fetched for Region based Request 060
		Id quoteId = lstQuotes[0].Id;
		List<SBQQ__Quote__c> lstQuote = Database.query(
			'SELECT ' +
				String.escapeSingleQuotes(String.join(lstFieldNames, ',')) +
				', PMC_CPQ_SalesArea__r.PMC_SS_SalesArea__r.PMC_CPQ_SAPSalesOrganization__c FROM SBQQ__Quote__c where Id  = \'' +
				String.escapeSingleQuotes(quoteId) +
				'\''
		); // WITH SECURITY_ENFORCED');

		if (lstQuotes != null && !lstQuotes.isempty()) {
			// List<SBQQ__QuoteLine__c> lstQuoteLine = [
			// 	SELECT id, PMC_CPQ_FinalPricePerTonne__c
			// 	FROM SBQQ__QuoteLine__c
			// 	WHERE SBQQ__Quote__c = :lstQuotes[0].id
			// 	WITH SECURITY_ENFORCED
			// ];
			// List<SBQQ__QuoteLine__c> updateOriginalPrice = new List<SBQQ__QuoteLine__c>();

			// for (SBQQ__QuoteLine__c quoteLine : lstQuoteLine) {
			// 	if (quoteLine.PMC_CPQ_FinalPricePerTonne__c != null) {
			// 		quoteLine.PMC_CPQ_FinalPricePerTon__c = quoteLine.PMC_CPQ_FinalPricePerTonne__c;
			// 		updateOriginalPrice.add(quoteLine);
			// 	}
			// }

			String strInterface = 'ProductsExternalPricing';
			PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface);
			String strEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;
			HttpResponse response = PMC_CPQ_GetPriceOnQuickSave.makeCalloutRequest(lstQuote, strEndpoint);
			String getPricesStatus;
			SBQQ.TriggerControl.disable();
			if (response.getStatusCode() != 200 && response.getStatusCode() != 201) {
				getPriceResult.add(false);
				if (!Test.isRunningTest()) {
					update new SBQQ__Quote__c(Id = lstQuotes[0].Id, Get_Prices_Status__c = 'Failed');
					throw new CustomException('Error in Get Price Callout: ' + response.getStatus());
				}
			} else {
				update new SBQQ__Quote__c(Id = lstQuotes[0].Id, Get_Prices_Status__c = 'Approval In Progress');
				getPriceResult.add(true);
			}
			SBQQ.TriggerControl.enable();
			// if (response != null && (Schema.sObjectType.SBQQ__QuoteLine__c.isAccessible() || Schema.sObjectType.SBQQ__QuoteLine__c.isUpdateable())) {
			// 	try {
			// 		DataBase.update(updateOriginalPrice);
			// 	} catch (DmlException objException) {
			// 		PMC_ErrorLogClass.processException(objException);
			// 	}

			// 	PMC_CPQ_GetPriceResponseParsing.parseJSONGetPriceInterface(lstQuotes, response, strEndpoint);

			// }
		}

		return getPriceResult;
	}
}