force-app/main/default/objects/Case/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_AtFaultParty__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_AtFaultParty__c</fullName>
    <label>At Fault Party</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Logistics Planning</fullName>
            </value>
            <value>
                <fullName>Plant / Operations</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Supply Planning</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_Order__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field stores the look-up to the Order record against which the case is being created</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <description>This field captures the order number in SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
    <label>SAP Order Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SoldToAccount__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SoldToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture Sold To Account for the Order.</description>
    <inlineHelpText>Sold To Account for the Order.</inlineHelpText>
    <label>Sold To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseExtControllerTests.cls
@isTest
private class CaseExtControllerTests {
    
    @TestSetup
    static void setup() {    
        // Create an Account
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        // Create a Contact
        Contact cont = new Contact(
            LastName = 'Test Contact',
            AccountId = acc.Id
        );
        insert cont;
        
        // Create an Order with the correct Pricebook2Id
        Order ord = new Order(
            AccountId = acc.Id,
            EffectiveDate = Date.today(),
            Status = 'Draft',
            PMC_CPQ_SoldToAccount__c = acc.Id,
            PMC_CPQ_SAPOrderNumber__c = '6576512'
        );
        insert ord;
        
        // Create a Case
        Case cs = new Case(
            Subject = 'Test Case Subject',
            Status = 'New',
            Type = 'Inquiry',
            ContactId = cont.Id,
            PMC_SS_AtFaultParty__c = 'Carrier',
            PMC_SS_Order__c = ord.Id
        );
        insert cs;
    }
    
    testMethod static void testSubmit() {
        Case cse = [Select Id from Case LIMIT 1];
        
        Test.startTest();
        CaseExtController con = new CaseExtController(new ApexPages.StandardController(cse));
        con.onSubmit();
        cse = [SELECT ApprovalStatus__c FROM Case WHERE Id = :cse.Id LIMIT 1];
        Test.stopTest();
        System.assertEquals('Approved', cse.ApprovalStatus__c);
    }
    
    testMethod static void testRecall() {
        Case cse = [Select Id from Case LIMIT 1];
        
        Test.startTest();
        CaseExtController con = new CaseExtController(new ApexPages.StandardController(cse));
        con.onRecall();
        cse = [SELECT ApprovalStatus__c FROM Case WHERE Id = :cse.Id LIMIT 1];
        Test.stopTest();
        System.assertEquals('Recalled', cse.ApprovalStatus__c);
    }
    
    testMethod static void testinvokeURLAction() {
        Case cse = [Select Id from Case LIMIT 1];
        
        Test.startTest();
        CaseExtController.invokeURLAction(new List<String>{cse.Id});
        cse = [SELECT ApprovalStatus__c FROM Case WHERE Id = :cse.Id LIMIT 1];
        Test.stopTest();
        System.assertEquals('Approved', cse.ApprovalStatus__c);
    }
}