force-app/main/default/objects/Case/fields/Customer_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Customer_Purchase_Order__c</fullName>
    <label>Customer Purchase Order #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_AtFaultParty__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_AtFaultParty__c</fullName>
    <label>At Fault Party</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Logistics Planning</fullName>
            </value>
            <value>
                <fullName>Plant / Operations</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Supply Planning</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_Invoice__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>PMC_CPQ_Invoice__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_Order__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field stores the look-up to the Order record against which the case is being created</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_OriginalInvoiceAmount__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_OriginalInvoiceAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Original Invoice Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_SAPInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SAPInvoiceNumber__c</fullName>
    <label>SAP Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SAPOrderNumber__c</fullName>
    <label>SAP Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_SoldToAccount__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SoldToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Sold To)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_VehicleId__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_VehicleId__c</fullName>
    <label>Vehicle Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <description>This field captures the order number in SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
    <label>SAP Order Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SoldToAccount__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SoldToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture Sold To Account for the Order.</description>
    <inlineHelpText>Sold To Account for the Order.</inlineHelpText>
    <label>Sold To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Invoice__c/PMC_CPQ_Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_Invoice__c/fields/PMC_CPQ_BillingDate__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_BillingDate__c</fullName>
    <label>Billing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Invoice__c/fields/PMC_CPQ_CustomerPONumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CustomerPONumber__c</fullName>
    <label>Customer Purchase Order #</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Invoice__c/fields/PMC_CPQ_Delivery__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Delivery associated to this invoice.</description>
    <label>Delivery</label>
    <referenceTo>Shipment</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Invoice__c/fields/PMC_CPQ_InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_InvoiceNumber__c</fullName>
    <description>This field is to capture the SAP Invoice Id.</description>
    <externalId>true</externalId>
    <label>SAP Invoice Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Invoice__c/fields/PMC_CPQ_Order__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Invoice__c/fields/PMC_CPQ_SoldToAccount__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SoldToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices (Sold To)</relationshipLabel>
    <relationshipName>PMC_CPQ_SoldToInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Invoice__c/fields/PMC_CPQ_TotalInvoiceValue__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_TotalInvoiceValue__c</fullName>
    <label>Total Invoice Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_Order__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field captures the Order Number.</description>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceCasesController.cls
/**
* @File Name : InvoiceCasesController.cls
* @Description :GSMD-1449-Create Case from Invoice Record
* @Author :Azaam Ali
* @Last Modified By :Azaam Ali
* @Last Modified On : May 7, 2025
* @Modification Log :
*==============================================================================
* Ver | Date 		| Author 	| Modification
*==============================================================================
* 1.0 | May 7, 2025 |  Azaamali | Initial Version
* 2.0 | Aug 12, 2025 |  Nithin M | GSMD-2754: Auto Populate Case Fields When Opening Case from Invoice Object
**/

public class InvoiceCasesController {
    @AuraEnabled(cacheable=true)
    public static List<Case> getRelatedCases(Id invoiceId) {
        System.debug('In apex class!');
        List<Case> casesRetreived = [SELECT Id, CaseNumber, Status, Type, Contact.Name, PMC_SS_AtFaultParty__c, CreatedDate 
                FROM Case WHERE PMC_SS_Invoice__c = :invoiceId ORDER BY CreatedDate DESC];
        System.debug('casesRetreived-->' + casesRetreived);
        return casesRetreived;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getInvoiceDetails(Id invoiceId) {
        PMC_CPQ_Invoice__c inv = [SELECT Id,Name, PMC_CPQ_Order__r.AccountId, PMC_CPQ_Order__r.BillToContactId, PMC_CPQ_Order__c,PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c,
                                  PMC_CPQ_SoldToAccount__c, PMC_CPQ_InvoiceNumber__c,PMC_CPQ_CustomerPONumber__c,PMC_CPQ_TotalInvoiceValue__c,PMC_CPQ_Delivery__r.PMC_CPQ_VehicleID__c,PMC_CPQ_BillingDate__c 
                                  FROM PMC_CPQ_Invoice__c
                                  WHERE Id = :invoiceId];

        Map<String, Object> result = new Map<String, Object>();
        result.put('AccountId', inv.PMC_CPQ_Order__r.AccountId);
        result.put('ContactId', inv.PMC_CPQ_Order__r.BillToContactId);
		result.put('PMC_SS_Order__c',inv.PMC_CPQ_Order__c);
		result.put('PMC_SS_SAPOrderNumber__c', inv.PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c);
        result.put('PMC_SS_SoldToAccount__c', inv.PMC_CPQ_Order__r.AccountId);
		result.put('PMC_SS_SAPInvoiceNumber__c',inv.PMC_CPQ_InvoiceNumber__c);
        result.put('PMC_SS_Invoice__c',inv.Id);
       	result.put('Customer_Purchase_Order__c',inv.PMC_CPQ_CustomerPONumber__c);
        result.put('PMC_SS_OriginalInvoiceAmount__c',inv.PMC_CPQ_TotalInvoiceValue__c);
        result.put('PMC_SS_VehicleID__c',inv.PMC_CPQ_Delivery__r.PMC_CPQ_VehicleID__c);
        result.put('PMC_CPQ_BillingDate__c',inv.PMC_CPQ_BillingDate__c);

        return result;
    }
}