force-app/main/default/objects/Case/fields/Customer_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Customer_Purchase_Order__c</fullName>
    <label>Customer Purchase Order #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_AtFaultParty__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_AtFaultParty__c</fullName>
    <label>At Fault Party</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Logistics Planning</fullName>
            </value>
            <value>
                <fullName>Plant / Operations</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Supply Planning</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_Order__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field stores the look-up to the Order record against which the case is being created</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SAPOrderNumber__c</fullName>
    <label>SAP Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_SNOW_OrderNumberorContractNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SNOW_OrderNumberorContractNumber__c</fullName>
    <label>Order Number or Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_SoldToAccount__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SoldToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Sold To)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PMC_CPQ_PO__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PO__c</fullName>
    <label>Customer Purchase Order #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_PO__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PO__c</fullName>
    <description>This field is used to capture the user input for Purchase order number.</description>
    <inlineHelpText>Purchase Order number for this order.</inlineHelpText>
    <label>Customer Purchase Order #</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <description>This field captures the order number in SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
    <label>SAP Order Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SoldToAccount__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SoldToAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to capture Sold To Account for the Order.</description>
    <inlineHelpText>Sold To Account for the Order.</inlineHelpText>
    <label>Sold To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderCasesController.cls
public with sharing class OrderCasesController {
    @AuraEnabled(cacheable=true)
    public static List<Case> getRelatedCases(Id orderId) {
        System.debug('In apex class!');
        List<Case> casesRetreived = [SELECT Id, CaseNumber, Status, Type, Contact.Name, PMC_SS_AtFaultParty__c, CreatedDate 
                FROM Case WHERE PMC_SS_Order__c = :orderId ORDER BY CreatedDate DESC];
        System.debug('casesRetreived-->' + casesRetreived);
        return casesRetreived;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getOrderDetails(Id orderId) {
        Order ord = [SELECT Id, AccountId, Contract.CustomerSignedId, PMC_CPQ_SoldToAccount__c, PMC_CPQ_SAPOrderNumber__c,PMC_CPQ_PO__c,OrderNumber 
        //GSMD3234
        ,(select id,PMC_CPQ_ModeofTransportation__c,PMC_CPQ_ShipTo__r.name,PMC_CPQ_UnitOfMeasure__c,product2.name,PMC_CPQ_ConfirmedQuantity__c from orderitems  )              
        FROM Order WHERE Id = :orderId];

        Map<String, Object> result = new Map<String, Object>();
        result.put('AccountId', ord.AccountId);
        result.put('ContactId', ord.Contract.CustomerSignedId);
        result.put('PMC_SS_SoldToAccount__c', ord.AccountId);
        result.put('PMC_SS_SAPOrderNumber__c', ord.PMC_CPQ_SAPOrderNumber__c);
        result.put('PMC_SS_SNOW_OrderNumberorContractNumber__c', ord.OrderNumber);
        result.put('PMC_SS_Order__c', ord.Id);
        //Added for GSMD-1534
        result.put('Customer_Purchase_Order__c', ord.PMC_CPQ_PO__c);
        //GSMD-3234
        if(ord.orderitems!=null)
        {
            if(ord.orderitems.size()==1)
            {
                result.put('Is_MultipleOrdereItem',false);
                result.put('OrderRecord',ord.orderitems[0]);
                


            }
            if(ord.orderitems.size()>1)
            {
                result.put('Is_MultipleOrdereItem',true);
                result.put('OrderItemRecords', ord.orderitems);

            }
        }
        

        return result;
    }
}