force-app/main/default/objects/Case/fields/PMC_SS_AtFaultParty__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_AtFaultParty__c</fullName>
    <label>At Fault Party</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Logistics Planning</fullName>
            </value>
            <value>
                <fullName>Plant / Operations</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Supply Planning</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_InvoiceDifference__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_InvoiceDifference__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Delta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_OriginalInvoiceAmount__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_OriginalInvoiceAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Original Invoice Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_RebillAmount__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_RebillAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Rebill Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/PMC_SS_CaseGeneral.recordType-meta.xml
<RecordType>
    <fullName>PMC_SS_CaseGeneral</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <label>Case General</label>
</RecordType>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PMC_SS_Case_AA_EmailTemplate_ctrl_Test.cls
@isTest
public class PMC_SS_Case_AA_EmailTemplate_ctrl_Test {

    @isTest
    static void testControllerMethods() {
        
        // Create test Account
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        //Create test Contact
        Contact con = new Contact (FirstName = 'Test FName', LastName = 'Test LName', Email = 'test@test.Mosaic.com',AccountId = acc.Id);
        insert con;
        
		Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PMC_SS_CaseGeneral').getRecordTypeId();
        // Create test Case
        Case cs = new Case(
            Subject = 'Test Case Subject', 
            Description = 'Test Description',
            AccountId = acc.Id,
            ContactId = con.Id,
            PMC_SS_AtFaultParty__c = 'Customer',
            PMC_SS_OriginalInvoiceAmount__c = 456.789,
            PMC_SS_RebillAmount__c = 123.456,
            PMC_SS_InvoiceDifference__c = 333.333,
            RecordTypeId = caseRecordTypeId
        );
        insert cs;

        // Create test Users
        User approverUser = [SELECT Id,Name FROM User WHERE Profile.Name = 'System Administrator' LIMIT 1];
        User assignedToUser = approverUser;
        
        sbaa__Approver__c approver = new sbaa__Approver__c(sbaa__User__c = approverUser.Id, Name = approverUser.Name);

        // Create test sbaa__Approval__c record
        sbaa__Approval__c approval = new sbaa__Approval__c(
            sbaa__Approver__c = approver.Id,
            sbaa__AssignedTo__c = assignedToUser.Id,
            sbaa__ApprovalStep__c = 1,
            sbaa__RecordField__c = 'Case__c'
        );
        insert approval;

        // Instantiate the controller and set parameters
        Test.startTest();
        PMC_SS_Case_AA_EmailTemplate_ctrl controller = new PMC_SS_Case_AA_EmailTemplate_ctrl();
        controller.caseId = cs.Id;
        controller.approvalId = approval.Id;

        // Call methods results
        Case fetchedCase = controller.getcaseRecord();
        sbaa__Approval__c fetchedApproval = controller.getapprovalRecord();
        String caseLink = controller.getcaseLink();
        String approvalLink = controller.getapprovalLink();
        String rebillFormatted = controller.getFormattedRebillAmount();
        String originalFormatted = controller.getFormattedOriginalInvoiceAmount();
        String diffFormatted = controller.getFormattedInvoiceDifference();
        Test.stopTest();
         //Assert values
        System.assertNotEquals(null, fetchedCase);
        System.assertEquals(cs.Id, fetchedCase.Id);
        System.assertNotEquals(null, fetchedApproval);
        System.assertEquals(approval.Id, fetchedApproval.Id);
        System.assert(caseLink.contains(cs.Id));
        System.assert(approvalLink.contains(approval.Id));
        System.assertEquals('123.46', rebillFormatted);
        System.assertEquals('456.79', originalFormatted);
        System.assertEquals('333.33', diffFormatted);
    }
}