force-app/main/default/objects/Case/fields/PMC_SS_AtFaultParty__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_AtFaultParty__c</fullName>
    <label>At Fault Party</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Logistics Planning</fullName>
            </value>
            <value>
                <fullName>Plant / Operations</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Supply Planning</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_InvoiceDifference__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_InvoiceDifference__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Delta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_Location__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location</description>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Cases (Location)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_MOT__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_MOT__c</fullName>
    <description>The mode of transportation for a shipping case</description>
    <label>Mode of Transportation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barge</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_OriginalInvoiceAmount__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_OriginalInvoiceAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Original Invoice Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_RebillAmount__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_RebillAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Invoice Rebill Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PMC_SS_Case_AA_EmailTemplate_ctrl.cls
public class PMC_SS_Case_AA_EmailTemplate_ctrl {
	
    public Id caseId {get;set;}
    public Id approvalId {get;set;}
    
    public PMC_SS_Case_AA_EmailTemplate_ctrl() {}
    
    public Case getcaseRecord(){
        System.Debug('caseRecord PRT1**: '+this.caseId);
        if (this.caseId != null) {
			return [SELECT Id, CaseNumber, Subject, Description,
                          Account.Name,
                          PMC_SS_AtFaultParty__c,
                          PMC_SS_Location__r.Name,
                          PMC_SS_OriginalInvoiceAmount__c,
                          PMC_SS_RebillAmount__c,
                          PMC_SS_InvoiceDifference__c,
                          PMC_SS_MOT__c,
                          CreatedBy.Name
                          FROM Case
                          WHERE Id = :this.caseId
                          LIMIT 1];
        }
        
        return null;
    }
    
    public sbaa__Approval__c getapprovalRecord(){
        if(approvalId != null){
            return [SELECT Id,Name,Owner.Name,LastModifiedDate,sbaa__RejectedBy__r.Name,sbaa__CommentsLong__c,sbaa__Approver__r.Name,sbaa__AssignedTo__r.Name,sbaa__Approver__r.LastModifiedDate,CreatedBy.name FROM sbaa__Approval__c WHERE Id=:this.approvalId];
        }
        return null;
    }
    
    public String getcaseLink() {
        return URL.getOrgDomainURL().toExternalForm() + '/' + this.caseId;
    }
    
    public String getapprovalLink() {
        return URL.getOrgDomainURL().toExternalForm() + '/' + this.approvalId;
    }
   public String getFormattedRebillAmount() {
   return (getcaseRecord()?.PMC_SS_RebillAmount__c != null)
       ? String.valueOf(getcaseRecord().PMC_SS_RebillAmount__c.setScale(2, RoundingMode.HALF_UP)): '';
   }
public String getFormattedOriginalInvoiceAmount() {
   return (getcaseRecord()?.PMC_SS_OriginalInvoiceAmount__c != null)
       ? String.valueOf(getcaseRecord().PMC_SS_OriginalInvoiceAmount__c.setScale(2, RoundingMode.HALF_UP)): '';
}
public String getFormattedInvoiceDifference() {
   return (getcaseRecord()?.PMC_SS_InvoiceDifference__c != null)
       ? String.valueOf(getcaseRecord().PMC_SS_InvoiceDifference__c.setScale(2, RoundingMode.HALF_UP)): '';
}
}