force-app/main/default/objects/Case/fields/PMC_SS_AtFaultParty__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_AtFaultParty__c</fullName>
    <label>At Fault Party</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Logistics Planning</fullName>
            </value>
            <value>
                <fullName>Plant / Operations</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Supply Planning</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
            <value>
                <fullName>Warehouse</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_IssueReason__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_IssueReason__c</fullName>
    <description>Specifies the reason of the issue</description>
    <inlineHelpText>Contract Cancellation, Product request, Credit Request, Financial Solution and Anticipated Billing are for Brazil users ONLY...</inlineHelpText>
    <label>Issue Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Issues</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Banking Edits</fullName>
            </value>
            <value>
                <fullName>Call by Date</fullName>
            </value>
            <value>
                <fullName>Cambio Exhange</fullName>
            </value>
            <value>
                <fullName>Change to loading priorities</fullName>
            </value>
            <value>
                <fullName>COA Setup / Change</fullName>
            </value>
            <value>
                <fullName>Consignment</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
                <label>Contract Cancellation</label>
            </value>
            <value>
                <fullName>Credit Note Request</fullName>
            </value>
            <value>
                <fullName>Credit Request</fullName>
            </value>
            <value>
                <fullName>Customer Issue</fullName>
            </value>
            <value>
                <fullName>Deactivation</fullName>
            </value>
            <value>
                <fullName>Debit Note Request</fullName>
            </value>
            <value>
                <fullName>Delivery Delay</fullName>
            </value>
            <value>
                <fullName>Demurrage</fullName>
            </value>
            <value>
                <fullName>Diversion</fullName>
            </value>
            <value>
                <fullName>Document Request</fullName>
            </value>
            <value>
                <fullName>Donation Order/Bonus</fullName>
            </value>
            <value>
                <fullName>Driver Verification/Change</fullName>
            </value>
            <value>
                <fullName>Equipment Failure</fullName>
            </value>
            <value>
                <fullName>Export Documentation</fullName>
            </value>
            <value>
                <fullName>Export prioritization</fullName>
            </value>
            <value>
                <fullName>Financial Solution</fullName>
            </value>
            <value>
                <fullName>IDOC Failures</fullName>
            </value>
            <value>
                <fullName>Include Script CIF</fullName>
            </value>
            <value>
                <fullName>Incorrect Destination</fullName>
            </value>
            <value>
                <fullName>Incorrect Label</fullName>
            </value>
            <value>
                <fullName>Incorrect Product</fullName>
            </value>
            <value>
                <fullName>Incorrect UOM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_Location__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Location</description>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Cases (Location)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMC_SS_MOT__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_MOT__c</fullName>
    <description>The mode of transportation for a shipping case</description>
    <label>Mode of Transportation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barge</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Truck</fullName>
            </value>
            <value>
                <fullName>Vessel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location/recordTypes/PMC_CPQ_Origin_Location.recordType-meta.xml
<RecordType>
    <fullName>PMC_CPQ_Origin_Location</fullName>
    <active>true</active>
    <description>This record type created to customize Origin record user interface</description>
    <label>Origin Location</label>
</RecordType>

force-app/main/default/objects/PMC_ProcessSwitches__c/PMC_ProcessSwitches__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Custom Setting is for implementing bypass framework for triggers, flows, integrations and validation rules.</description>
    <label>Process Switches</label>
</CustomObject>

force-app/main/default/objects/PMC_ProcessSwitches__c/fields/PMC_BypassFlow__c.field-meta.xml
<CustomField>
    <fullName>PMC_BypassFlow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to bypass the flows.</description>
    <label>Bypass Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PMC_DH_CaseUtilTest.cls
/**
* @author @hemant.giri
* @description test class for Case
* @since 06-14-2023
*/
@isTest
public with sharing class PMC_DH_CaseUtilTest {

    private static void enableFlowBypassForCurrentUser() {
        PMC_ProcessSwitches__c cs = PMC_ProcessSwitches__c.getInstance();
        if (cs == null) cs = new PMC_ProcessSwitches__c();
        cs.PMC_ByPassFlow__c = true;
        upsert cs;
    }

    /**
    * @description test setup method
    * @since 06-15-2023
    * @author hemant giri goswami
    */
    @testSetup
    public static void testData(){
        User userAdmin = PMC_DH_TestDataFactoryClass.createAdminUser();
        User usr;
        Account acc1;
        BusinessHours bh = [SELECT Name, Id FROM BusinessHours WHERE Name = 'Default' LIMIT 1];

        System.runAs(userAdmin) {
            acc1 = PMC_DH_TestDataFactoryClass.createParentTestAccount();
            PMC_DH_TestDataFactoryClass.createTestContact(acc1.Id);
            Profile profile = [SELECT Id FROM Profile WHERE Name = :PMC_DH_ConstantClass.PROFILE_NAME LIMIT 1];
            PMC_DH_TestDataFactoryClass.createTestUser(acc1.Id, profile.Id);
            usr = [SELECT Id, ContactId FROM User WHERE UserName = 'demouser@test.com.testuser' LIMIT 1];

            Id psDHCPQ = [SELECT Id FROM PermissionSet WHERE Name = 'PMC_DH_CPQ_PermissionSetLicense' LIMIT 1].Id;
            PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(usr.Id, psDHCPQ);

            Id psSteelBrick = [SELECT Id FROM PermissionSet WHERE Name = 'SteelBrickDHCPQPartnerUser' LIMIT 1].Id;
            PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(usr.Id, psSteelBrick);

            Id psSuperBuyer = [SELECT Id FROM PermissionSet WHERE Name = 'PMC_DH_SuperBuyer' LIMIT 1].Id;
            PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(usr.Id, psSuperBuyer);

            Id psAccountCRE = [SELECT Id FROM PermissionSet WHERE Name = 'PMC_DH_AccountCRE' LIMIT 1].Id;
            PMC_DH_TestDataFactoryClass.assignPermissionSetToUser(usr.Id, psAccountCRE);
        }

        System.runAs(usr){
            PMC_DH_TestDataFactoryClass.createCaseRecord(acc1.Id, usr.ContactId, bh.Id);
        }
    }

    /**
    * @description test method for reopen case
    * @author Ajeet
    */
    @isTest
    public static void reopenCaseTest() {
        User usr = [SELECT Id FROM User WHERE UserName = 'demouser@test.com.testuser' LIMIT 1];

        Test.startTest();
        System.runAs(usr) {
            enableFlowBypassForCurrentUser();

            Id originLocRtId = [
                SELECT Id
                FROM RecordType
                WHERE SObjectType = 'Location'
                AND DeveloperName = 'PMC_CPQ_Origin_Location'
                LIMIT 1
            ].Id;

            Schema.SObjectType locType = Schema.getGlobalDescribe().get('Location');
            SObject locRec = locType.newSObject();
            locRec.put('Name', 'test name');
            locRec.put('LocationType', 'Plant');
            locRec.put('RecordTypeId', originLocRtId);
            insert locRec;

            Case caseObjRecord = [SELECT CaseNumber, Id, ClosedDate, Subject FROM Case WHERE Status = 'New' WITH SECURITY_ENFORCED LIMIT 1];
            caseObjRecord.PMC_SS_IssueReason__c = 'Delivery delay';
            caseObjRecord.Status = 'Closed';
            caseObjRecord.PMC_SS_Location__c = (Id)locRec.get('Id');
            caseObjRecord.PMC_SS_MOT__c = 'Truck';
            caseObjRecord.PMC_SS_AtFaultParty__c = 'Customer';
            update caseObjRecord;

            PMC_DH_CaseUtil.isEligibleToUploadDoc(caseObjRecord.Id);
            PMC_DH_CaseUtil.getDependentPicklistValues(Case.PMC_SS_IssueReason__c);

            PMC_DH_CaseUtil.CaseWrapper wrp1 = new PMC_DH_CaseUtil.CaseWrapper();
            wrp1.strCaseId = caseObjRecord.Id;
            wrp1.strReason = 'Resolution Not Accurate';
            wrp1.strOthersComment = 'Test';

            PMC_DH_DigitalHubB2BUtils.PMC_DH_StatusCodeMessageWrapper result = PMC_DH_CaseUtil.reopenCase(wrp1);
            System.assert(result != null, 'Success');
        }
        Test.stopTest();
    }

    /**
    * @description test method for reopen case exception
    * @author Hemant
    */
    @isTest
    public static void reopenCaseExceptionTest() {
        User usr = [SELECT Id FROM User WHERE UserName = 'demouser@test.com.testuser' LIMIT 1];

        Test.startTest();
        System.runAs(usr) {
            enableFlowBypassForCurrentUser();

            Boolean isException;
            try {
                Case caseObjRecord = [SELECT CaseNumber, Id, ClosedDate, Subject FROM Case WHERE Status = 'New' WITH SECURITY_ENFORCED LIMIT 1];
                caseObjRecord.PMC_SS_IssueReason__c = 'Delivery delay';
                caseObjRecord.Status = 'Pending';
                isException = false;
                update caseObjRecord;

                PMC_DH_CaseUtil.CaseWrapper wrp1 = new PMC_DH_CaseUtil.CaseWrapper();
                wrp1.strCaseId = caseObjRecord.Id;
                wrp1.strReason = 'Resolution Not Accurate';
                wrp1.strOthersComment = '';
                PMC_DH_CaseUtil.reopenCase(wrp1);

                PMC_DH_CaseUtil.boolThrow = true;
                PMC_DH_CaseUtil.reopenCase(wrp1);
            } catch (Exception ex) {
                isException = true;
            }
            System.assert(isException != null, 'Exception Handled');
        }
        Test.stopTest();
    }

    /**
    * @description test method for reopen case List
    * @author Hemant
    */
    @isTest
    public static void getReopenReasonListTest() {
        List<PMC_DH_PicklistWrapper> wrp = PMC_DH_CaseUtil.getReopenReasonList();
        System.assert(wrp != null, 'Success');
    }
}