force-app/main/default/objects/Order/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <description>This field captures the order number in SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
    <label>SAP Order Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Line_Approval__c/Order_Line_Approval__c.object-meta.xml
<CustomObject>
    <label>Order Line Approval</label>
    <nameField>
        <displayFormat>OLA{0000}</displayFormat>
        <label>Order Line Approval Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Approval__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Approval__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Line</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Line Approvals</relationshipLabel>
    <relationshipName>Order_Line_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Approval__c/fields/PMC_CPQ_AboveCeiling_Approval_Required__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_AboveCeiling_Approval_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Above Ceiling Approval Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Agreed_Final_Price__c.field-meta.xml
<CustomField>
    <fullName>Agreed_Final_Price__c</fullName>
    <description>Agreed Final price to be filled on the order line record - GCPM - 2908</description>
    <label>Agreed Final Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Flow Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Under Revision</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_EstFreightPrice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_EstFreightPrice__c</fullName>
    <label>Freight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_FinalAgreedPrice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FinalAgreedPrice__c</fullName>
    <description>This field is will store the Final Agreed Price and send it back to SAP after the Order is placed.</description>
    <label>Final Agreed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_Floorplusfreight__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Floorplusfreight__c</fullName>
    <formula>PMC_CPQ_Floorprice__c + PMC_CPQ_EstFreightPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Floor Price + Freight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_FPDPricefromPriceFx__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FPDPricefromPriceFx__c</fullName>
    <description>Created as part of GDASF-9360. This field captures the FPD price from Price Fx.</description>
    <inlineHelpText>The FPD List Price for the Order Product is only relevant when the contract type of the product is specified as FPD</inlineHelpText>
    <label>FPD List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_LinePONumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_LinePONumber__c</fullName>
    <description>This field will be used to capture the PO Number at a order line level - leveraged in the Contract Document forms for North America</description>
    <label>Customer Purchase Order #</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_OrderItemIntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderItemIntegrationMessage__c</fullName>
    <description>The Integration message of external callout.</description>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_OrderItemIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderItemIntegrationStatus__c</fullName>
    <description>This field captures the integration status of the Order product</description>
    <inlineHelpText>This field captures the integration status of the Order product</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_OrderLineStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderLineStatus__c</fullName>
    <label>Order Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Completely Shipped</fullName>
                <isActive>false</isActive>
                <label>Completely Shipped</label>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
                <isActive>false</isActive>
                <label>Partially Shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_PriceGuidanceCeiling__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PriceGuidanceCeiling__c</fullName>
    <description>Created as part of GCPM-4521</description>
    <label>Ceiling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_PricingDate__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PricingDate__c</fullName>
    <description>This field captures Pricing date.</description>
    <inlineHelpText>This field captures the pricing date</inlineHelpText>
    <label>Price by Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_ShipTo__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShipTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order Products (Ship To)</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/SendIntegrationResultEmail__c.field-meta.xml
<CustomField>
    <fullName>SendIntegrationResultEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Integration Result Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Sent_to_SAP_By__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_SAP_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sent to SAP By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LinesSentToSAP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/PMC_CPQ_Integration_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/fields/PMC_CPQ_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Endpoint__c</fullName>
    <description>This is used to store the Integration endpoint.</description>
    <label>Endpoint</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Order_Line_Approval__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Line Approval</label>
    <referenceTo>Order_Line_Approval__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderItem</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/PMC_CPQ_EstFreightPrice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_EstFreightPrice__c</fullName>
    <formula>OrderItem__r.PMC_CPQ_EstFreightPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Freight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/PMC_CPQ_FinalAgreedPrice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FinalAgreedPrice__c</fullName>
    <formula>OrderItem__r.PMC_CPQ_FinalAgreedPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Agreed Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/PMC_CPQ_Floorplusfreight__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Floorplusfreight__c</fullName>
    <formula>IF($Permission.View_OrderLine_FloorPrice, OrderItem__r.PMC_CPQ_Floorplusfreight__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Floor Price + Freight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/PMC_CPQ_FPDPricefromPriceFx__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FPDPricefromPriceFx__c</fullName>
    <formula>OrderItem__r.PMC_CPQ_FPDPricefromPriceFx__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FPD List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <formula>OrderItem__r.Order.PMC_CPQ_SAPOrderNumber__c</formula>
    <label>SAP Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/PMC_CPQ_SendEmail__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SendEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Status__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Status__c</fullName>
    <description>Status of this approval.</description>
    <inlineHelpText>Status of this approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PMC_CPQ_sendFPDOrderProductsSAPClass.cls
/**
 * @description This class will be used to receive order products from fpdMassUpdate lightning web component and process it and send to SAP or receive
 * price from PriceFX
 * @storynumber GDASF-9421
 */
public without sharing class PMC_CPQ_sendFPDOrderProductsSAPClass {
	/**
	 * @description Common method to fetch OrderItems based on a list of IDs
	 * @param idOps - List of id for which the OrderItem record is to be returned
	 * @return - the result of the SOQL query
	 */
	@TestVisible
	private static List<OrderItem> fetchOrderItems(List<Id> idOps) {
		return [
			SELECT
				Id,
				OrderItemNumber,
				OrderId,
				Order.OrderNumber,
				SBQQ__Contract__r.PMC_CPQ_ContractNumberIdentifier__c,
				PMC_CPQ_LinePONumber__c,
				PMC_CPQ_ShipTo__r.Name,
				Order.AccountId,
				Order.Account.Name,
				Product2.Name,
				Quantity,
				PMC_CPQ_PricingDate__c,
				PMC_CPQ_Floorplusfreight__c,
				PMC_CPQ_FPDPricefromPriceFx__c,
				PMC_CPQ_FinalAgreedPrice__c,
				PMC_CPQ_PriceGuidanceCeiling__c,
				PMC_CPQ_EstFreightPrice__c,
				PMC_CPQ_OrderLineStatus__c,
				PMC_CPQ_OrderItemIntegrationStatus__c,
				PMC_CPQ_OrderItemIntegrationMessage__c,
				ApprovalStatus__c,
				Order.PMC_CPQ_SAPOrderNumber__c,
				(
					SELECT Id, sbaa__Status__c
					FROM Approvals__r
					ORDER BY CreatedDate DESC
					LIMIT 1
				)
			FROM OrderItem
			WHERE Id IN :idOps
		];
	}

	/**
	 * @description This method will be used to send Order products to SAP with negotiated Final Agreed Price
	 * @param lstOlines - String of List of Order Products sent from LWC component or Send To SAP from Order Product RecordPage
	 */
	@AuraEnabled
	public static String saveOPFromUI(String lstOlines) {
		return saveOPFromUI(lstOlines, 'Save and Send to SAP: FPD Component button click.');
	}

	public static String saveOPFromUI(String lstOlines, String sourceIntegrationMessage) {
		Set<Id> recallOrderItems = new Set<Id>();
		Set<Id> approvalRequestOrderItems = new Set<Id>();
		List<PMC_CPQ_OrderProductDetailsWrapperClass> params = (List<PMC_CPQ_OrderProductDetailsWrapperClass>) JSON.deserialize(
			lstOlines,
			List<PMC_CPQ_OrderProductDetailsWrapperClass>.class
		);
		List<Id> idOps = new List<Id>();
		for (PMC_CPQ_OrderProductDetailsWrapperClass wrapper : params) {
			idOps.add(wrapper.customId);
		}
		Map<Id, OrderItem> mapOrderItems = new Map<Id, OrderItem>(fetchOrderItems(idOps));
		for (Integer i = 0; i < params.size(); i++) {
			OrderItem oItem = mapOrderItems.get(params[i].customId);
			Decimal finalAgreedPrice = params[i].finalAgreedPrice != null ? params[i].finalAgreedPrice : 0;

			oItem.PMC_CPQ_FinalAgreedPrice__c = finalAgreedPrice;
			oItem.Agreed_Final_Price__c = finalAgreedPrice;
			oItem.PMC_CPQ_OrderItemIntegrationMessage__c = sourceIntegrationMessage;
			if (requiresApproval(oItem, finalAgreedPrice)) {
				oItem.ApprovalStatus__c = 'Pending Approval';
				oItem.PMC_CPQ_OrderItemIntegrationMessage__c = 'Approval Require';
				approvalRequestOrderItems.add(oItem.Id);
			} else if (oItem.Quantity > 0 && finalAgreedPrice > 0) {
				recallOrderItems.add(oItem.Id);
				oItem.Sent_to_SAP_By__c = UserInfo.getUserId();
				oItem.SendIntegrationResultEmail__c = true;
				oItem.ApprovalStatus__c = 'Approved';
				oItem.PMC_CPQ_OrderItemIntegrationMessage__c = sourceIntegrationMessage + 'Save and Send to SAP: Automatic Approval';
			}
		}

		try {
			if (
				Schema.sObjectType.OrderItem.isAccessible() &&
				Schema.sObjectType.OrderItem.isUpdateable() &&
				Schema.SObjectType.OrderItem.fields.PMC_CPQ_FinalAgreedPrice__c.isUpdateable()
			) {
				if (!approvalRequestOrderItems.isEmpty()) {
					List<SBAA__Approval__c> approvalsToRecall = [
						SELECT
							Id,
							OrderItem__r.OrderId,
							sbaa__Approver__r.sbaa__User__c,
							sbaa__Approver__r.sbaa__GroupId__c,
							sbaa__Status__c
						FROM SBAA__Approval__c
						WHERE OrderItem__c IN :approvalRequestOrderItems AND sbaa__Status__c = 'Requested'
					];

					if (!approvalsToRecall.isEmpty()) {
						Map<Id, Set<Id>> orderIdToUserIds = new Map<Id, Set<Id>>();
						Set<Id> groupIdsToQuery = new Set<Id>();

						for (SBAA__Approval__c approval : approvalsToRecall) {
							approval.sbaa__Status__c = 'Recalled';
						}
						update approvalsToRecall;
					}
				}
				OrderItemTriggerHandler.boolBypassTriggerLogic = true;
				SBQQ.TriggerControl.disable();
				update mapOrderItems.values();
				SBQQ.TriggerControl.enable();
				OrderItemTriggerHandler.boolBypassTriggerLogic = false;
				if (!approvalRequestOrderItems.isEmpty()) {
					orderItemsApprovalRequestsSendEmails(JSON.serialize(approvalRequestOrderItems));
				}

				if (!recallOrderItems.isEmpty()) {
					recallApprovalsAndNotify(JSON.serialize(recallOrderItems));
				}
			}
		} catch (DmlException objException) {
			PMC_ErrorLogClass.processException(objException);
			return 'Error saving Order Products : ' + objException.getMessage();
		}
		return sendOrderProductsToSAP(mapOrderItems.values());
	}

	@Future
	public static void recallApprovalsAndNotify(String strApprovalRequestOrderItems) {
		Set<Id> orderItemIds = (Set<Id>) JSON.deserialize(strApprovalRequestOrderItems, Set<Id>.class);
		List<SBAA__Approval__c> approvalsToRecall = [
			SELECT Id, OrderItem__r.OrderId, sbaa__Approver__r.sbaa__User__c, sbaa__Approver__r.sbaa__GroupId__c, sbaa__Status__c
			FROM SBAA__Approval__c
			WHERE OrderItem__c IN :orderItemIds AND sbaa__Status__c = 'Requested'
		];

		if (approvalsToRecall.isEmpty()) {
			return;
		}

		Map<Id, Set<Id>> orderIdToUserIds = new Map<Id, Set<Id>>();
		Set<Id> groupIdsToQuery = new Set<Id>();

		for (SBAA__Approval__c approval : approvalsToRecall) {
			approval.sbaa__Status__c = 'Recalled';
			approval.PMC_CPQ_SendEmail__c = true;
			if (String.isBlank(approval.sbaa__Approver__r.sbaa__User__c)) {
				groupIdsToQuery.add(approval.sbaa__Approver__r.sbaa__GroupId__c);
			}
		}

		Map<Id, List<GroupMember>> groupIdToMembers = new Map<Id, List<GroupMember>>();
		if (!groupIdsToQuery.isEmpty()) {
			for (GroupMember gm : [
				SELECT GroupId, UserOrGroupId
				FROM GroupMember
				WHERE GroupId IN :groupIdsToQuery
			]) {
				if (!groupIdToMembers.containsKey(gm.GroupId)) {
					groupIdToMembers.put(gm.GroupId, new List<GroupMember>());
				}
				groupIdToMembers.get(gm.GroupId).add(gm);
			}
		}

		for (SBAA__Approval__c approval : approvalsToRecall) {
			Id orderId = approval.OrderItem__r.OrderId;
			Set<Id> userIds = orderIdToUserIds.containsKey(orderId) ? orderIdToUserIds.get(orderId) : new Set<Id>();
			if (String.isNotBlank(approval.sbaa__Approver__r.sbaa__User__c)) {
				userIds.add(approval.sbaa__Approver__r.sbaa__User__c);
			} else if (groupIdToMembers.containsKey(approval.sbaa__Approver__r.sbaa__GroupId__c)) {
				for (GroupMember gm : groupIdToMembers.get(approval.sbaa__Approver__r.sbaa__GroupId__c)) {
					userIds.add(gm.UserOrGroupId);
				}
			}
			if (!userIds.isEmpty()) {
				orderIdToUserIds.put(orderId, userIds);
			}
		}
		update approvalsToRecall;
		if (!orderIdToUserIds.isEmpty()) {
			EmailUtils.sendApprovalRecallEmails(JSON.serialize(orderIdToUserIds));
		}
	}

	@Future
	public static void orderItemsApprovalRequestsSendEmails(String strApprovalRequestOrderItems) {
		Set<Id> orderItemIds = (Set<Id>) JSON.deserialize(strApprovalRequestOrderItems, Set<Id>.class);
		Map<Id, Set<Id>> orderIdToUserIds = new Map<Id, Set<Id>>();
		Map<Id, Set<Id>> aboveCeilingOrderIdToUserIds = new Map<Id, Set<Id>>();
		Set<Id> groupIdsToQuery = new Set<Id>();

		List<SBAA__Approval__c> approvalsToUpdate = [
			SELECT Id, sbaa__Approver__r.sbaa__GroupId__c, sbaa__Approver__r.sbaa__User__c, PMC_CPQ_SendEmail__c, OrderItem__r.OrderId,
				Order_Line_Approval__r.PMC_CPQ_AboveCeiling_Approval_Required__c
			FROM SBAA__Approval__c
			WHERE OrderItem__c IN :orderItemIds
		];

		for (SBAA__Approval__c approval : approvalsToUpdate) {
			if (String.isBlank(approval.sbaa__Approver__r.sbaa__User__c)) {
				groupIdsToQuery.add(approval.sbaa__Approver__r.sbaa__GroupId__c);
			}
			approval.PMC_CPQ_SendEmail__c = true;
		}

		Map<Id, List<GroupMember>> groupIdToMembers = new Map<Id, List<GroupMember>>();
		if (!groupIdsToQuery.isEmpty()) {
			for (GroupMember gm : [
				SELECT GroupId, UserOrGroupId
				FROM GroupMember
				WHERE GroupId IN :groupIdsToQuery
			]) {
				if (!groupIdToMembers.containsKey(gm.GroupId)) {
					groupIdToMembers.put(gm.GroupId, new List<GroupMember>());
				}
				groupIdToMembers.get(gm.GroupId).add(gm);
			}
		}

		for (SBAA__Approval__c approval : approvalsToUpdate) {
			Id orderId = approval.OrderItem__r.OrderId;

			Boolean isAboveCeiling = approval.Order_Line_Approval__r.PMC_CPQ_AboveCeiling_Approval_Required__c;

			if (!isAboveCeiling) {
				Set<Id> userIds = orderIdToUserIds.containsKey(orderId) ? orderIdToUserIds.get(orderId) : new Set<Id>();
				if (String.isNotBlank(approval.sbaa__Approver__r.sbaa__User__c)) {
					userIds.add(approval.sbaa__Approver__r.sbaa__User__c);
				} else if (groupIdToMembers.containsKey(approval.sbaa__Approver__r.sbaa__GroupId__c)) {
					for (GroupMember gm : groupIdToMembers.get(approval.sbaa__Approver__r.sbaa__GroupId__c)) {
						userIds.add(gm.UserOrGroupId);
					}
				}

				if (!userIds.isEmpty()) {
					orderIdToUserIds.put(orderId, userIds);
				}
			} else {
				Set<Id> aboveCeilingUserIds = aboveCeilingOrderIdToUserIds.containsKey(orderId)
					? aboveCeilingOrderIdToUserIds.get(orderId)
					: new Set<Id>();
				if (String.isNotBlank(approval.sbaa__Approver__r.sbaa__User__c)) {
					aboveCeilingUserIds.add(approval.sbaa__Approver__r.sbaa__User__c);
				} else if (groupIdToMembers.containsKey(approval.sbaa__Approver__r.sbaa__GroupId__c)) {
					for (GroupMember gm : groupIdToMembers.get(approval.sbaa__Approver__r.sbaa__GroupId__c)) {
						aboveCeilingUserIds.add(gm.UserOrGroupId);
					}
				}

				if (!aboveCeilingUserIds.isEmpty()) {
					aboveCeilingOrderIdToUserIds.put(orderId, aboveCeilingUserIds);
				}
			}
		}

		if (!approvalsToUpdate.isEmpty()) {
			update approvalsToUpdate;
		}

		if (!orderIdToUserIds.isEmpty()) {
			EmailUtils.sendApprovalRequestEmails(JSON.serialize(orderIdToUserIds));
		}
		if (!aboveCeilingOrderIdToUserIds.isEmpty()) {
			EmailUtils.sendFPDAboveCeilingApprovalRequestEmails(JSON.serialize(aboveCeilingOrderIdToUserIds));
		}
	}

	/**
	 * @description This method will be used to send Order products to SAP with negotiated Final Agreed Price and this function will block to send to SAP if Order products status is Pending Approval and Rejected
	 * @param lstOP - List of Order Products
	 */
	@AuraEnabled
	public static String sendOrderProductsToSAP(List<OrderItem> lstOP) {
		//GCPM-2008 - SAA Start
		PMC_CPQ_FPDActionClass objRef = new PMC_CPQ_FPDActionClass(lstOP, true);
		List<OrderItem> lstOrdItemApp = [
			SELECT id, ApprovalStatus__c, PMC_CPQ_OrderItemIntegrationMessage__c
			FROM OrderItem
			WHERE ID IN :lstOP
		];
		List<OrderItem> lstToUpdateIntegration = new List<OrderItem>();
		List<OrderItem> lstToIntegrate = new List<OrderItem>();
		String message = '';
		for (OrderItem lstOrdItem : lstOrdItemApp) {
			if (lstOrdItem.ApprovalStatus__c == 'Approved') {
				lstToIntegrate.add(lstOrdItem);
			} else {
				lstOrdItem.PMC_CPQ_OrderItemIntegrationMessage__c = 'Approval Require';
				lstToUpdateIntegration.add(lstOrdItem);
			}
		}
		if (!lstToIntegrate.isEmpty()) {
			objRef.bulkSendFPDtoSAPRequest(lstToIntegrate);
		}
		try {
			if (!lstToUpdateIntegration.isEmpty()) {
				update lstToUpdateIntegration;
				message = 'One or more selected Orders Lines have been sent to PM for approval.';
			}
		} catch (DmlException e) {
			message = 'Error Updating Order Item : ' + e.getMessage();
			PMC_ErrorLogClass.processException(e);
		}
		return message;

		//GCPM-2008 - SAA End
	}

	/**
	 * @description This method will be used to receive the latest price of selected order products from the Price FPD Order Line tab
	 * @param lstOlines - String of List of Order Products sent from LWC component
	 */
	@AuraEnabled
	public static void getPriceFromPriceFX(String lstOlines) {
		List<PMC_CPQ_OrderProductDetailsWrapperClass> params = (List<PMC_CPQ_OrderProductDetailsWrapperClass>) JSON.deserialize(
			lstOlines,
			List<PMC_CPQ_OrderProductDetailsWrapperClass>.class
		);
		List<Id> idOps = new List<Id>();
		for (PMC_CPQ_OrderProductDetailsWrapperClass wrapper : params) {
			idOps.add(wrapper.customId);
		}
		List<OrderItem> lstOP = fetchOrderItems(idOps);
		PMC_CPQ_GetFPDController objRef1 = new PMC_CPQ_GetFPDController(lstOP, true);
		objRef1.bulkGetFPDRequest(lstOP);
	}

	/**
	 * @description This method will retrieve the interface url from the PMC_CPQ_Integration_Endpoint__mdt
	 * @return endpoint- the interface URL string
	 */
	@AuraEnabled(cacheable=true)
	public static string sendFPDPriceFXURL() {
		String strInterface = 'SendFPD';
		PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface);
		String endpoint = JSON.serialize(strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c);
		return endpoint;
	}

	//added by Monika 05-09

	@AuraEnabled
	public static Map<String, List<PMC_CPQ_OrderProductDetailsWrapperClass>> getRowsForProcessing(
		List<Id> selectedIds,
		Map<Id, Decimal> updatedPrices
	) {
		List<PMC_CPQ_OrderProductDetailsWrapperClass> approvalRows = new List<PMC_CPQ_OrderProductDetailsWrapperClass>();
		List<PMC_CPQ_OrderProductDetailsWrapperClass> nonApprovalRows = new List<PMC_CPQ_OrderProductDetailsWrapperClass>();

		Map<Id, OrderItem> mapOrderItems = new Map<Id, OrderItem>(fetchOrderItems(selectedIds));
		for (Id id : selectedIds) {
			OrderItem oItem = mapOrderItems.get(id);

			PMC_CPQ_OrderProductDetailsWrapperClass row = convertOrderItemToWrapper(oItem); // helper to map OrderItem to wrapper
			//added
			if (updatedPrices != null && updatedPrices.containsKey(id)) {
				row.finalAgreedPrice = updatedPrices.get(id);
			}

			Decimal finalAgreedPrice = row.finalAgreedPrice != null ? row.finalAgreedPrice : 0;

			if (requiresApproval(oItem, finalAgreedPrice)) {
				approvalRows.add(row);
			} else {
				nonApprovalRows.add(row);
			}
		}

		Map<String, List<PMC_CPQ_OrderProductDetailsWrapperClass>> result = new Map<String, List<PMC_CPQ_OrderProductDetailsWrapperClass>>();
		result.put('approvalRows', approvalRows);
		result.put('nonApprovalRows', nonApprovalRows);
		return result;
	}

	@TestVisible
	private static PMC_CPQ_OrderProductDetailsWrapperClass convertOrderItemToWrapper(OrderItem oItem) {
		PMC_CPQ_OrderProductDetailsWrapperClass wrap = new PMC_CPQ_OrderProductDetailsWrapperClass();
		wrap.customId = oItem.Id;
		wrap.quantity = oItem.Quantity;
		wrap.finalAgreedPrice = oItem.PMC_CPQ_FinalAgreedPrice__c;
		wrap.productName = oItem.Product2.Name;
		wrap.orderNum = oItem.Order.OrderNumber;
		wrap.contractNum = oItem.SBQQ__Contract__r != null ? oItem.SBQQ__Contract__r.PMC_CPQ_ContractNumberIdentifier__c : null;
		wrap.freight = oItem.PMC_CPQ_EstFreightPrice__c;
		wrap.integrationMessage = oItem.PMC_CPQ_OrderItemIntegrationMessage__c;
		wrap.approvalStatus = oItem.ApprovalStatus__c;
		wrap.sapOrderNumber = oItem.Order.PMC_CPQ_SAPOrderNumber__c;
		return wrap;
	}

	/**
	 * @description Centralized approval requirement logic to avoid duplication and guarantee consistent criteria.
	 * Criteria: Quantity > 10000 OR Final Agreed Price below Floor+Freight OR (Final Agreed Price - Freight) above Ceiling
	 * Null numeric fields are treated as zero.
	 * @param oItem - OrderItem record (must include Quantity, PMC_CPQ_Floorplusfreight__c, PMC_CPQ_PriceGuidanceCeiling__c, PMC_CPQ_EstFreightPrice__c)
	 * @param finalAgreedPrice - Decimal (already defaulted to 0 if null by caller)
	 * @return Boolean indicating whether approval is required
	 */
	private static Boolean requiresApproval(OrderItem oItem, Decimal finalAgreedPrice) {
		Decimal floorPlusFreight = oItem.PMC_CPQ_Floorplusfreight__c != null ? oItem.PMC_CPQ_Floorplusfreight__c : 0;
		Decimal ceilingPrice = oItem.PMC_CPQ_PriceGuidanceCeiling__c != null ? oItem.PMC_CPQ_PriceGuidanceCeiling__c : 0;
		Decimal freightPrice = oItem.PMC_CPQ_EstFreightPrice__c != null ? oItem.PMC_CPQ_EstFreightPrice__c : 0;
		return (oItem.Quantity > 10000 || finalAgreedPrice < floorPlusFreight || (finalAgreedPrice - freightPrice) > ceilingPrice);
	}
}