force-app/main/default/objects/Order/fields/PMC_CPQ_PO__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PO__c</fullName>
    <description>This field is used to capture the user input for Purchase order number.</description>
    <inlineHelpText>Purchase Order number for this order.</inlineHelpText>
    <label>Customer Purchase Order #</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <description>This field captures the order number in SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
    <label>SAP Order Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/PMC_Shipment_Data__c.object-meta.xml
<CustomObject>
    <label>Shipment Data</label>
    <nameField>
        <label>Shipment Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/DaysNotMoved__c.field-meta.xml
<CustomField>
    <fullName>DaysNotMoved__c</fullName>
    <label>Days Not Moved</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/Intransit_Status__c.field-meta.xml
<CustomField>
    <fullName>Intransit_Status__c</fullName>
    <label>Intransit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intransit_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_BOL__c.field-meta.xml
<CustomField>
    <fullName>PMC_BOL__c</fullName>
    <label>BOL</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_BOLNUMBER__c.field-meta.xml
<CustomField>
    <fullName>PMC_BOLNUMBER__c</fullName>
    <label>BOLNUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_COMMENTS__c.field-meta.xml
<CustomField>
    <fullName>PMC_COMMENTS__c</fullName>
    <label>COMMENTS</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_CPQ_CurrentCoordinates__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CurrentCoordinates__c</fullName>
    <label>CurrentCoordinates</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_CPQ_SAPDeliveryID__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
    <label>Delivery Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_CPQ_Shipment_PO__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Shipment_PO__c</fullName>
    <externalId>true</externalId>
    <label>Shipment PO</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_CPQ_ShipmentNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShipmentNumber__c</fullName>
    <label>Shipment Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_CURRENTCARRIER__c.field-meta.xml
<CustomField>
    <fullName>PMC_CURRENTCARRIER__c</fullName>
    <label>CURRENTCARRIER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_CURRENTLOCATION__c.field-meta.xml
<CustomField>
    <fullName>PMC_CURRENTLOCATION__c</fullName>
    <label>CURRENTLOCATION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_CUSTORDERNO__c.field-meta.xml
<CustomField>
    <fullName>PMC_CUSTORDERNO__c</fullName>
    <label>CUSTORDERNO</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_Deliveries_Updated__c.field-meta.xml
<CustomField>
    <fullName>PMC_Deliveries_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deliveries Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_DELIVERYNUMBER__c.field-meta.xml
<CustomField>
    <fullName>PMC_DELIVERYNUMBER__c</fullName>
    <label>DELIVERYNUMBER</label>
    <length>252</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_DESTINATIONCARRIER__c.field-meta.xml
<CustomField>
    <fullName>PMC_DESTINATIONCARRIER__c</fullName>
    <label>DESTINATIONCARRIER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_DESTINATIONMM__c.field-meta.xml
<CustomField>
    <fullName>PMC_DESTINATIONMM__c</fullName>
    <label>DESTINATIONMM</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_EQUIPMENTID__c.field-meta.xml
<CustomField>
    <fullName>PMC_EQUIPMENTID__c</fullName>
    <label>EQUIPMENTID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_ETA__c.field-meta.xml
<CustomField>
    <fullName>PMC_ETA__c</fullName>
    <label>ETA</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_FLEETTOWNAME__c.field-meta.xml
<CustomField>
    <fullName>PMC_FLEETTOWNAME__c</fullName>
    <label>FLEETTOWNAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_LATESTINTERNALCOMMENT__c.field-meta.xml
<CustomField>
    <fullName>PMC_LATESTINTERNALCOMMENT__c</fullName>
    <label>LATESTINTERNALCOMMENT</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_LATESTTRIPSIGHTINGID__c.field-meta.xml
<CustomField>
    <fullName>PMC_LATESTTRIPSIGHTINGID__c</fullName>
    <label>LATESTTRIPSIGHTINGID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_PONUMBER__c.field-meta.xml
<CustomField>
    <fullName>PMC_PONUMBER__c</fullName>
    <label>PONUMBER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_SHIPMENTNUMBER_CNTORDER__c.field-meta.xml
<CustomField>
    <fullName>PMC_SHIPMENTNUMBER_CNTORDER__c</fullName>
    <label>SHIPMENTNUMBER_CNTORDER</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_SIGHTINGDESTINATION__c.field-meta.xml
<CustomField>
    <fullName>PMC_SIGHTINGDESTINATION__c</fullName>
    <label>SIGHTINGDESTINATION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_Shipment_Data__c/fields/PMC_SIGHTINGLOADOREMPTY__c.field-meta.xml
<CustomField>
    <fullName>PMC_SIGHTINGLOADOREMPTY__c</fullName>
    <label>SIGHTINGLOADOREMPTY</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/DaysNotMoved__c.field-meta.xml
<CustomField>
    <fullName>DaysNotMoved__c</fullName>
    <label>Days Not Moved</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/Intransit_Status__c.field-meta.xml
<CustomField>
    <fullName>Intransit_Status__c</fullName>
    <label>Intransit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Intransit_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_Carrier__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Carrier__c</fullName>
    <label>Carrier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_Comments__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Comments__c</fullName>
    <label>COMMENTS</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_CurrentCarrier__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CurrentCarrier__c</fullName>
    <description>This is used in intellitrans integration</description>
    <label>Current Carrier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_CurrentCoordinates__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CurrentCoordinates__c</fullName>
    <description>This field is used in intellitrans integration</description>
    <label>Current Coordinates</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_CurrentLocation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CurrentLocation__c</fullName>
    <label>Current Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_ETA__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ETA__c</fullName>
    <label>ETA</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_Order__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field captures the Order Number.</description>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_PO__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PO__c</fullName>
    <description>This field is used to capture the user input for Purchase order number.</description>
    <label>Customer Purchase Order #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_SAPDeliveryID__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPDeliveryID__c</fullName>
    <description>This field captures the sap Delivery ID.</description>
    <externalId>true</externalId>
    <label>SAP Delivery ID</label>
    <length>64</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_TowName__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_TowName__c</fullName>
    <label>Tow Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Intransit_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
        <label>A - Arrival-In Transit Yard</label>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
        <label>AO - LOADED ON BARGE</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>B - Bad Orders</label>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
        <label>CPU - Constructive Placed to Unload</label>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <label>D - Arrival-Destination</label>
    </customValue>
    <customValue>
        <fullName>FUL</fullName>
        <label>FUL - Finished Unload</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>G - Bad Order Release</label>
    </customValue>
    <customValue>
        <fullName>INT</fullName>
        <label>INT - Interchange</label>
    </customValue>
    <customValue>
        <fullName>J</fullName>
        <label>J - Delivery-Junction</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>P - Departure</label>
    </customValue>
    <customValue>
        <fullName>R</fullName>
        <label>R - Received-Junction</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>S - Storage</label>
    </customValue>
    <customValue>
        <fullName>STO</fullName>
        <label>STO - Storage</label>
    </customValue>
    <customValue>
        <fullName>TOW</fullName>
        <label>TOW - Towed Event</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>W - Released</label>
    </customValue>
    <customValue>
        <fullName>*W</fullName>
        <label>*W - Waybill Created</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Y - Placement-Constructive</label>
    </customValue>
    <customValue>
        <fullName>Z</fullName>
        <label>Z - Placement-Actual</label>
    </customValue>
    <description>Intransit Status</description>
    <masterLabel>Intransit Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMC_IntellitransShipmentBatchUpdate.cls
// GMDP-2612 - Added NOMOVEMENT/DaysNotMoved__c data into shipment
public class PMC_IntellitransShipmentBatchUpdate implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable {

    private Set<Id> shipmentDataIds;

    public PMC_IntellitransShipmentBatchUpdate() {
        this.shipmentDataIds = new Set<Id>();
    }

    public PMC_IntellitransShipmentBatchUpdate(Set<Id> shipmentDataIds) {
        this.shipmentDataIds = shipmentDataIds;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, PMC_BOL__c, PMC_BOLNUMBER__c, PMC_COMMENTS__c, PMC_CPQ_CurrentCoordinates__c, ' +
                       'PMC_CPQ_CurrentCoordinates__Latitude__s, PMC_CPQ_CurrentCoordinates__Longitude__s, ' +
                       'PMC_CPQ_SAPDeliveryID__c, PMC_CPQ_Shipment_PO__c, PMC_CPQ_ShipmentNumber__c, ' +
                       'PMC_CURRENTCARRIER__c, DaysNotMoved__c, Intransit_Status__c, toLabel(Intransit_Status__c) statusCode, ' +
                       'PMC_CURRENTLOCATION__c, PMC_CUSTORDERNO__c, PMC_DELIVERYNUMBER__c, PMC_DESTINATIONCARRIER__c, ' +
                       'PMC_DESTINATIONMM__c, PMC_EQUIPMENTID__c, PMC_ETA__c, PMC_FLEETTOWNAME__c, ' +
                       'PMC_LATESTINTERNALCOMMENT__c, PMC_LATESTTRIPSIGHTINGID__c, PMC_PONUMBER__c, ' +
                       'PMC_SHIPMENTNUMBER_CNTORDER__c, PMC_SIGHTINGDESTINATION__c, PMC_SIGHTINGLOADOREMPTY__c, ' +
                       'PMC_Deliveries_Updated__c ' +
                       'FROM PMC_Shipment_Data__c ' +
                       'WHERE PMC_CUSTORDERNO__c != null AND PMC_EQUIPMENTID__c != null AND PMC_Deliveries_Updated__c = FALSE';

        if (this.shipmentDataIds != null && !this.shipmentDataIds.isEmpty()) {
            query += ' AND Id IN :shipmentDataIds';
        }

        return Database.getQueryLocator(query);
    }

    public void execute(SchedulableContext objSchedulableContext) {
        Database.executeBatch(new PMC_IntellitransShipmentBatchUpdate(), 200);
    }

    public void execute(Database.BatchableContext bc, List<PMC_Shipment_Data__c> scope) {
        // Maps to hold Intellitrans data
        Map<String, PMC_Shipment_Data__c> intellitransMapPO = new Map<String, PMC_Shipment_Data__c>();
        Map<String, PMC_Shipment_Data__c> intellitransMapVID = new Map<String, PMC_Shipment_Data__c>();
        Map<String, PMC_Shipment_Data__c> intellitransMapConcat = new Map<String, PMC_Shipment_Data__c>();

        // Populate the maps with IntelliTrans data
        for (PMC_Shipment_Data__c shipmentData : scope) {
            if (shipmentData.PMC_CUSTORDERNO__c != null) intellitransMapPO.put(shipmentData.PMC_CUSTORDERNO__c, shipmentData);
            if (shipmentData.PMC_EQUIPMENTID__c != null) intellitransMapVID.put(shipmentData.PMC_EQUIPMENTID__c, shipmentData);

            intellitransMapConcat.put(shipmentData.PMC_CUSTORDERNO__c + shipmentData.PMC_EQUIPMENTID__c, shipmentData);
        }

        List<Shipment> shipmentsToUpdate = [
            SELECT 
                Id,
                DaysNotMoved__c,
                Intransit_Status__c,
                PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c,
                PMC_CPQ_SAPDeliveryID__c,
                PMC_CPQ_ETA__c,
                PMC_CPQ_PO__c,
                PMC_CPQ_VehicleID__c,
                PMC_CPQ_CurrentCarrier__c,
                PMC_CPQ_Carrier__c,
                PMC_CPQ_TowName__c,
                PMC_CPQ_CurrentLocation__c,
                PMC_CPQ_CurrentCoordinates__Latitude__s,
                PMC_CPQ_CurrentCoordinates__Longitude__s 
            FROM Shipment 
            WHERE PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c IN :intellitransMapPO.keySet() 
               OR PMC_CPQ_VehicleID__c IN :intellitransMapVID.keySet()
        ];

        List<PMC_Shipment_Data__c> processedRecordsToUpdate = new List<PMC_Shipment_Data__c>();
        Map<Id, Shipment> shipmentsToUpdateMap = new Map<Id, Shipment>();

        for (Shipment ship : shipmentsToUpdate) {
            PMC_Shipment_Data__c matchedIntellitrans;
            String sapOrderNumber = ship.PMC_CPQ_Order__r.PMC_CPQ_SAPOrderNumber__c;

            if (sapOrderNumber != null) {
                sapOrderNumber = sapOrderNumber.removeStart('00');
            }

            if (sapOrderNumber != null && ship.PMC_CPQ_VehicleID__c != null) {
                String concatKey = sapOrderNumber + ship.PMC_CPQ_VehicleID__c;
                if (intellitransMapConcat.containsKey(concatKey)) {
                    matchedIntellitrans = intellitransMapConcat.get(concatKey);

                    PMC_Shipment_Data__c processedRecord = new PMC_Shipment_Data__c(
                        Id = matchedIntellitrans.Id, 
                        PMC_Deliveries_Updated__c = true
                    );

                    processedRecordsToUpdate.add(processedRecord);
                }
            }

            if (matchedIntellitrans != null) {
                // ship.Id = matchedIntellitrans.Id;
                // ship.PMC_CPQ_SAPDeliveryID__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;

                if (matchedIntellitrans.PMC_ETA__c != null) {
                    Date currentDate = matchedIntellitrans.PMC_ETA__c.date();
                    ship.PMC_CPQ_ETA__c = Date.valueOf(currentDate);
                }

                // ship.Intransit_Status__c = matchedIntellitrans.Status__c;
                ship.Intransit_Status__c = matchedIntellitrans.Intransit_Status__c;
                String retrievedStatusCode = (String) matchedIntellitrans.get('statusCode');
                System.debug('>>> STATUS CODE: ' + retrievedStatusCode);

                if (retrievedStatusCode != null) {
                    ship.StatusCode__c = retrievedStatusCode;
                }

                // ship.PMC_CPQ_PO__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;
                // ship.PMC_CPQ_VehicleID__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;
                ship.PMC_CPQ_CurrentCarrier__c = matchedIntellitrans.PMC_CURRENTCARRIER__c;
                // ship.PMC_CPQ_Carrier__c = matchedIntellitrans.PMC_CPQ_SAPDeliveryID__c;

                ship.DaysNotMoved__c = matchedIntellitrans.DaysNotMoved__c;
                ship.PMC_CPQ_Comments__c = matchedIntellitrans.PMC_COMMENTS__c;
                ship.PMC_CPQ_TowName__c = matchedIntellitrans.PMC_FLEETTOWNAME__c;
                ship.PMC_CPQ_CurrentLocation__c = matchedIntellitrans.PMC_CURRENTLOCATION__c;
                ship.PMC_CPQ_Carrier__c = matchedIntellitrans.PMC_DESTINATIONCARRIER__c;
                ship.PMC_CPQ_CurrentCoordinates__Latitude__s = matchedIntellitrans.PMC_CPQ_CurrentCoordinates__Latitude__s;
                ship.PMC_CPQ_CurrentCoordinates__Longitude__s = matchedIntellitrans.PMC_CPQ_CurrentCoordinates__Longitude__s;

                shipmentsToUpdateMap.put(ship.Id, ship);
            }
        }

        // Perform the updates
        if (!shipmentsToUpdateMap.isEmpty()) {
            Database.SaveResult[] results = Database.update(shipmentsToUpdateMap.values(), false);
            for (Database.SaveResult sr : results) {
                if (!sr.isSuccess()) {
                    for (Database.Error err : sr.getErrors()) {
                        System.debug('>>> FALHA NO UPDATE DO SHIPMENT (' + sr.getId() + '). Campos: ' + err.getFields() + ' | Mensagem: ' + err.getMessage());
                    }
                }
            }
        }

        if (!processedRecordsToUpdate.isEmpty()) {
            Map<Id, PMC_Shipment_Data__c> uniqueProcessedRecordsMap = new Map<Id, PMC_Shipment_Data__c>();
            uniqueProcessedRecordsMap.putAll(processedRecordsToUpdate);
            Database.update(uniqueProcessedRecordsMap.values(), false);
        }
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Batch processing finished.');
    }
}