force-app/main/default/objects/Order/fields/PMC_CPQ_OrderIntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderIntegrationMessage__c</fullName>
    <description>The Integration message of external callout.</description>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_OrderIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderIntegrationStatus__c</fullName>
    <description>The staus of a callout made to an external system.</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <description>This field captures the order number in SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
    <label>SAP Order Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>This field captures the integration status of the Order product</description>
    <inlineHelpText>This field captures the integration status of the Order product</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_OrderItemIntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderItemIntegrationMessage__c</fullName>
    <description>The Integration message of external callout.</description>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_OrderItemIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderItemIntegrationStatus__c</fullName>
    <description>This field captures the integration status of the Order product</description>
    <inlineHelpText>This field captures the integration status of the Order product</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_SAPOrderLineID__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderLineID__c</fullName>
    <description>This Field is used to capture the relevant Order Line ID in SAP System.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order Line ID in SAP System</inlineHelpText>
    <label>SAP Order Line ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/PMC_CPQ_Integration_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/fields/PMC_CPQ_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Endpoint__c</fullName>
    <description>This is used to store the Integration endpoint.</description>
    <label>Endpoint</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/PMC_CPQ_TransactionLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>This will show the status of the response of the external callout.</description>
    <label>Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_InterfaceURL__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_InterfaceURL__c</fullName>
    <description>This is the endpoint that was hit during the transaction.</description>
    <label>Interface URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RequestBody__c</fullName>
    <description>This is the request body sent to the external system.</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ResponseBody__c</fullName>
    <description>This field stores the response body of the request made to the external system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/OrderCart_OrderIntegrationClass.cls
public without sharing class OrderCart_OrderIntegrationClass implements Database.AllowsCallouts {
    static HttpRequest request = new HttpRequest();
    static HttpResponse response;

    static Boolean boolTransLogSuccess = false;
    static Boolean boolTransLogError = false;
    static String strTransactionLogStatus;

    static final String STRING_INTEGRATIONSTATUSERROR = 'Error';
    static final String STRING_INTEGRATIONSTATUSSUCCESS = 'Success';

    static final String STRING_SAP_ORDERNO = 'OBJ_NUM';
    static final String STRING_SAP_ORDERITEMNO = 'OBJ_ITEM';
    static final String STRING_SF_ORDERID = 'SFOrderId';
    static final String STRING_SF_ORDERLINEID = 'SF_ORDERITEM_ID';
    static final string STRING_STATUSCODE = 'statusCode';
    static final string STRING_RESPONSEMESSAGE = 'responsetext';

    static final Integer INT_STATUSCODE200 = 200;
    static final Integer INT_STATUSCODE201 = 201;

    static final List<Integer> LISTINT_SUCCESSCODES = new List<Integer>{INT_STATUSCODE200,INT_STATUSCODE201};
    static List<Object> lstFilteredOrderLine = new List<Object>();
    static List<Object> lstFilteredOrder = new List<Object>();
    static List<Object> lstFilteredTransactionStatus = new List<Object>();
    static List<OrderItem> lstOrderLines = new List<OrderItem>();

    public static void setFilteredListOrderOrderLine(List<Object> lstObjContainer)
    {
        Set<Object> setFilteredOrderLine = new Set<Object>();
        Set<Object> setFilteredOrder = new Set<Object>();
        Set<Object> setFilteredTransactionStatus = new Set<Object>();

        for(Object objContainer: lstObjContainer)
        {
            Map<String,Object> mapCurRecord = (Map<String,Object>) objContainer;
            Map<String,Object> mapOrderLineRecord = new Map<String,Object>();
            Map<String,Object> mapOrderRecord = new Map<String,Object>();

            mapOrderLineRecord.put(STRING_SAP_ORDERNO,mapCurRecord.get(STRING_SAP_ORDERNO));
            mapOrderLineRecord.put(STRING_SF_ORDERID,mapCurRecord.get(STRING_SF_ORDERID));
            mapOrderLineRecord.put(STRING_SAP_ORDERITEMNO,mapCurRecord.get(STRING_SAP_ORDERITEMNO));
            mapOrderLineRecord.put(STRING_SF_ORDERLINEID,mapCurRecord.get(STRING_SF_ORDERLINEID));
            mapOrderLineRecord.put(STRING_STATUSCODE,mapCurRecord.get(STRING_STATUSCODE));
            mapOrderLineRecord.put(STRING_RESPONSEMESSAGE,mapCurRecord.get(STRING_RESPONSEMESSAGE));

            mapOrderRecord.put(STRING_SF_ORDERID,mapCurRecord.get(STRING_SF_ORDERID));
            mapOrderRecord.put(STRING_SAP_ORDERNO,mapCurRecord.get(STRING_SAP_ORDERNO));
            mapOrderRecord.put(STRING_STATUSCODE,mapCurRecord.get(STRING_STATUSCODE));
            mapOrderRecord.put(STRING_RESPONSEMESSAGE,mapCurRecord.get(STRING_RESPONSEMESSAGE));

            setFilteredOrderLine.add(mapOrderLineRecord);
            setFilteredOrder.add(mapOrderRecord);
            setFilteredTransactionStatus.add(mapCurRecord.get(STRING_STATUSCODE));
        }
        lstFilteredOrder.addAll(setFilteredOrder);
        lstFilteredOrderLine.addAll(setFilteredOrderLine);
        lstFilteredTransactionStatus.addAll(setFilteredTransactionStatus);
    }

    public static void parseOrderFilteredList(List<Order> lstOrders)
    {
        for(Order objOrder: lstOrders)
        {
            for(Object objCurrent: lstFilteredOrder)
            {
                Map<String,Object> mapRecord = (Map<String,Object>)objCurrent;
                Boolean boolIsCurrentOrder = (String)mapRecord.get(STRING_SF_ORDERID) == objOrder.Id;
                if(boolIsCurrentOrder)
                {
                    objOrder.PMC_CPQ_OrderIntegrationMessage__c = (String) mapRecord.get(STRING_RESPONSEMESSAGE);
                    if(String.isBlank((String) mapRecord.get(STRING_SAP_ORDERNO)) == false)
                    {
                        objOrder.PMC_CPQ_OrderIntegrationStatus__c = STRING_INTEGRATIONSTATUSSUCCESS;
                        objOrder.PMC_CPQ_SAPOrderNumber__c = (String) mapRecord.get(STRING_SAP_ORDERNO);
                    }
                    else
                    {
                         objOrder.PMC_CPQ_OrderIntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
                    }

                    if (mapRecord.get('statusCode') != null) {
                        Integer statusCode = Integer.valueOf(mapRecord.get('statusCode'));
                        if (statusCode == 406) {
                            objOrder.PMC_CPQ_OrderIntegrationStatus__c = 'Warning';
                        }
                    }
                 }
            }
        }
     }

    public static void parseOrderLineFilteredList(List<OrderItem> lstOrderLines)
    {
        for(OrderItem objOrderLine: lstOrderLines)
        {
            for(Object objCurrent: lstFilteredOrderLine)
            {
                Map<String,Object> mapRecord = (Map<String,Object>)objCurrent;
                Boolean boolIsCurrentOrderLine = String.valueOf(mapRecord.get(STRING_SF_ORDERLINEID)) == String.valueOf(objOrderLine.Id);
                if(boolIsCurrentOrderLine)
                {
                    objOrderLine.PMC_CPQ_OrderItemIntegrationMessage__c = (String) mapRecord.get(STRING_RESPONSEMESSAGE);
                    if(String.isBlank((String) mapRecord.get(STRING_SAP_ORDERNO)) == false)
                    {
                        objOrderLine.PMC_CPQ_OrderItemIntegrationStatus__c = STRING_INTEGRATIONSTATUSSUCCESS;
                        objOrderLine.PMC_CPQ_SAPOrderLineID__c = (String) mapRecord.get(STRING_SAP_ORDERNO)+'_'+String.valueOf(mapRecord.get(STRING_SAP_ORDERITEMNO));
                    }
                    else
                    {
                        objOrderLine.PMC_CPQ_OrderItemIntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
                    }
                }
            }
        }

    }

    public static void parseJSONOrderInterface(List<Order> lstOrders, HttpResponse response, List<Id> lstIds)
    {
        List<Object> lstObjContainer= new List<Object>();
        String strJSONResponseBody = response.getBody();
        List<OrderItem> lstOrderLines = new List<OrderItem>();
        if(Schema.sObjectType.OrderItem.isAccessible())
        {
             lstOrderLines = [select Id from OrderItem where OrderId in :lstIds];
        }

        String strInterface = 'SAPSalesOrderCreate';
        PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface);
        String strOrderReplicationEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;

        if(LISTINT_SUCCESSCODES.contains(response.getStatusCode()))
        {
            try
            {
                lstObjContainer = (List<Object>) JSON.deserializeUntyped(response.getBody());
                setFilteredListOrderOrderLine(lstObjContainer);
                parseOrderFilteredList(lstOrders);
                parseOrderLineFilteredList(lstOrderLines);

                if(lstFilteredTransactionStatus.size() == 1 && LISTINT_SUCCESSCODES.contains(Integer.valueOf(lstFilteredTransactionStatus[0])))
                {
                    strTransactionLogStatus = STRING_INTEGRATIONSTATUSSUCCESS;
                }
                else
                {
                    strTransactionLogStatus = STRING_INTEGRATIONSTATUSERROR;
                }
            }
            catch(Exception e)
            {
                strTransactionLogStatus = STRING_INTEGRATIONSTATUSERROR;
                updateOrderandOrderLineErrorExceptionStatusMsg(lstOrders,lstIds,e.getMessage());
            }
        }
        else
        {
            strTransactionLogStatus = STRING_INTEGRATIONSTATUSERROR;
            updateOrderandOrderLineErrorExceptionStatusMsg(lstOrders,lstIds,response.getBody());
        }

        SObjectAccessDecision securityDecisionOrder = Security.stripInaccessible(AccessType.UPDATABLE, lstOrders);
        Database.update(securityDecisionOrder.getRecords(),false);

        SObjectAccessDecision securityDecisionOrderItem = Security.stripInaccessible(AccessType.UPDATABLE, lstOrderLines);
        Database.update(securityDecisionOrderItem.getRecords(),false);

        Map<String, String> mapTransactionLogFields = new Map<String,String>();
        mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c',strTransactionLogStatus);
        mapTransactionLogFields.put('PMC_CPQ_InterfaceURL__c',strOrderReplicationEndpoint);
        mapTransactionLogFields.put('PMC_CPQ_RequestBody__c',OrderCart_CPIRemoteCalloutUtilityClass.request.getBody());
        mapTransactionLogFields.put('PMC_CPQ_ResponseBody__c',strJSONResponseBody);

        List<PMC_CPQ_TransactionLog__c> lstTransactionLogs = OrderCart_TransactionLogUtilityClass.addTransactionLog(mapTransactionLogFields);
        OrderCart_TransactionLogUtilityClass.insertTransactionLogs(lstTransactionLogs);
    }

    public static void updateOrderandOrderLineErrorExceptionStatusMsg(List<Order> lstOrders, List<Id> lstIds, String strMessage)
    {
        List<OrderItem> lstOrderLines = new List<OrderItem>();
        if(Schema.sObjectType.OrderItem.isAccessible())
        {
             lstOrderLines = [select Id from OrderItem where OrderId in :lstIds];
        }
        for(Order objOrder: lstOrders)
        {
            objOrder.PMC_CPQ_OrderIntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
            objOrder.PMC_CPQ_OrderIntegrationMessage__c = strMessage;
        }
        for(OrderItem objOrderLine: lstOrderLines)
        {
            objOrderLine.PMC_CPQ_OrderItemIntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
            objOrderLine.PMC_CPQ_OrderItemIntegrationMessage__c = strMessage;
        }

        SObjectAccessDecision securityDecisionOrder = Security.stripInaccessible(AccessType.UPDATABLE, lstOrders);
        Database.update(securityDecisionOrder.getRecords(),false);

        SObjectAccessDecision securityDecisionOrderItem = Security.stripInaccessible(AccessType.UPDATABLE, lstOrderLines);
        Database.update(securityDecisionOrderItem.getRecords(),false);
    }
}