force-app/main/default/objects/PMC_TriggerSwitches__mdt/PMC_TriggerSwitches__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to bypass trigger operations.</description>
    <label>PMC Trigger Switches</label>
    <pluralLabel>PMC Trigger Switches</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterDelete__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterInsert__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterUndelete__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_BeforeDelete__c.field-meta.xml
<CustomField>
    <fullName>PMC_BeforeDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_BeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>PMC_BeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_BeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>PMC_BeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_QuoteApprovedExtractor__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_QuoteApprovedExtractor__c</fullName>
    <formula>SBQQ__Quote__r.PMC_CPQ_QuoteApproved__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Approved Extractor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PMC_CPQ_QuoteLineTriggerHandler.cls
public class PMC_CPQ_QuoteLineTriggerHandler extends PMC_TriggerHandler {
	private static final Boolean BOOL_BYPASS_BEFORE_INSERT;
	private static final Boolean BOOL_BYPASS_BEFORE_UPDATE;
	private static final Boolean BOOL_BYPASS_BEFORE_DELETE;
	private static final Boolean BOOL_BYPASS_AFTER_INSERT;
	private static final Boolean BOOL_BYPASS_AFTER_UPDATE;
	private static final Boolean BOOL_BYPASS_AFTER_DELETE;
	private static final Boolean BOOL_BYPASS_AFTER_UNDELETE;

	@testVisible
	public static Boolean boolBypassTriggerLogic = false;

	private List<SBQQ__QuoteLine__c> newList;
	private Map<Id, SBQQ__QuoteLine__c> newMap;
	private List<SBQQ__QuoteLine__c> oldList;
	private Map<Id, SBQQ__QuoteLine__c> oldMap;

	/**
	 * @description This static block initializes the trigger switches when the class is invoked
	 */
	static {
		PMC_TriggerSwitches__mdt operationSwitches = PMC_TriggerSwitches__mdt.getInstance('QuoteLine');
		BOOL_BYPASS_BEFORE_INSERT = operationSwitches.PMC_BeforeInsert__c;
		BOOL_BYPASS_BEFORE_UPDATE = operationSwitches.PMC_BeforeUpdate__c;
		BOOL_BYPASS_BEFORE_DELETE = operationSwitches.PMC_BeforeDelete__c;
		BOOL_BYPASS_AFTER_INSERT = operationSwitches.PMC_AfterInsert__c;
		BOOL_BYPASS_AFTER_UPDATE = operationSwitches.PMC_AfterUpdate__c;
		BOOL_BYPASS_AFTER_DELETE = operationSwitches.PMC_AfterDelete__c;
		BOOL_BYPASS_AFTER_UNDELETE = operationSwitches.PMC_AfterUndelete__c;
	}

	public PMC_CPQ_QuoteLineTriggerHandler() {
		//Instantiating local class variables from trigger variables
		this.newList = Trigger.new;
		this.newMap = (Map<Id, SBQQ__QuoteLine__c>) Trigger.newMap;
		this.oldList = Trigger.old;
		this.oldMap = (Map<Id, SBQQ__QuoteLine__c>) Trigger.oldMap;

		//Set the maximum calls allowed for the class
		this.setMaxLoopCount(8);
	}

	public override void beforeInsert() {
		if (BOOL_BYPASS_BEFORE_INSERT || boolBypassTriggerLogic) {
			return;
		}
		PMC_CPQ_QuoteLineTriggerHelper.copyAmendmentQuoteLineDetails(newList);
		PMC_CPQ_QuoteLineTriggerHelper.updateVCOInsertedLineItems(newList);
	}

	public override void beforeDelete() {
		if (BOOL_BYPASS_BEFORE_DELETE || boolBypassTriggerLogic) {
			return;
		}
		for (SBQQ__QuoteLine__c ql : this.oldList) {
			// Prevent approved Quote Lines deletion
			if (ql.PMC_CPQ_QuoteApprovedExtractor__c) {
				ql.addError(Label.PMC_CPQ_DeleteApprovedQuoteLineErrorMsg);
			}
		}
	}

	public override void afterUpdate() {
		if (BOOL_BYPASS_AFTER_UPDATE || boolBypassTriggerLogic) {
			return;
		}
		PMC_CPQ_QuoteLineTriggerHelper.setContractUpdateCheckEligibilityStatus(newList, oldMap);
	}
}