force-app/main/default/objects/PMC_SS_SalesArea__c/PMC_SS_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area Object</description>
    <label>Sales Area</label>
    <nameField>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_CPQ_SAPSalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPSalesOrganization__c</fullName>
    <description>Field to uniquely identify SAP Sales Organization</description>
    <externalId>true</externalId>
    <label>SAP Sales Organization</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_SS_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_DistributionChannel__c</fullName>
    <description>Specifies the Distribution Channel</description>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Common</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_SS_Division__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Division__c</fullName>
    <description>Specifies the Division</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Domestic</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Export</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Intercompany</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_SS_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SalesOrganization__c</fullName>
    <description>Specifies the Sales Organization</description>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fospar SA</fullName>
            </value>
            <value>
                <fullName>Comp. Minera Miski Mayo</fullName>
                <label>Minera Miski Mayo</label>
            </value>
            <value>
                <fullName>Mos. Sulphur Partner</fullName>
            </value>
            <value>
                <fullName>Mos Ag Innovation Sol,LLC</fullName>
                <label>Mosaic Ag Innov Sol</label>
            </value>
            <value>
                <fullName>Mosaic Potash Colonsay UL</fullName>
                <label>Mosaic CA Colonsay</label>
            </value>
            <value>
                <fullName>Mosaic CA Crop Nutrit, LP</fullName>
                <label>Mosaic CA Crop Nutri</label>
            </value>
            <value>
                <fullName>Mosaic Potash Esterhazy</fullName>
                <label>Mosaic CA Esterhazy</label>
            </value>
            <value>
                <fullName>Mosaic Canada ULC (BP)</fullName>
                <label>Mosaic CA ULC (BP)</label>
            </value>
            <value>
                <fullName>Mosaic Crop Nutrition LLC</fullName>
                <label>Mosaic CN Fertilizer</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (HK) L</fullName>
                <label>Mosaic Fert. (HK)</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizantes Ltd.</fullName>
                <label>Mosaic Fert Bahamas</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (BJ)</fullName>
                <label>Mosaic Fert BMF</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizantes do B</fullName>
                <label>Mosaic Fert Brasil</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizer LLC</fullName>
                <label>Mosaic Fertilizer</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizantes P&amp;K</fullName>
                <label>Mosaic Fert P&amp;K</label>
            </value>
            <value>
                <fullName>Mosaic Fertz Paraguay SRL</fullName>
                <label>Mosaic Fert Paraguay</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (QHD)</fullName>
                <label>Mosaic Fert QMF</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (YT)</fullName>
                <label>Mosaic Fert YMF</label>
            </value>
            <value>
                <fullName>Mosaic Global Sales LLC</fullName>
                <label>Mosaic Global Sales</label>
            </value>
            <value>
                <fullName>Mosaic India Private Ltd.</fullName>
                <label>Mosaic India Pvt Ltd</label>
            </value>
            <value>
                <fullName>Mosaic Potash Carlsbad In</fullName>
                <label>Mosaic Potash Carlsb</label>
            </value>
            <value>
                <fullName>Mosaic Potássio Mineração</fullName>
                <label>Mosaic Potássio Mine</label>
            </value>
            <value>
                <fullName>Tampa Port Services, LLC</fullName>
                <label>Tampa Port Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationMessage__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the integration response message</description>
    <inlineHelpText>receives the Integration response message</inlineHelpText>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_PrimaryBusinessType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PrimaryBusinessType__c</fullName>
    <description>This field is to extract business type from Primary Business Type in Quote to use filter on Add product selection page</description>
    <formula>IF(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&quot;International&quot;,&quot;&quot;, IF(
ISPICKVAL( PMC_CPQ_Region__c, &apos;North America&apos;) ,
IF( RecordType.DeveloperName =&apos;PMC_CPQ_International&apos;,&apos;&apos;,
IF(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&quot;Industrial&quot;,&quot;&quot;,
IF( or(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&apos;Co-Products&apos; ,TEXT(PMC_CPQ_QuoteRecordSubType__c)=&apos;Raw Material&apos;),&apos;Co-Product&apos;,
TEXT(PMC_CPQ_QuoteRecordSubType__c))
)
) ,
IF( OR(TRIM(RIGHT( TEXT( PMC_CPQ_QuoteRecordSubType__c ),LEN(TEXT( PMC_CPQ_QuoteRecordSubType__c ))-6) )=&quot;Potash&quot;,
TRIM(RIGHT( TEXT( PMC_CPQ_QuoteRecordSubType__c ),LEN(TEXT( PMC_CPQ_QuoteRecordSubType__c ))-6) )=&quot;Paraguay&quot;),&quot;&quot;,
if(TEXT(PMC_CPQ_QuoteRecordSubType__c)=&apos;B2B_Specialities&apos;,&apos;Co-Product&apos;,TRIM(RIGHT( TEXT( PMC_CPQ_QuoteRecordSubType__c ),LEN(TEXT( PMC_CPQ_QuoteRecordSubType__c ))-6) )))
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Business Type Extractor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SBQQ__Account__c</field>
            <operation>equals</operation>
            <valueField>PMC_SS_AccountSalesAreaRelationship__c.PMC_SS_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_FinalPricePerTon__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FinalPricePerTon__c</fullName>
    <label>Final Price Per Ton (Original)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
    <relationshipLabel>CPQ Quote Lines</relationshipLabel>
    <relationshipName>PMC_CPQ_CPQQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/PMC_CPQ_PrimaryBusinessType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PrimaryBusinessType__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PMC_CPQ_SalesRegion__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_QuoteBusinessType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <description>The Sales Areas associated with the user from which the record type and product will be configured.</description>
    <label>Sales Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_SalesAreaUser</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PMC_CPQ_SalesRegion__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesRegion__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_QuoteBusinessType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Feed</fullName>
    </customValue>
    <customValue>
        <fullName>Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Material</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Products</fullName>
    </customValue>
    <customValue>
        <fullName>B2C - Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Feed</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Fertilizer</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Specialties</fullName>
    </customValue>
    <customValue>
        <fullName>B2C - Paraguay</fullName>
    </customValue>
    <customValue>
        <fullName>B2B - Potash</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Raw Materials</fullName>
        <isActive>false</isActive>
        <label>Raw Materials</label>
    </customValue>
    <masterLabel>Quote Business Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMC_CPQ_NoCalcUpdateInvocableTest.cls
/**
 * @description Test class for PMC_CPQ_NoCalcUpdateInvocable.
 * @author Raphael Soares
 * @storynumber back-to-draft-fix
 */
@isTest(seeAllData = false)
private with sharing class PMC_CPQ_NoCalcUpdateInvocableTest {

    @TestSetup
    static void setup() {
        List<String> lstProfileNames = new List<String>{ 'System Administrator', 'Sales User' };
        List<String> lstPermissionSetGroupNames = new List<String>{ 'PMC_Administrator_Permission_Set_Group', 'PMC_SLS_Permission_Set_Group' };
        Map<String, Id> mapProfiles = PMC_TestUtilityClass.getProfiles(lstProfileNames);
        Map<String, PermissionSetGroup> mapPermGroups = PMC_TestUtilityClass.getPemissionsetGroups(lstPermissionSetGroupNames);

        Integer intUserCount = 0;
        User objSystemAdminUser;
        User objSalesUser;
        List<User> lstUsers = PMC_TestUtilityClass.createUser(2);
        for (User objUser : lstUsers) {
            if (intUserCount == 0) {
                objUser.LastName = 'Admin User Test';
                objUser.ProfileId = mapProfiles.get('System Administrator');
                objUser.FederationIdentifier = objUser.Username + 'Admin';
            } else if (intUserCount == 1) {
                objUser.LastName = 'Sales User Test';
                objUser.ProfileId = mapProfiles.get('Sales User');
                objUser.FederationIdentifier = objUser.Username + 'Sales';
            }
            objUser.isActive = true;
            objUser.MobilePhone = '1234567890';
            objUser.UserPermissionsKnowledgeUser = true;
            objUser.LanguageLocaleKey = 'en_US';
            objUser.PMC_CPQ_SalesRegion__c = 'North America';
            objUser.PMC_CPQ_PrimaryBusinessType__c = 'Feed';
            objUser.PMC_CPQ_SalesArea__c = 'Mosaic Global Sales LLC Domestic Common';
            intUserCount++;
        }
        insert lstUsers;
        objSystemAdminUser = lstUsers[0];
        objSalesUser = lstUsers[1];
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(
            new List<User>{ objSystemAdminUser },
            mapPermGroups.get('PMC_Administrator_Permission_Set_Group')
        );
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(
            new List<User>{ objSalesUser },
            mapPermGroups.get('PMC_SLS_Permission_Set_Group')
        );

        System.runAs(objSystemAdminUser) {
            List<PMC_SS_SalesArea__c> lstSalesArea = PMC_TestUtilityClass.createSalesArea(1, 'Master');
            lstSalesArea[0].PMC_SS_SalesOrganization__c = 'Mosaic Global Sales LLC';
            lstSalesArea[0].PMC_CPQ_SAPSalesOrganization__c = '10020010';
            lstSalesArea[0].PMC_SS_DistributionChannel__c = '00';
            lstSalesArea[0].PMC_SS_Division__c = '10';
            update lstSalesArea;
        }
    }

    @isTest
    static void updateWithoutCalc_handlesNullRequest() {
        Test.startTest();
        try {
            PMC_CPQ_NoCalcUpdateInvocable.updateWithoutCalc(null);
        } catch (Exception e) {
            System.assert(false, 'null request should not throw: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    static void updateWithoutCalc_handlesEmptyRequest() {
        Test.startTest();
        try {
            PMC_CPQ_NoCalcUpdateInvocable.updateWithoutCalc(new List<PMC_CPQ_NoCalcUpdateInvocable.Request>());
        } catch (Exception e) {
            System.assert(false, 'empty request should not throw: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    static void updateWithoutCalc_handlesRequestWithNullFields() {
        List<PMC_CPQ_NoCalcUpdateInvocable.Request> lstRequests = new List<PMC_CPQ_NoCalcUpdateInvocable.Request>{
            new PMC_CPQ_NoCalcUpdateInvocable.Request()
        };

        Test.startTest();
        try {
            PMC_CPQ_NoCalcUpdateInvocable.updateWithoutCalc(lstRequests);
        } catch (Exception e) {
            System.assert(false, 'request with null fields should not throw: ' + e.getMessage());
        }
        Test.stopTest();
    }

    @isTest
    static void updateWithoutCalc_updatesQuoteSuccessfully() {
        List<User> lstUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];
        System.runAs(lstUser[0]) {
            List<SBQQ__Quote__c> lstQuotes = PMC_CPQ_SetPriceResourceTest.createQuotes(1, lstUser);

            SBQQ__Quote__c objQuoteToUpdate = new SBQQ__Quote__c(
                Id = lstQuotes[0].Id,
                PMC_CPQ_IntegrationMessage__c = 'Updated via invocable test'
            );
            PMC_CPQ_NoCalcUpdateInvocable.Request req = new PMC_CPQ_NoCalcUpdateInvocable.Request();
            req.quote = objQuoteToUpdate;

            Test.startTest();
            PMC_CPQ_NoCalcUpdateInvocable.updateWithoutCalc(
                new List<PMC_CPQ_NoCalcUpdateInvocable.Request>{ req }
            );
            Test.stopTest();

            SBQQ__Quote__c objAfter = [
                SELECT PMC_CPQ_IntegrationMessage__c FROM SBQQ__Quote__c WHERE Id = :lstQuotes[0].Id
            ];
            System.assertEquals(
                'Updated via invocable test',
                objAfter.PMC_CPQ_IntegrationMessage__c,
                'Quote should have been updated by the invocable'
            );
        }
    }

    @isTest
    static void updateWithoutCalc_updatesQuoteLinesSuccessfully() {
        List<User> lstUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];
        System.runAs(lstUser[0]) {
            List<SBQQ__Quote__c> lstQuotes = PMC_CPQ_SetPriceResourceTest.createQuotes(1, lstUser);
            List<SBQQ__QuoteLine__c> lstQuoteLines = [
                SELECT Id, PMC_CPQ_FinalPricePerTon__c FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :lstQuotes[0].Id
            ];
            System.assert(!lstQuoteLines.isEmpty(), 'Setup should have created a quote line');

            for (SBQQ__QuoteLine__c objQl : lstQuoteLines) {
                objQl.PMC_CPQ_FinalPricePerTon__c = 99.99;
            }
            PMC_CPQ_NoCalcUpdateInvocable.Request req = new PMC_CPQ_NoCalcUpdateInvocable.Request();
            req.quoteLines = lstQuoteLines;

            Test.startTest();
            PMC_CPQ_NoCalcUpdateInvocable.updateWithoutCalc(
                new List<PMC_CPQ_NoCalcUpdateInvocable.Request>{ req }
            );
            Test.stopTest();

            List<SBQQ__QuoteLine__c> lstAfter = [
                SELECT PMC_CPQ_FinalPricePerTon__c FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :lstQuotes[0].Id
            ];
            System.assertEquals(
                99.99,
                lstAfter[0].PMC_CPQ_FinalPricePerTon__c,
                'QuoteLine should have been updated by the invocable'
            );
        }
    }

    @isTest
    static void updateWithoutCalc_updatesQuoteAndLinesInSameRequest() {
        List<User> lstUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];
        System.runAs(lstUser[0]) {
            List<SBQQ__Quote__c> lstQuotes = PMC_CPQ_SetPriceResourceTest.createQuotes(1, lstUser);
            List<SBQQ__QuoteLine__c> lstQuoteLines = [
                SELECT Id FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :lstQuotes[0].Id
            ];

            SBQQ__Quote__c objQuoteToUpdate = new SBQQ__Quote__c(
                Id = lstQuotes[0].Id,
                PMC_CPQ_IntegrationMessage__c = 'Combined update'
            );
            for (SBQQ__QuoteLine__c objQl : lstQuoteLines) {
                objQl.PMC_CPQ_FinalPricePerTon__c = 55.55;
            }
            PMC_CPQ_NoCalcUpdateInvocable.Request req = new PMC_CPQ_NoCalcUpdateInvocable.Request();
            req.quote = objQuoteToUpdate;
            req.quoteLines = lstQuoteLines;

            Test.startTest();
            PMC_CPQ_NoCalcUpdateInvocable.updateWithoutCalc(
                new List<PMC_CPQ_NoCalcUpdateInvocable.Request>{ req }
            );
            Test.stopTest();

            SBQQ__Quote__c objQuoteAfter = [
                SELECT PMC_CPQ_IntegrationMessage__c FROM SBQQ__Quote__c WHERE Id = :lstQuotes[0].Id
            ];
            List<SBQQ__QuoteLine__c> lstLinesAfter = [
                SELECT PMC_CPQ_FinalPricePerTon__c FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c = :lstQuotes[0].Id
            ];

            System.assertEquals('Combined update', objQuoteAfter.PMC_CPQ_IntegrationMessage__c);
            System.assertEquals(55.55, lstLinesAfter[0].PMC_CPQ_FinalPricePerTon__c);
        }
    }
}