force-app/main/default/objects/Contract/fields/PMC_CPQ_ContractType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractType__c</fullName>
    <description>This field will be used to indicate the Contract Type wrt to the Mode to Transportation (Rail, Truck, Barge) and FPD/Priced/CCC</description>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Priced Contract Barge</fullName>
            </value>
            <value>
                <fullName>Priced Contract Truck</fullName>
            </value>
            <value>
                <fullName>Priced Contract Rail</fullName>
            </value>
            <value>
                <fullName>FPD Contract Barge</fullName>
            </value>
            <value>
                <fullName>FPD Contract Rail</fullName>
            </value>
            <value>
                <fullName>FPD Contract Truck</fullName>
            </value>
            <value>
                <fullName>CCC Contract Truck</fullName>
            </value>
            <value>
                <fullName>Third Party Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000}</displayFormat>
        <label>Contract Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Invoiced_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Quantity__c</fullName>
    <inlineHelpText>Sum of all invoices subtracting return invoices and NOT adding cancelled and FA invoices.</inlineHelpText>
    <label>Invoiced Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Latest_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Latest_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest QL</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Contract Line Items (Latest QL)</relationshipLabel>
    <relationshipName>Contract_Line_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Latest_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Sub</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Contract Line Items (Latest Sub)</relationshipLabel>
    <relationshipName>Contract_Line_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Original_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Original_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original QL</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Contract Line Items (Original QL)</relationshipLabel>
    <relationshipName>Contract_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Original_Subscription_Ref__c.field-meta.xml
<CustomField>
    <fullName>Original_Subscription_Ref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Sub</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Contract Line Items (Original Sub)</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/PMC_CPQ_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RejectionReason__c</fullName>
    <label>Rejected Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Quantity contracted. This is only changed with amendments.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Available_Quantity__c</fullName>
    <inlineHelpText>Quantity available to be consumed from the contract into sales order.</inlineHelpText>
    <label>Total Available Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Consumed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Consumed_Quantity__c</fullName>
    <inlineHelpText>Invoiced quantity subtracting ordered quantity.</inlineHelpText>
    <label>Qty to Ship</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CLM_DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CLM_DocumentNumber__c</fullName>
    <description>This field will store the contract document number</description>
    <formula>IF(TEXT(SBQQ__Type__c) &lt;&gt; &apos;Amendment&apos;,
SUBSTITUTE(Name,&quot;Q-&quot;,&quot;&quot;),
SUBSTITUTE(SBQQ__Opportunity2__r.SBQQ__AmendedContract__r.SBQQ__Quote__r.Name ,&quot;Q-&quot;,&quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Document Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Annual</fullName>
                <isActive>false</isActive>
                <label>Annual</label>
            </value>
            <value>
                <fullName>CCC</fullName>
            </value>
            <value>
                <fullName>FPD</fullName>
            </value>
            <value>
                <fullName>FPD Ex-Space</fullName>
                <isActive>false</isActive>
                <label>FPD Ex-Space</label>
            </value>
            <value>
                <fullName>Priced</fullName>
            </value>
            <value>
                <fullName>Priced Ex-Space</fullName>
                <isActive>false</isActive>
                <label>Priced Ex-Space</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RejectionReason__c</fullName>
    <description>This field is created as a part of story to handle/store value of Rejection Reason for any Quote.</description>
    <inlineHelpText>Reason for which the Quote was rejected</inlineHelpText>
    <label>Rejection Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CLM_QuoteLineNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CLM_QuoteLineNumber__c</fullName>
    <formula>IF	(
	TEXT(SBQQ__Quote__r.SBQQ__Type__c) &lt;&gt; &apos;Amendment&apos;,
		SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(Name,&quot;QL-&quot;,&quot;&quot;),
		IF	(
				ISNULL(SBQQ__UpgradedSubscription__c) ||  ISBLANK(SBQQ__UpgradedSubscription__c),
				SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__AmendedContract__r.SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(Name,&quot;QL-&quot;,&quot;&quot;),
				SBQQ__UpgradedSubscription__r.SBQQ__QuoteLine__r.SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(SBQQ__UpgradedSubscription__r.SBQQ__QuoteLine__r.Name ,&quot;QL-&quot;,&quot;&quot;) 	
			)
	)</formula>
    <label>Quote Line Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_ContractType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractType__c</fullName>
    <description>This field is created  to check the contract type associated to the SBQQ Quote line item.</description>
    <inlineHelpText>This field captures the Contract Type</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PMC_CPQ_QuoteRecordType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCC</fullName>
            </value>
            <value>
                <fullName>FPD</fullName>
            </value>
            <value>
                <fullName>Priced</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
                <isActive>false</isActive>
                <label>Annual</label>
            </value>
            <value>
                <fullName>FPD Ex-Space</fullName>
                <isActive>false</isActive>
                <label>FPD Ex-Space</label>
            </value>
            <value>
                <fullName>Priced Ex-Space</fullName>
                <isActive>false</isActive>
                <label>Priced Ex-Space</label>
            </value>
            <value>
                <fullName>Provisional Pricing</fullName>
                <isActive>false</isActive>
                <label>Provisional Pricing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/AutoClosedInfo__c.field-meta.xml
<CustomField>
    <fullName>AutoClosedInfo__c</fullName>
    <label>Auto Closed Info</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DN</fullName>
                <label>Reel not cleared</label>
            </value>
            <value>
                <fullName>PB</fullName>
                <label>Prepay Block</label>
            </value>
            <value>
                <fullName>Y1</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Y2</fullName>
                <label>Closed for Orders</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Line Item</label>
    <referenceTo>Contract_Line_Item__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/MD_SAPItemNumber__c.field-meta.xml
<CustomField>
    <fullName>MD_SAPItemNumber__c</fullName>
    <label>SAP Item Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PMC_CPQ_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RejectionReason__c</fullName>
    <label>Rejected Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/md_reportContractService.cls
public without sharing class md_reportContractService {

    @TestVisible
    private static Exception serviceException = null;

    public static List<Id> getLatestQuoteIdsForAccounts(List<Id> accountIds) {
        if (serviceException != null) throw serviceException;
        if (accountIds == null || accountIds.isEmpty()) return new List<Id>();
        return new List<Id>(md_reportContractDAO.queryLatestQuoteIdsByAccounts(new Set<Id>(accountIds)));
    }

    public static String getWhereClauseExcludingRejected(List<Id> quoteIds) {
        if (serviceException != null) throw serviceException;
        if (quoteIds == null || quoteIds.isEmpty()) return '';

        List<SBQQ__QuoteLine__c> quoteLines = [
            SELECT Id, PMC_CLM_QuoteLineNumber__c
            FROM SBQQ__QuoteLine__c
            WHERE SBQQ__Quote__c IN :quoteIds
        ];

        if (quoteLines.isEmpty()) return '';

        Map<String, Id> displayedQuoteLineIdByItemNumber = new Map<String, Id>();
        for (SBQQ__QuoteLine__c ql : quoteLines) {
            if (String.isNotBlank(ql.PMC_CLM_QuoteLineNumber__c)) {
                displayedQuoteLineIdByItemNumber.put(ql.PMC_CLM_QuoteLineNumber__c, ql.Id);
            }
        }

        List<Contract_Line_Item__c> rejectedItems =
            md_reportContractDAO.queryRejectedContractLineItems(displayedQuoteLineIdByItemNumber.keySet());

        if (rejectedItems.isEmpty()) return '';

        Set<Id> rejectedDisplayedQuoteLineIds = new Set<Id>();
        for (Contract_Line_Item__c cli : rejectedItems) {
            if (!String.isNotBlank(cli.Original_Subscription_Ref__r?.PMC_CPQ_RejectionReason__c)) continue;

            String itemNumber = cli.Latest_Quote_Line__r?.PMC_CLM_QuoteLineNumber__c;
            if (itemNumber == null || !displayedQuoteLineIdByItemNumber.containsKey(itemNumber)) {
                itemNumber = cli.Original_Quote_Line__r?.PMC_CLM_QuoteLineNumber__c;
            }

            Id displayedQuoteLineId = displayedQuoteLineIdByItemNumber.get(itemNumber);
            if (displayedQuoteLineId != null) {
                rejectedDisplayedQuoteLineIds.add(displayedQuoteLineId);
            }
        }

        if (rejectedDisplayedQuoteLineIds.isEmpty()) return '';

        List<String> excluded = new List<String>();
        for (Id qlId : rejectedDisplayedQuoteLineIds) {
            excluded.add('\'' + qlId + '\'');
        }

        return 'Id NOT IN (' + String.join(excluded, ',') + ')';
    }

    public static List<md_reportContractWrapper.EnrichmentData> getContractEnrichmentData(List<Id> quoteIds) {
        if (serviceException != null) throw serviceException;
        if (quoteIds == null || quoteIds.isEmpty()) return new List<md_reportContractWrapper.EnrichmentData>();

        List<SBQQ__QuoteLine__c> quoteLines = [
            SELECT Id, PMC_CLM_QuoteLineNumber__c
            FROM SBQQ__QuoteLine__c
            WHERE SBQQ__Quote__c IN :quoteIds
        ];

        if (quoteLines.isEmpty()) return new List<md_reportContractWrapper.EnrichmentData>();

        Map<String, Id> displayedQuoteLineIdByItemNumber = new Map<String, Id>();
        for (SBQQ__QuoteLine__c ql : quoteLines) {
            if (String.isNotBlank(ql.PMC_CLM_QuoteLineNumber__c)) {
                displayedQuoteLineIdByItemNumber.put(ql.PMC_CLM_QuoteLineNumber__c, ql.Id);
            }
        }

        List<Contract_Line_Item__c> lineItems =
            md_reportContractDAO.queryContractLineItemsByLatestQuoteLines(displayedQuoteLineIdByItemNumber.keySet());

        Map<Id, md_reportContractWrapper.EnrichmentData> enrichmentMap = new Map<Id, md_reportContractWrapper.EnrichmentData>();

        for (Contract_Line_Item__c cli : lineItems) {
            Id key = displayedQuoteLineIdByItemNumber.get(cli.Latest_Quote_Line__r?.PMC_CLM_QuoteLineNumber__c);
            if (key != null) {
                enrichmentMap.put(key, buildEnrichmentData(cli, key));
            }
        }
        for (Contract_Line_Item__c cli : lineItems) {
            Id key = displayedQuoteLineIdByItemNumber.get(cli.Original_Quote_Line__r?.PMC_CLM_QuoteLineNumber__c);
            if (key != null && !enrichmentMap.containsKey(key)) {
                enrichmentMap.put(key, buildEnrichmentData(cli, key));
            }
        }
        for (Contract_Line_Item__c cli : lineItems) {
            Id key = displayedQuoteLineIdByItemNumber.get(cli.Quote_Line__r?.PMC_CLM_QuoteLineNumber__c);
            if (key != null && !enrichmentMap.containsKey(key)) {
                enrichmentMap.put(key, buildEnrichmentData(cli, key));
            }
        }

        return enrichmentMap.values();
    }

    private static md_reportContractWrapper.EnrichmentData buildEnrichmentData(Contract_Line_Item__c cli, Id resolvedQuoteLineId) {
        md_reportContractWrapper.EnrichmentData data = new md_reportContractWrapper.EnrichmentData();
        data.quoteLineId = resolvedQuoteLineId;
        data.originalQuoteId = cli.Contract__r?.SBQQ__Quote__c;
        data.contractNumber = cli.Latest_Quote_Line__r?.SBQQ__Quote__r?.PMC_CLM_DocumentNumber__c;
        data.sapItemNumber = cli.Latest_Subscription__r?.MD_SAPItemNumber__c
            ?? cli.Original_Subscription_Ref__r?.MD_SAPItemNumber__c
            ?? cli.Subscription__r?.MD_SAPItemNumber__c;
        data.startDate = cli.Contract__r.StartDate;
        data.endDate = cli.Contract__r.EndDate;
        data.contractQty = cli.Quantity__c ?? 0;
        data.openOrderQty = cli.Invoiced_Quantity__c ?? 0;
        data.shippedQty = cli.Total_Consumed_Quantity__c ?? 0;
        data.remainingQty = cli.Total_Available_Quantity__c ?? 0;
        data.lineStatus = cli.Line_Status__c;
        data.contractStatus = computeContractStatus(cli.Contract__r.StartDate, cli.Contract__r.EndDate, cli.Total_Available_Quantity__c);
        Set<String> autoClosedValues = new Set<String>{ 'Y1', 'Y2' };
        if (autoClosedValues.contains(cli.Original_Subscription_Ref__r?.AutoClosedInfo__c) ||
            autoClosedValues.contains(cli.Latest_Subscription__r?.AutoClosedInfo__c)) {
            data.contractStatus = 'Completed';
        }
        return data;
    }

    public static md_reportContractWrapper.FilterOptions getContractFilterOptions(
        String baseWhereClause,
        List<Id> quoteIds,
        List<String> appliedContractType,
        List<String> appliedProduct,
        List<String> appliedOrigin,
        List<String> appliedShipTo
    ) {
        md_reportContractWrapper.FilterOptions options = new md_reportContractWrapper.FilterOptions();

        String whereClause = buildFilterOptionsWhereClause(
            baseWhereClause, quoteIds,
            appliedContractType, appliedProduct, appliedOrigin, appliedShipTo
        );

        Set<String> contractTypes = new Set<String>();
        Set<String> products = new Set<String>();
        Set<String> origins = new Set<String>();
        Set<String> shipTos = new Set<String>();

        for (SBQQ__QuoteLine__c ql : md_reportContractDAO.queryFilterOptionsQuoteLines(whereClause)) {
            if (ql.SBQQ__Quote__r?.PMC_CPQ_ContractType__c != null) contractTypes.add(ql.SBQQ__Quote__r.PMC_CPQ_ContractType__c);
            if (ql.SBQQ__ProductName__c != null) products.add(ql.SBQQ__ProductName__c);
            if (ql.PMC_CPQ_ProductLocation__r?.Name != null) origins.add(ql.PMC_CPQ_ProductLocation__r.Name);
            if (ql.PMC_CPQ_ShipTo__r?.ShipToFormula__c != null) shipTos.add(ql.PMC_CPQ_ShipTo__r.ShipToFormula__c);
        }

        options.contractType = new List<String>(contractTypes);
        options.product = new List<String>(products);
        options.origin = new List<String>(origins);
        options.shipTo = new List<String>(shipTos);

        options.contractType.sort();
        options.product.sort();
        options.origin.sort();
        options.shipTo.sort();

        return options;
    }

    public static Map<Id, Map<String, Object>> getQuotesWithContractFile(List<Id> quoteIds) {
        if (serviceException != null) throw serviceException;
        Map<Id, Map<String, Object>> result = new Map<Id, Map<String, Object>>();
        if (quoteIds == null || quoteIds.isEmpty()) return result;

        Set<Id> uniqueIds = new Set<Id>(quoteIds);
        uniqueIds.remove(null);
        for (Id qid : uniqueIds) {
            result.put(qid, new Map<String, Object>{ 'hasFile' => false });
        }

        Map<Id, ContentDocumentLink> latestByQuote = md_reportContractDAO.queryLatestContractLinksByQuotes(uniqueIds);

        for (Id qid : latestByQuote.keySet()) {
            ContentDocumentLink cdl = latestByQuote.get(qid);
            Id cvId = cdl.ContentDocument.LatestPublishedVersionId;
            if (cvId == null) continue;
            result.put(qid, new Map<String, Object>{
                'hasFile'     => true,
                'downloadUrl' => '/sfc/servlet.shepherd/version/download/' + cvId,
                'fileName'    => cdl.ContentDocument.Title
            });
        }

        return result;
    }

    public static Map<String, Object> downloadContractFile(Id contentVersionId) {
        if (serviceException != null) throw serviceException;
        if (contentVersionId == null) {
            throw new AuraHandledException('contentVersionId is required.');
        }
        List<ContentVersion> cvs = md_reportContractDAO.queryContentVersion(contentVersionId);
        if (cvs.isEmpty()) {
            throw new AuraHandledException('File not found.');
        }
        ContentVersion cv = cvs[0];
        return new Map<String, Object>{
            'fileName' => cv.Title + (String.isNotBlank(cv.FileExtension) ? '.' + cv.FileExtension : ''),
            'mimeType' => 'application/pdf',
            'base64'   => EncodingUtil.base64Encode(cv.VersionData)
        };
    }

    public static Map<String, Object> getQuoteContractDownloadUrl(Id quoteId) {
        if (serviceException != null) throw serviceException;
        Map<String, Object> result = new Map<String, Object>();
        if (quoteId == null) {
            result.put('success', false);
            result.put('message', 'There is no Sales Contract PDF file available for download.');
            return result;
        }

        List<ContentDocumentLink> links = md_reportContractDAO.queryLatestContractLinkByQuote(quoteId);

        if (links.isEmpty() || links[0].ContentDocument.LatestPublishedVersionId == null) {
            result.put('success', false);
            result.put('message', 'There is no Sales Contract PDF file available for download.');
            return result;
        }

        String versionId = String.valueOf(links[0].ContentDocument.LatestPublishedVersionId);
        result.put('success', true);
        result.put('downloadUrl', '/sfc/servlet.shepherd/version/download/' + versionId);
        result.put('fileName', links[0].ContentDocument.Title);
        return result;
    }

    public static String computeContractStatus(Date startDate, Date endDate, Decimal availableQty) {
        if (availableQty != null && availableQty <= 0) return 'Completed';
        if (endDate != null && Date.today() > endDate) return 'Expired';
        return 'Open';
    }

    private static String buildFilterOptionsWhereClause(
        String baseWhereClause,
        List<Id> quoteIds,
        List<String> appliedContractType,
        List<String> appliedProduct,
        List<String> appliedOrigin,
        List<String> appliedShipTo
    ) {
        List<String> parts = new List<String>();

        if (String.isNotBlank(baseWhereClause)) parts.add('(' + baseWhereClause + ')');

        if (quoteIds != null && !quoteIds.isEmpty()) {
            List<String> quoted = new List<String>();
            for (Id qId : quoteIds) quoted.add('\'' + qId + '\'');
            parts.add('SBQQ__Quote__c IN (' + String.join(quoted, ',') + ')');
        }

        if (appliedContractType != null && !appliedContractType.isEmpty()) {
            parts.add('SBQQ__Quote__r.PMC_CPQ_ContractType__c IN (' + toSoqlList(appliedContractType) + ')');
        }

        if (appliedProduct != null && !appliedProduct.isEmpty()) {
            parts.add('SBQQ__ProductName__c IN (' + toSoqlList(appliedProduct) + ')');
        }

        if (appliedOrigin != null && !appliedOrigin.isEmpty()) {
            parts.add('PMC_CPQ_ProductLocation__r.Name IN (' + toSoqlList(appliedOrigin) + ')');
        }

        if (appliedShipTo != null && !appliedShipTo.isEmpty()) {
            parts.add('PMC_CPQ_ShipTo__r.ShipToFormula__c IN (' + toSoqlList(appliedShipTo) + ')');
        }

        return String.join(parts, ' AND ');
    }

    private static String toSoqlList(List<String> values) {
        List<String> escaped = new List<String>();
        for (String v : values) escaped.add('\'' + String.escapeSingleQuotes(v) + '\'');
        return String.join(escaped, ',');
    }
}