force-app/main/default/objects/Contract/fields/PMC_CLM_AmendmentNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CLM_AmendmentNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field will store the numerical value representing the number of times this contract has been amended</description>
    <label>Amendment Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/MassUpdateExecutionLine__c.object-meta.xml
<CustomObject>
    <label>Mass Update Execution Line</label>
    <nameField>
        <displayFormat>EXL-{0000}</displayFormat>
        <label>Execution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Execution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/CheckEligibilityStatus__c.field-meta.xml
<CustomField>
    <fullName>CheckEligibilityStatus__c</fullName>
    <label>Check Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Mass Update Execution Lines</relationshipLabel>
    <relationshipName>MassUpdateExecutionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/CreatedQuote__c.field-meta.xml
<CustomField>
    <fullName>CreatedQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Mass Update Execution Lines</relationshipLabel>
    <relationshipName>MassUpdateExecutionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/FinishedSteps__c.field-meta.xml
<CustomField>
    <fullName>FinishedSteps__c</fullName>
    <label>FinishedSteps</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generate Amendments</fullName>
            </value>
            <value>
                <fullName>Check Eligibility</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Generate Contracts</fullName>
            </value>
            <value>
                <fullName>Update Quotes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check Eligibility</fullName>
            </value>
            <value>
                <fullName>Generate Amendments</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Generate Contracts</fullName>
            </value>
            <value>
                <fullName>Update Quotes</fullName>
            </value>
            <value>
                <fullName>Check Elegibility</fullName>
                <isActive>false</isActive>
                <label>Check Elegibility</label>
            </value>
            <value>
                <fullName>Generate Contract</fullName>
                <isActive>false</isActive>
                <label>Generate Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Approvals (Quote)</relationshipLabel>
    <relationshipName>Approvals1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <description>Field which automatically gets updated when a Quote is submitted to approval/ it&apos;s approved/ it&apos;s rejected.</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_AutoApprovedToggle__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_AutoApprovedToggle__c</fullName>
    <defaultValue>false</defaultValue>
    <description>toggle checkbox to validate a quote is auto approved through screenflow</description>
    <label>Auto Approved Toggle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_FlowVRByPassToggle__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FlowVRByPassToggle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flow VR ByPass Toggle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SubmittedUser__c.field-meta.xml
<CustomField>
    <fullName>SubmittedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created to enable Advanced Approvals for quote object</description>
    <label>Submitted User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractSubmitForApprovalQueueable.cls
/**
 * Queueable class to submit approval for a quote and update execution line status/step.
 */
public with sharing class ContractSubmitForApprovalQueueable implements Queueable, Database.AllowsCallouts {
    private Id executionLineId;
    private Id quoteId;

    public ContractSubmitForApprovalQueueable(Id executionLineId, Id quoteId) {
        this.executionLineId = executionLineId;
        this.quoteId = quoteId;
    }

    public void execute(QueueableContext context) {
        if (executionLineId == null || quoteId == null) {
            return;
        }

        // MassUpdateExecutionLine__c line = [SELECT Id, Status__c, Step__c FROM MassUpdateExecutionLine__c WHERE Id = :executionLineId LIMIT 1];
        // try {
        //     // Fire approval submission
        //     SBAA.ApprovalAPI.submit(quoteId, SBAA__Approval__c.Quote__c);
        //     line.Status__c = 'In Progress';
        //     line.Step__c = 'Submit for Approval';
        //     update line;
        // } catch (Exception ex) {
        //     line.Status__c = 'Error';
        //     line.Step__c = 'Submit for Approval';
        //     update line;
        //     throw ex;
        // }

        List<MassUpdateExecutionLine__c> lines = [
            SELECT Id, CreatedQuote__c, Status__c, Step__c, FinishedSteps__c, Contract__c, Contract__r.PMC_CLM_AmendmentNumber__c
            FROM MassUpdateExecutionLine__c
            WHERE Id = :executionLineId AND CheckEligibilityStatus__c = 'Eligible'
        ];
        try {
            List<SBQQ__Quote__c> quotes = new List<SBQQ__Quote__c>();
            for (MassUpdateExecutionLine__c line : lines) {
                if (line.CreatedQuote__c != null) {
                    line.Status__c = 'Success';
                    line.Step__c = 'Submit for Approval';
                    line.FinishedSteps__c = StringUtils.addPicklistValueToMultiSelect(line.FinishedSteps__c, 'Submit for Approval');
                    quotes.add(
                        new SBQQ__Quote__c(
                            Id = line.CreatedQuote__c,
                            SBQQ__Status__c = 'Approved',
                            ApprovalStatus__c = 'Approved',
                            PMC_CPQ_FlowVRByPassToggle__c = true,
                            PMC_CPQ_AutoApprovedToggle__c = true,
                            SubmittedUser__c = UserInfo.getUserId()
                        )
                    );
                }
            }
            if (!lines.isEmpty()) {
                SBQQ.TriggerControl.disable();
                update lines;
                update quotes;
                SBQQ.TriggerControl.enable();
            }
            // Update the quote status to accepted so that the PMC_CPQ_AfterCreateUpdateQuoteFlow updates contract's PMC_CLM_AmendmentNumber__c correctly.
            if (!quotes.isEmpty()) {
                for (SBQQ__Quote__c quote : quotes) {
                    quote.SBQQ__Status__c = 'Accepted';
                }
                SBQQ.TriggerControl.disable();
                update quotes;
                SBQQ.TriggerControl.enable();
            }
        } catch (Exception ex) {
            update new MassUpdateExecutionLine__c(
                Id = executionLineId,
                Message__c = ex.getMessage(),
                Status__c = 'Error',
                Step__c = 'Submit for Approval'
            );
        }
    }
}