force-app/main/default/objects/Contract/fields/PMC_CPQ_LatestQuote__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_LatestQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Contracts (Latest Quote)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000}</displayFormat>
        <label>Contract Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Invoiced_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Invoiced_Quantity__c</fullName>
    <inlineHelpText>Sum of all invoices subtracting return invoices and NOT adding cancelled and FA invoices.</inlineHelpText>
    <label>Invoiced Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Latest_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Latest_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest QL</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Contract Line Items (Latest QL)</relationshipLabel>
    <relationshipName>Contract_Line_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Latest_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Sub</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Contract Line Items (Latest Sub)</relationshipLabel>
    <relationshipName>Contract_Line_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Amended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Original_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Original_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original QL</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Contract Line Items (Original QL)</relationshipLabel>
    <relationshipName>Contract_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Original_Subscription_Ref__c.field-meta.xml
<CustomField>
    <fullName>Original_Subscription_Ref__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Sub</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Contract Line Items (Original Sub)</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/PMC_CPQ_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RejectionReason__c</fullName>
    <label>Rejected Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Quantity contracted. This is only changed with amendments.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Available_Quantity__c</fullName>
    <inlineHelpText>Quantity available to be consumed from the contract into sales order.</inlineHelpText>
    <label>Total Available Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Consumed_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Consumed_Quantity__c</fullName>
    <inlineHelpText>Invoiced quantity subtracting ordered quantity.</inlineHelpText>
    <label>Qty to Ship</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Total_Ordered_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Ordered_Quantity__c</fullName>
    <inlineHelpText>Sum of all sales orders subtracting return orders and NOT adding cancelled and rejected orders and order lines.</inlineHelpText>
    <label>Total Ordered Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CLM_DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CLM_DocumentNumber__c</fullName>
    <description>This field will store the contract document number</description>
    <formula>IF(TEXT(SBQQ__Type__c) &lt;&gt; &apos;Amendment&apos;,
SUBSTITUTE(Name,&quot;Q-&quot;,&quot;&quot;),
SUBSTITUTE(SBQQ__Opportunity2__r.SBQQ__AmendedContract__r.SBQQ__Quote__r.Name ,&quot;Q-&quot;,&quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Document Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ProductLocation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ProductLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Field captures the Location of the product.This is as per the  US GCPM 1064</description>
    <label>Product Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Origin Location</value>
        </filterItems>
        <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
    <relationshipLabel>CPQ Quotes</relationshipLabel>
    <relationshipName>CPQ_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RejectionReason__c</fullName>
    <description>This field is created as a part of story to handle/store value of Rejection Reason for any Quote.</description>
    <inlineHelpText>Reason for which the Quote was rejected</inlineHelpText>
    <label>Rejection Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CLM_QuoteLineNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CLM_QuoteLineNumber__c</fullName>
    <formula>IF	(
	TEXT(SBQQ__Quote__r.SBQQ__Type__c) &lt;&gt; &apos;Amendment&apos;,
		SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(Name,&quot;QL-&quot;,&quot;&quot;),
		IF	(
				ISNULL(SBQQ__UpgradedSubscription__c) ||  ISBLANK(SBQQ__UpgradedSubscription__c),
				SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__AmendedContract__r.SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(Name,&quot;QL-&quot;,&quot;&quot;),
				SBQQ__UpgradedSubscription__r.SBQQ__QuoteLine__r.SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(SBQQ__UpgradedSubscription__r.SBQQ__QuoteLine__r.Name ,&quot;QL-&quot;,&quot;&quot;) 	
			)
	)</formula>
    <label>Quote Line Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_ProductLocation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ProductLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Field captures the Location of the product.</description>
    <label>Product Location</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>$Source.SBQQ__Product__c</field>
            <operation>equals</operation>
            <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
        </filterItems>
        <filterItems>
            <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Origin Location</value>
        </filterItems>
        <infoMessage>Select Product Location Columns Link to add appropriate Locations</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/AutoClosedInfo__c.field-meta.xml
<CustomField>
    <fullName>AutoClosedInfo__c</fullName>
    <label>Auto Closed Info</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DN</fullName>
                <label>Reel not cleared</label>
            </value>
            <value>
                <fullName>PB</fullName>
                <label>Prepay Block</label>
            </value>
            <value>
                <fullName>Y1</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Y2</fullName>
                <label>Closed for Orders</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/Contract_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Contract_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Line Item</label>
    <referenceTo>Contract_Line_Item__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/MD_SAPItemNumber__c.field-meta.xml
<CustomField>
    <fullName>MD_SAPItemNumber__c</fullName>
    <label>SAP Item Number</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PMC_CPQ_ProductLocation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ProductLocation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SBQQ__Product__c</field>
            <operation>equals</operation>
            <valueField>PMC_CPQ_ProductLocation__c.PMC_CPQ_ProductName__c</valueField>
        </filterItems>
        <filterItems>
            <field>PMC_CPQ_ProductLocation__c.PMC_CPQ_Location__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Origin Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMC_CPQ_ProductLocation__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PMC_CPQ_RejectionReason__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RejectionReason__c</fullName>
    <label>Rejected Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/md_reportContractDAO.cls
public without sharing class md_reportContractDAO {

    public static Set<Id> queryLatestQuoteIdsByAccounts(Set<Id> accountIds) {
        Set<Id> quoteIds = new Set<Id>();
        for (Contract c : [
            SELECT PMC_CPQ_LatestQuote__c
            FROM Contract
            WHERE AccountId IN :accountIds
            AND PMC_CPQ_LatestQuote__c != null
        ]) {
            quoteIds.add(c.PMC_CPQ_LatestQuote__c);
        }
        return quoteIds;
    }

    public static List<Contract_Line_Item__c> queryContractLineItemsByLatestQuoteLines(Set<String> itemNumbers) {
        return [
            SELECT Id,
                Latest_Quote_Line__c,
                Latest_Quote_Line__r.PMC_CLM_QuoteLineNumber__c,
                Original_Quote_Line__c,
                Original_Quote_Line__r.PMC_CLM_QuoteLineNumber__c,
                Quote_Line__c,
                Quote_Line__r.PMC_CLM_QuoteLineNumber__c,
                Contract__c,
                Contract__r.SBQQ__Quote__c,
                Latest_Quote_Line__r.SBQQ__Quote__r.PMC_CLM_DocumentNumber__c,
                Contract__r.StartDate,
                Contract__r.EndDate,
                Quantity__c,
                Invoiced_Quantity__c,
                Total_Ordered_Quantity__c,
                Total_Consumed_Quantity__c,
                Total_Available_Quantity__c,
                Line_Status__c,
                Original_Subscription_Ref__r.AutoClosedInfo__c,
                Original_Subscription_Ref__r.MD_SAPItemNumber__c,
                Latest_Subscription__r.AutoClosedInfo__c,
                Latest_Subscription__r.MD_SAPItemNumber__c,
                Subscription__r.MD_SAPItemNumber__c
            FROM Contract_Line_Item__c
            WHERE Latest_Quote_Line__r.PMC_CLM_QuoteLineNumber__c IN :itemNumbers
               OR Original_Quote_Line__r.PMC_CLM_QuoteLineNumber__c IN :itemNumbers
               OR Quote_Line__r.PMC_CLM_QuoteLineNumber__c IN :itemNumbers
        ];
    }

    public static List<Contract_Line_Item__c> queryRejectedContractLineItems(Set<String> itemNumbers) {
        return [
            SELECT Id,
                Original_Quote_Line__c,
                Original_Quote_Line__r.PMC_CLM_QuoteLineNumber__c,
                Latest_Quote_Line__c,
                Latest_Quote_Line__r.PMC_CLM_QuoteLineNumber__c,
                Original_Subscription_Ref__r.PMC_CPQ_RejectionReason__c,
                Original_Subscription_Ref__r.AutoClosedInfo__c,
                Latest_Subscription__r.AutoClosedInfo__c
            FROM Contract_Line_Item__c
            WHERE (Latest_Quote_Line__r.PMC_CLM_QuoteLineNumber__c IN :itemNumbers
                OR Original_Quote_Line__r.PMC_CLM_QuoteLineNumber__c IN :itemNumbers)
            AND Original_Subscription_Ref__c != null
        ];
    }

    public static List<SBQQ__QuoteLine__c> queryFilterOptionsQuoteLines(String whereClause) {
        String soql =
            'SELECT Id,' +
            ' SBQQ__ProductName__c,' +
            ' PMC_CPQ_ProductLocation__r.Name,' +
            ' PMC_CPQ_ShipTo__r.ShipToFormula__c,' +
            ' SBQQ__Quote__r.PMC_CPQ_ContractType__c' +
            ' FROM SBQQ__QuoteLine__c' +
            (String.isNotBlank(whereClause) ? ' WHERE ' + whereClause : '') +
            ' LIMIT 2000';
        return Database.query(soql);
    }

    public static Map<Id, ContentDocumentLink> queryLatestContractLinksByQuotes(Set<Id> quoteIds) {
        Map<Id, ContentDocumentLink> latestByQuote = new Map<Id, ContentDocumentLink>();
        String cdlQuery = 'SELECT LinkedEntityId, Visibility, ContentDocument.LatestPublishedVersionId, ContentDocument.Title, ContentDocument.LastModifiedDate ' +
                          'FROM ContentDocumentLink ' +
                          'WHERE LinkedEntityId IN :quoteIds ' +
                          'ORDER BY ContentDocument.LastModifiedDate DESC';
        Map<String, Object> cdlBinds = new Map<String, Object>{ 'quoteIds' => quoteIds };
        for (ContentDocumentLink cdl : (List<ContentDocumentLink>) Database.queryWithBinds(cdlQuery, cdlBinds, System.AccessLevel.SYSTEM_MODE)) {
            if (!latestByQuote.containsKey((Id) cdl.LinkedEntityId)) {
                latestByQuote.put((Id) cdl.LinkedEntityId, cdl);
            }
        }
        return latestByQuote;
    }

    public static List<ContentVersion> queryContentVersion(Id cvId) {
        return (List<ContentVersion>) Database.queryWithBinds(
            'SELECT Id, Title, FileExtension, VersionData FROM ContentVersion WHERE Id = :cvId',
            new Map<String, Object>{ 'cvId' => cvId },
            System.AccessLevel.SYSTEM_MODE
        );
    }

    public static List<ContentDocumentLink> queryLatestContractLinkByQuote(Id quoteId) {
        return [
            SELECT ContentDocumentId,
                   ContentDocument.LatestPublishedVersionId,
                   ContentDocument.Title,
                   ContentDocument.LastModifiedDate
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :quoteId
            WITH SECURITY_ENFORCED
            ORDER BY ContentDocument.LastModifiedDate DESC
            LIMIT 1
        ];
    }
}