force-app/main/default/objects/Contract/fields/PMC_CPQ_SAPContractReference__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPContractReference__c</fullName>
    <formula>SBQQ__Quote__r.PMC_CPQ_SAPContractReference__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Contract Reference</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/PMC_CPQ_TransactionLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>This will show the status of the response of the external callout.</description>
    <label>Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_InterfaceURL__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_InterfaceURL__c</fullName>
    <description>This is the endpoint that was hit during the transaction.</description>
    <label>Interface URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RequestBody__c</fullName>
    <description>This is the request body sent to the external system.</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ResponseBody__c</fullName>
    <description>This field stores the response body of the request made to the external system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationMessage__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the integration response message</description>
    <inlineHelpText>receives the Integration response message</inlineHelpText>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the overall integration status.</description>
    <inlineHelpText>Indicates the over all integration status</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_SAPContractReference__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPContractReference__c</fullName>
    <description>This field stores the Contract Number generated on SAP.</description>
    <externalId>true</externalId>
    <label>SAP Contract Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PMC_CPQ_SetContractRefResource.cls
/** @description This class will be used to create and expose a custom web service end point for CPI to call with response to the 
 * published amend quote/update contract event . 
 *  @author 
 *  @storynumber -SIR-27
 */
@RestResource(urlMapping='/quote/contractupdate')
global without sharing class PMC_CPQ_SetContractRefResource {
    static final String STRING_INTEGRATIONSTATUSERROR = 'Error';
	static final String STRING_INTEGRATIONSTATUSSUCCESS = 'Success';
	static final String STRING_GETPRICEPREFIX = 'Contract Update: ';
    static final string STRING_SFRECORDID = 'SFRecordId';    
    static String strTransactionLogStatus;
    static List<PMC_CPQ_TransactionLog__c> lstTransactionLogs;
    
    /** 
     * @description This is the apex method that will be exposed as HTTP POST action that will be called by CPI.
     * @param 
     */
    
    @HttpPost
	global static void saveQuoteContractRef() {
		RestRequest req = RestContext.request;
		RestResponse res = RestContext.response;
		SBQQ__Quote__c quoteRecord;
		List<SBQQ__Quote__c> lstQuotes;
		Map<String, Object> jsonResponse;
		String reqBody = req.requestBody.toString();
		String resBody = '';
        String strEndpoint = '/http/UpdateContractRecords';
		PMC_CPQ_TransactionLog__c transactionLog = new PMC_CPQ_TransactionLog__c();
		transactionLog.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
		transactionLog.PMC_CPQ_InterfaceURL__c = strEndpoint;
		List<Object> lstObjContainer= new List<Object>();
        List<Object> lstFilteredList = new List<Object>();
        Set<String> quoteSFRecIdSet = new Set<String>();
		list<SBQQ__QuoteLine__c> QuoteItemUpdate=new list<SBQQ__QuoteLine__c>();
        String strSerializedBody;
        
        Map<String, String> mapTransactionLogFields = new Map<String,String>();
        mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c',strTransactionLogStatus);
        mapTransactionLogFields.put('PMC_CPQ_InterfaceURL__c',strEndpoint);
        mapTransactionLogFields.put('PMC_CPQ_RequestBody__c',reqBody);
        mapTransactionLogFields.put('PMC_CPQ_ResponseBody__c','');
        try {
			lstObjContainer = (List<Object>) JSON.deserializeUntyped(reqBody);
            lstFilteredList = PMC_CPQ_CPIQuoteContractIntegrationClass.getFilteredList(lstObjContainer);//removes duplicate records and non essential values
            for(Object curObjContainer: lstFilteredList)//parse through filtered list 
            {
                Map<String,Object> mapRecord = (Map<String,Object>)curObjContainer;
                quoteSFRecIdSet.add((Id)mapRecord.get(STRING_SFRECORDID));
            }
            
            lstQuotes = [
					SELECT Id, PMC_CPQ_SAPContractReference__c, PMC_CPQ_IntegrationStatus__c, PMC_CPQ_IntegrationMessage__c 
					FROM SBQQ__Quote__c
					WHERE Id in  :quoteSFRecIdSet					
				];
            // Convert Set to List using the List constructor
			List<String> lstIds = new List<String>(quoteSFRecIdSet);
            strSerializedBody = PMC_CPQ_CPIRemoteCalloutUtilityClass.createMinimalPayload(lstIds);
            
            if (lstQuotes.isEmpty()) {
					throw new CustomException('Quotes not found!');
			}
            
            PMC_CPQ_CPIQuoteContractIntegrationClass.parseQuoteContractFilteredList(lstQuotes, lstFilteredList, strEndpoint, lstObjContainer);
            strTransactionLogStatus = PMC_CPQ_CPIQuoteContractIntegrationClass.getOverallTransactionStatus();
            if(strTransactionLogStatus == STRING_INTEGRATIONSTATUSERROR){
            	PMC_CPQ_CPIQuoteContractIntegrationClass.getFilteredErrorList(lstObjContainer,lstQuotes,QuoteItemUpdate,strEndpoint);
            }

            SObjectAccessDecision securityDecisionQuote = Security.stripInaccessible(AccessType.UPDATABLE, lstQuotes);
            Database.update(securityDecisionQuote.getRecords(),false);

           // PMC_CPQ_CPIQuoteContractIntegrationClass.parseAndUpdateQuoteLineFields(lstObjContainer);
            
            
            res.statusCode = 200;
            
            
        	mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c',strTransactionLogStatus);
        	                    
        	if (strTransactionLogStatus == STRING_INTEGRATIONSTATUSERROR) {
        		mapTransactionLogFields = PMC_CPQ_TransactionLogUtilityClass.extractQuoteAndErrorMsg(reqBody,
                                                                                            strSerializedBody,
                                                                                            mapTransactionLogFields );
        	}
        
        	
        	
								
			
		} catch (Exception ex) {
			System.debug(ex.getMessage());
            mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c',STRING_INTEGRATIONSTATUSERROR);
            mapTransactionLogFields = PMC_CPQ_TransactionLogUtilityClass.extractQuoteAndErrorMsg(reqBody,
                                                                                            strSerializedBody,
                                                                                            mapTransactionLogFields );
			res.statusCode = 500;
			if (lstQuotes!=null && !lstQuotes.isEmpty()) {				
				resBody = '{"error":"Internal Server Error","details":"' + ex.getMessage() + '","quoteId":"' + lstQuotes[0].Id + '"}';			
				
			} else {
				resBody = '{"error":"Internal Server Error","details":"' + ex.getMessage() + '","quoteId":""}';
			}
		}
		
		res.responseBody = Blob.valueOf(resBody);
        lstTransactionLogs = PMC_CPQ_TransactionLogUtilityClass.addTransactionLog(mapTransactionLogFields);
		PMC_CPQ_TransactionLogUtilityClass.insertTransactionLogs(lstTransactionLogs);
		
	}

}