force-app/main/default/objects/Contract/fields/PMC_CPQ_ContractShippingInstructions__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractShippingInstructions__c</fullName>
    <description>Shipping Instructions</description>
    <label>Shipping Instructions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_ProcessSwitches__c/PMC_ProcessSwitches__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This Custom Setting is for implementing bypass framework for triggers, flows, integrations and validation rules.</description>
    <label>Process Switches</label>
</CustomObject>

force-app/main/default/objects/PMC_ProcessSwitches__c/fields/PMC_BypassValidationRule__c.field-meta.xml
<CustomField>
    <fullName>PMC_BypassValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to bypass the validation rules</description>
    <label>Bypass Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_SS_AccountSalesAreaRelationship__c/PMC_SS_AccountSalesAreaRelationship__c.object-meta.xml
<CustomObject>
    <description>Junction Object to relate Account and Sales Areas</description>
    <label>Account Sales Area Relationship</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_SS_AccountSalesAreaRelationship__c/fields/PMC_SS_Account__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Account__c</fullName>
    <description>Master Detail relationship between Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Areas</relationshipLabel>
    <relationshipName>AccountSalesAreRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMC_SS_AccountSalesAreaRelationship__c/fields/PMC_SS_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SalesArea__c</fullName>
    <description>Master Detail relationship to Sales Area</description>
    <label>Sales Area</label>
    <referenceTo>PMC_SS_SalesArea__c</referenceTo>
    <relationshipName>AccountSalesAreRelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/PMC_SS_SalesArea__c.object-meta.xml
<CustomObject>
    <description>Sales Area Object</description>
    <label>Sales Area</label>
    <nameField>
        <label>Sales Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_CPQ_SAPSalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPSalesOrganization__c</fullName>
    <description>Field to uniquely identify SAP Sales Organization</description>
    <externalId>true</externalId>
    <label>SAP Sales Organization</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_SS_DistributionChannel__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_DistributionChannel__c</fullName>
    <description>Specifies the Distribution Channel</description>
    <label>Distribution Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <label>Common</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_SS_Division__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Division__c</fullName>
    <description>Specifies the Division</description>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Domestic</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>Export</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Intercompany</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_SS_SalesArea__c/fields/PMC_SS_SalesOrganization__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_SalesOrganization__c</fullName>
    <description>Specifies the Sales Organization</description>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fospar SA</fullName>
            </value>
            <value>
                <fullName>Comp. Minera Miski Mayo</fullName>
                <label>Minera Miski Mayo</label>
            </value>
            <value>
                <fullName>Mos. Sulphur Partner</fullName>
            </value>
            <value>
                <fullName>Mos Ag Innovation Sol,LLC</fullName>
                <label>Mosaic Ag Innov Sol</label>
            </value>
            <value>
                <fullName>Mosaic Potash Colonsay UL</fullName>
                <label>Mosaic CA Colonsay</label>
            </value>
            <value>
                <fullName>Mosaic CA Crop Nutrit, LP</fullName>
                <label>Mosaic CA Crop Nutri</label>
            </value>
            <value>
                <fullName>Mosaic Potash Esterhazy</fullName>
                <label>Mosaic CA Esterhazy</label>
            </value>
            <value>
                <fullName>Mosaic Canada ULC (BP)</fullName>
                <label>Mosaic CA ULC (BP)</label>
            </value>
            <value>
                <fullName>Mosaic Crop Nutrition LLC</fullName>
                <label>Mosaic CN Fertilizer</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (HK) L</fullName>
                <label>Mosaic Fert. (HK)</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizantes Ltd.</fullName>
                <label>Mosaic Fert Bahamas</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (BJ)</fullName>
                <label>Mosaic Fert BMF</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizantes do B</fullName>
                <label>Mosaic Fert Brasil</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizer LLC</fullName>
                <label>Mosaic Fertilizer</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizantes P&amp;K</fullName>
                <label>Mosaic Fert P&amp;K</label>
            </value>
            <value>
                <fullName>Mosaic Fertz Paraguay SRL</fullName>
                <label>Mosaic Fert Paraguay</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (QHD)</fullName>
                <label>Mosaic Fert QMF</label>
            </value>
            <value>
                <fullName>Mosaic Fertilizers (YT)</fullName>
                <label>Mosaic Fert YMF</label>
            </value>
            <value>
                <fullName>Mosaic Global Sales LLC</fullName>
                <label>Mosaic Global Sales</label>
            </value>
            <value>
                <fullName>Mosaic India Private Ltd.</fullName>
                <label>Mosaic India Pvt Ltd</label>
            </value>
            <value>
                <fullName>Mosaic Potash Carlsbad In</fullName>
                <label>Mosaic Potash Carlsb</label>
            </value>
            <value>
                <fullName>Mosaic Potássio Mineração</fullName>
                <label>Mosaic Potássio Mine</label>
            </value>
            <value>
                <fullName>Tampa Port Services, LLC</fullName>
                <label>Tampa Port Services</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/PMC_CPQ_Region__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Region__c</fullName>
    <description>To identify which product belongs to which region so that the product selection can be done accurately. Avoiding cross-region sales. etc,</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_AccountManager__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field captures the Account manager for each quote</description>
    <inlineHelpText>Indicates the Account manager for the Quote</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractLanguage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractLanguage__c</fullName>
    <description>If region is North America, then English, else if region is Brazil, then ask Account Manager to select Spanish or Portuguese</description>
    <label>Output Document Language</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PMC_CPQ_Region__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Portuguese</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractShippingInstructions__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractShippingInstructions__c</fullName>
    <description>Shipping Instructions</description>
    <label>Shipping Instructions</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_EstFreightPrice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_EstFreightPrice__c</fullName>
    <description>This field is created to check the estimated freight value. This is as per the  US GCPM 1064</description>
    <label>Freight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_Region__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Region__c</fullName>
    <description>Set region based on Account Manager/SSR</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.SBQQ__Account__c</field>
            <operation>equals</operation>
            <valueField>PMC_SS_AccountSalesAreaRelationship__c.PMC_SS_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>Account for which this quote has been created.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Area</label>
    <referenceTo>PMC_SS_AccountSalesAreaRelationship__c</referenceTo>
    <relationshipLabel>CPQ Quote Lines</relationshipLabel>
    <relationshipName>PMC_CPQ_CPQQuoteLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/PMC_CPQ_SalesArea__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesArea__c</fullName>
    <description>The Sales Areas associated with the user from which the record type and product will be configured.</description>
    <label>Sales Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_SalesAreaUser</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PMC_CPQ_SalesRegion__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesRegion__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>North Brazil</fullName>
        <isActive>false</isActive>
        <label>North Brazil</label>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
        <isActive>false</isActive>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>Paraguay</fullName>
        <isActive>false</isActive>
        <label>Paraguay</label>
    </customValue>
    <customValue>
        <fullName>Peru</fullName>
        <isActive>false</isActive>
        <label>Peru</label>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
        <isActive>false</isActive>
        <label>Argentina</label>
    </customValue>
    <customValue>
        <fullName>South Brazil</fullName>
        <isActive>false</isActive>
        <label>South Brazil</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <description>This Global Value Set stores/handles values of Region</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMC_CPQ_GenerateQuoteHelperTest.cls
/**
* @description Test class for PMC_CPQ_GenerateQuoteHelper.
* @author Raphael Soares
* @storynumber GCPM-5347
* @changelog
*   GCPM-5347 (2026-07-14): Replaced EnvironmentChecker-based expected values with PMC_CLM_EnvironmentSettingService test overrides; added testMissingEnvironmentSetting
**/
@IsTest
private class PMC_CPQ_GenerateQuoteHelperTest {
    @TestSetup
    static void setup() {
        List<String> lstProfileNames = new List<String>{'System Administrator','Sales User'};
        List<UserRole> userRoleName = [SELECT Id FROM UserRole WHERE Name = 'Service Director'];
        List<String> lstPermissionNames = new List<String>{'PMC_Administrator_Permission_Set_Group','PMC_SLS_Permission_Set_Group'};
        Map<String,Id> mapOfProfiles = PMC_TestUtilityClass.getProfiles(lstProfileNames);
        Map<String,PermissionSetGroup> mapOfPermissionGrp = PMC_TestUtilityClass.getPemissionsetGroups(lstPermissionNames);
        Integer intuserCount = 0;
        User objSystemAdminUser;  
        User objSalesUser;
        List<User> lstUser = PMC_TestUtilityClass.createUser(2);
        for(User objUser : lstUser) {
            if(intuserCount == 0){
                objUser.LastName = 'Admin User Test';
                objUser.ProfileId = mapOfProfiles.get('System Administrator'); 
                objUser.FederationIdentifier = objUser.Username + 'Admin';
                objUser.UserRoleId = userRoleName[0].id;
            }else if(intuserCount == 1){
                objUser.LastName = 'Sales User Test PMC_CPQ_GenerateQuoteHelperTest';
                objUser.ProfileId = mapOfProfiles.get('Sales User'); 
                objUser.FederationIdentifier = objUser.Username + 'Sales';
            }
            objUser.PMC_CPQ_SalesArea__c = 'Mosaic Global Sales LLC Export Common';
            objUser.PMC_CPQ_SalesRegion__c = 'Brazil';
            objUser.isActive = true;                
            objUser.MobilePhone = '1234567890';
            objUser.UserPermissionsKnowledgeUser = true;
            objUser.LanguageLocaleKey = 'en_US';
            intuserCount = intuserCount + 1;
        }            
        insert lstUser;
        objSystemAdminUser = lstUser[0];
        objSalesUser = lstUser[1];
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(
            new List<User>{objSystemAdminUser}, 
            mapOfPermissionGrp.get('PMC_Administrator_Permission_Set_Group')
        );
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(
            new List<User>{objSalesUser}, 
            mapOfPermissionGrp.get('PMC_SLS_Permission_Set_Group')
        );
        
        System.runAs(objSystemAdminUser) {
            PMC_ProcessSwitches__c bypassSetting = PMC_ProcessSwitches__c.getOrgDefaults();
            bypassSetting.PMC_BypassValidationRule__c = true;
            upsert bypassSetting;
            
            Account acc = new Account(Name = 'Test Account', BillingCity = 'toronto', BillingStreet = 'tor');
            insert acc;
            
            PMC_SS_SalesArea__c salesArea = new PMC_SS_SalesArea__c(
                Name = 'Brazil Area',
                PMC_CPQ_SAPSalesOrganization__c = '40000010',
                PMC_SS_SalesOrganization__c = 'Mosaic Global Sales LLC',
                PMC_SS_DistributionChannel__c = '0',
                PMC_SS_Division__c = '20'
            );
            insert salesArea;
            
            PMC_SS_AccountSalesAreaRelationship__c salesAreaAssignment = new PMC_SS_AccountSalesAreaRelationship__c(
                Name = 'Test Sales Area Assignment',
                PMC_SS_Account__c = acc.Id, 
                PMC_SS_SalesArea__c = salesArea.Id
            );
            insert salesAreaAssignment;
            
            Product2 product = new Product2(
                Name = 'Test Product',
                IsActive = true
            );
            insert product;
            
            PricebookEntry pbe = new PricebookEntry(
                Pricebook2Id = Test.getStandardPricebookId(),
                Product2Id = product.Id,
                UnitPrice = 100,
                IsActive = true,
                UseStandardPrice = false
            );
            insert pbe;
            
            SBQQ__Quote__c validQuote = new SBQQ__Quote__c(
                SBQQ__Account__c = acc.Id,
                SBQQ__PriceBook__c = Test.getStandardPricebookId(),
                SBQQ__Primary__c = true,
                PMC_CPQ_SalesArea__c = salesAreaAssignment.Id,
                PMC_CPQ_Region__c = 'Brazil',
                PMC_CPQ_ContractLanguage__c = 'Portuguese',
                PMC_CPQ_ContractShippingInstructions__c = 'Test Shipping Instructions',
                PMC_CPQ_AccountManager__c = objSalesUser.Id
            );
            insert validQuote;
            
            SBQQ__QuoteLine__c quoteLine = new SBQQ__QuoteLine__c(
                SBQQ__Quote__c = validQuote.Id,
                SBQQ__Product__c = product.Id,
                SBQQ__PricebookEntryId__c = pbe.Id,
                SBQQ__Quantity__c = 1,
                SBQQ__NetPrice__c = 100,
                PMC_CPQ_EstFreightPrice__c = 10,
                PMC_CPQ_QuoteRecordType__c = 'Domestic SA',
                PMC_CPQ_QuoteRecordSubType__c = 'B2C - Fertilizer',
                PMC_CPQ_Incoterms1__c = 'CIF'
            );
            insert quoteLine;
        }
    }
    
    @isTest
    static void testValidSpanishContract() {
        User testUser = [SELECT Id, Name FROM User WHERE LastName='Admin User Test' WITH SECURITY_ENFORCED LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id, Name, PMC_CLM_Region__c, PMC_CPQ_ContractLanguage__c FROM SBQQ__Quote__c LIMIT 1];
        System.runAs(testUser) {
            // ======    START    ======      GCPM-5347
            PMC_CLM_EnvironmentSettingService.environmentNameOverride = 'unittest';
            PMC_CLM_EnvironmentSettingService.settingsOverride = new Map<String, PMC_CLM_Environment_Setting__mdt>{
                'unittest' => new PMC_CLM_Environment_Setting__mdt(
                    DeveloperName = 'unittest',
                    PMC_CLM_AccountId__c = '98018',
                    PMC_CLM_BaseUrl__c = 'https://uatna11.springcm.com'
                )
            };
            String expectedParam = 'aid=98018';
            // ======      END      ======      GCPM-5347
            quote.PMC_CPQ_Region__c = 'Brazil';
            quote.PMC_CPQ_ContractLanguage__c = 'Spanish';
            update quote;
            Test.startTest();
            String result = PMC_CPQ_GenerateQuoteHelper.generateContract(quote.Id);
            Test.stopTest();
            System.assert(result.contains(expectedParam), 'Should generate Spanish contract URL' + expectedParam + '\nActual result:' + result);
        }
    }
    
    @isTest
    static void testMissingShippingInstructions() {
        SBQQ__Quote__c quote = [SELECT Id, PMC_CPQ_ContractShippingInstructions__c FROM SBQQ__Quote__c LIMIT 1];
        quote.PMC_CPQ_ContractShippingInstructions__c = null;
        update quote;
        
        Test.startTest();
        try {
            PMC_CPQ_GenerateQuoteHelper.generateContract(quote.Id);
            System.assert(false, 'Expected exception not thrown');
        } catch (CustomException e) {
            System.assertEquals('Shipping Instructions field is empty. Please fill it before generating the contract.', e.getMessage());
        }
        Test.stopTest();
    }
    
    @isTest
    static void testInvalidRegion() {
        PMC_SS_SalesArea__c salesArea = [SELECT Id, PMC_SS_Division__c, PMC_SS_SalesOrganization__c, PMC_CPQ_SAPSalesOrganization__c FROM PMC_SS_SalesArea__c LIMIT 1];
        salesArea.PMC_CPQ_SAPSalesOrganization__c = '123';
        salesArea.PMC_SS_SalesOrganization__c = 'Mosaic Global Sales LLC';
        salesArea.PMC_SS_Division__c = '20';
        update salesArea;
        
        Test.startTest();
        try {
            PMC_CPQ_GenerateQuoteHelper.generateContract([SELECT Id FROM SBQQ__Quote__c LIMIT 1].Id);
            System.assert(false, 'Expected exception not thrown');
        } catch (CustomException e) {
            System.assertEquals('Contract generation is only available for Brazil region.', e.getMessage());
        }
        Test.stopTest();
    }
    
    @isTest
    static void testInvalidLanguage() {
        SBQQ__Quote__c quote = [SELECT Id, Name, PMC_CPQ_Region__c, PMC_CPQ_ContractLanguage__c FROM SBQQ__Quote__c LIMIT 1];
        quote.PMC_CPQ_Region__c = 'Brazil';
        quote.PMC_CPQ_ContractLanguage__c = 'English';
        
        Test.startTest();
        try {
            update quote;
            PMC_CPQ_GenerateQuoteHelper.generateContract(quote.Id);
            System.assert(false, 'Expected exception not thrown');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, bad value for restricted picklist field: English: [PMC_CPQ_ContractLanguage__c]'));
        }
        Test.stopTest();
    }
    
    @isTest
    static void testQuoteNotFound() {
        try {
            Test.startTest();
            PMC_CPQ_GenerateQuoteHelper.generateContract('invalidId');
            Test.stopTest();
            System.assert(false, 'Expected exception not thrown');
        } catch (CustomException e) {
            System.assertEquals('Quote not found or access denied.', e.getMessage());
        }
    }

    // ======    START    ======      GCPM-5347
    // Test environment without a PMC_CLM_Environment_Setting__mdt record — must fail fast, no fallback
    @isTest
    static void testMissingEnvironmentSetting() {
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        PMC_CLM_EnvironmentSettingService.environmentNameOverride = 'newsandbox';
        PMC_CLM_EnvironmentSettingService.settingsOverride = new Map<String, PMC_CLM_Environment_Setting__mdt>();
        String expectedMessage = String.format(System.Label.PMC_CLM_EnvironmentSettingMissing, new List<String>{ 'newsandbox' });

        Test.startTest();
        try {
            PMC_CPQ_GenerateQuoteHelper.generateContract(quote.Id);
            System.assert(false, 'Expected exception not thrown');
        } catch (CustomException e) {
            System.assertEquals(expectedMessage, e.getMessage());
        }
        Test.stopTest();
    }
    // ======      END      ======      GCPM-5347

    @IsTest
    static void testGetQuotePrimaryContact() {
        SBQQ__Quote__c quoteRecord = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Test.startTest();
        Map<String, String> result = PMC_CPQ_GenerateQuoteHelper.getQuotePrimaryContact(quoteRecord.Id);
        Test.stopTest();
        System.assertNotEquals(null, result.get('primaryContactName'));
        System.assertNotEquals(null, result.get('quoteName'));
    }

    @IsTest
    static void testUpdateDocusignPicklist() {
        SBQQ__Quote__c quoteRecord = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        Test.startTest();
        PMC_CPQ_GenerateQuoteHelper.updateDocusignPicklist(quoteRecord.Id, 'Yes');
        Test.stopTest();
        SBQQ__Quote__c updated = [
            SELECT Id, PMC_CPQ_Docusign__c 
            FROM SBQQ__Quote__c 
            WHERE Id = :quoteRecord.Id
        ];
        System.assertEquals('Yes', updated.PMC_CPQ_Docusign__c);
    }
}