force-app/main/default/objects/Contract/fields/PMC_CPQ_ContractShippingInstructions__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractShippingInstructions__c</fullName>
    <description>Shipping Instructions</description>
    <label>Shipping Instructions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/PMC_TriggerSwitches__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata is used to bypass trigger operations.</description>
    <label>PMC Trigger Switches</label>
    <pluralLabel>PMC Trigger Switches</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterDelete__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterInsert__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterUndelete__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_AfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>PMC_AfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_BeforeDelete__c.field-meta.xml
<CustomField>
    <fullName>PMC_BeforeDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_BeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>PMC_BeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMC_TriggerSwitches__mdt/fields/PMC_BeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>PMC_BeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_AccountManager__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field captures the Account manager for each quote</description>
    <inlineHelpText>Indicates the Account manager for the Quote</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractShippingInstructions__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractShippingInstructions__c</fullName>
    <description>Shipping Instructions</description>
    <label>Shipping Instructions</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractStageName__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractStageName__c</fullName>
    <description>This field helps to denote the current stage of the contract document</description>
    <label>Contract Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Signature</fullName>
            </value>
            <value>
                <fullName>Partially Executed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>Accept</fullName>
                <isActive>false</isActive>
                <label>Accept</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Executed / Signed</fullName>
                <isActive>false</isActive>
                <label>Executed / Signed</label>
            </value>
            <value>
                <fullName>Full Executed</fullName>
                <isActive>false</isActive>
                <label>Full Executed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pending Signatures</fullName>
                <isActive>false</isActive>
                <label>Pending Signatures</label>
            </value>
            <value>
                <fullName>Signed</fullName>
                <isActive>false</isActive>
                <label>Signed</label>
            </value>
            <value>
                <fullName>\</fullName>
                <isActive>false</isActive>
                <label>\</label>
            </value>
            <value>
                <fullName>hello</fullName>
                <isActive>false</isActive>
                <label>hello</label>
            </value>
            <value>
                <fullName>test</fullName>
                <isActive>false</isActive>
                <label>test</label>
            </value>
            <value>
                <fullName>yfgfgfc</fullName>
                <isActive>false</isActive>
                <label>yfgfgfc</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the overall integration status.</description>
    <inlineHelpText>Indicates the over all integration status</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RecordTypeName__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_Region__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Region__c</fullName>
    <description>Set region based on Account Manager/SSR</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesOffice__c</fullName>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PMC_CPQ_SalesAreaCombination__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_SalesOfficeCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_VCOQuotation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_VCOQuotation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>check box indicator for VCO quotation</description>
    <label>VCO Quotation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>North Brazil</fullName>
        <isActive>false</isActive>
        <label>North Brazil</label>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
        <isActive>false</isActive>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>Paraguay</fullName>
        <isActive>false</isActive>
        <label>Paraguay</label>
    </customValue>
    <customValue>
        <fullName>Peru</fullName>
        <isActive>false</isActive>
        <label>Peru</label>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
        <isActive>false</isActive>
        <label>Argentina</label>
    </customValue>
    <customValue>
        <fullName>South Brazil</fullName>
        <isActive>false</isActive>
        <label>South Brazil</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <description>This Global Value Set stores/handles values of Region</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PMC_CPQ_SalesOfficeCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR BA B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Canais MT  B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Espec Agricolas B</fullName>
    </customValue>
    <customValue>
        <fullName>BR Espec Industriais</fullName>
    </customValue>
    <customValue>
        <fullName>BR FEED B2B</fullName>
    </customValue>
    <customValue>
        <fullName>BR FOSPAR</fullName>
    </customValue>
    <customValue>
        <fullName>BR GO B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Mega Farmer B</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Retail Norte</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Retail Sul B2</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Trader GO+MT</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Trader INT B2</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Trader MS B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Matopipa B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MG Norte B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MG Sul B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MOS OPERAÇÕES B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MS B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MT Norte B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MT Oeste B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MT SUL B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Pastagem B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR PR/SC 1 B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR PR/SC 2 B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR RS B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR SP Norte B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR  Fertilizer B2B1</fullName>
    </customValue>
    <customValue>
        <fullName>BR  Fertilizer B2B2</fullName>
    </customValue>
    <customValue>
        <fullName>CA All Canpotex</fullName>
    </customValue>
    <customValue>
        <fullName>CA All Services</fullName>
    </customValue>
    <masterLabel>Sales Office Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMC_CPQ_QuoteTriggerHandler.cls
/**
 * @description This class will be used to handle all trigger operations of Quote (SBQQ_Quote__c) object
 * @author Lalit Sharma
 * @storynumber GDASF-8944
 */
public without sharing class PMC_CPQ_QuoteTriggerHandler extends PMC_TriggerHandler {
	/**
	 * These boolean variables are used to bypass the trigger operations
	 */
	private static final Boolean BOOL_BYPASS_BEFORE_INSERT;
	private static final Boolean BOOL_BYPASS_BEFORE_UPDATE;
	private static final Boolean BOOL_BYPASS_BEFORE_DELETE;
	private static final Boolean BOOL_BYPASS_AFTER_INSERT;
	private static final Boolean BOOL_BYPASS_AFTER_UPDATE;
	private static final Boolean BOOL_BYPASS_AFTER_DELETE;
	private static final Boolean BOOL_BYPASS_AFTER_UNDELETE;

	@testVisible
	public static Boolean boolBypassTriggerLogic = false;

	/**
	 * These variables will hold the copy of trigger variables
	 */
	private List<SBQQ__Quote__c> lstNewQuotes;
	private Map<Id, SBQQ__Quote__c> mapNewQuotes;
	private List<SBQQ__Quote__c> lstOldQuotes;
	private Map<Id, SBQQ__Quote__c> mapOldQuotes;

	/**
	 * @description This static block initializes the trigger switches when the class is invoked
	 */
	static {
		PMC_TriggerSwitches__mdt operationSwitches = PMC_TriggerSwitches__mdt.getInstance('Quote');

		BOOL_BYPASS_BEFORE_INSERT = operationSwitches.PMC_BeforeInsert__c;
		BOOL_BYPASS_BEFORE_UPDATE = operationSwitches.PMC_BeforeUpdate__c;
		BOOL_BYPASS_BEFORE_DELETE = operationSwitches.PMC_BeforeDelete__c;
		BOOL_BYPASS_AFTER_INSERT = operationSwitches.PMC_AfterInsert__c;
		BOOL_BYPASS_AFTER_UPDATE = operationSwitches.PMC_AfterUpdate__c;
		BOOL_BYPASS_AFTER_DELETE = operationSwitches.PMC_AfterDelete__c;
		BOOL_BYPASS_AFTER_UNDELETE = operationSwitches.PMC_AfterUndelete__c;
	}
//added by Monika -15-09
    private static final Set<String> allowedEditableFields = new Set<String>{ 
	'PMC_CPQ_ContractShippingInstructions__c', 
   'PMC_CPQ_AccountManager__c', 
   'PMC_CPQ_SalesOffice__c'
    }; 
        private static String runningProfileName;
public static void enforceFieldLock(List<SBQQ__Quote__c> newList, Map<Id, SBQQ__Quote__c> oldMap) {

	/* String runningProfileName = [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT 1].Name;
    if (runningProfileName == 'System Administrator' || runningProfileName == 'API Only profile' ) {
        return;
    } */
    if (runningProfileName == null) {
        runningProfileName = [SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT 1].Name;
    }

    if (runningProfileName == 'System Administrator' || runningProfileName == 'API Only profile' ) {
        return;
    }

    for (SBQQ__Quote__c newRec : newList) {
        SBQQ__Quote__c oldRec = oldMap.get(newRec.Id);

        
        if (oldRec == null || String.isBlank(oldRec.PMC_CPQ_ContractStageName__c)) {
            continue;
        }
        if(newRec.SBQQ__Status__c=='Rejected')
        {
            continue;
        }
       if (newRec.PMC_CPQ_AccountManager__c != oldRec.PMC_CPQ_AccountManager__c) {
            continue; 
        }
         if (newRec.PMC_CPQ_IntegrationStatus__c != oldRec.PMC_CPQ_IntegrationStatus__c) {
            continue; 
        }

		   if (newRec.PMC_CPQ_SalesOffice__c != oldRec.PMC_CPQ_SalesOffice__c) {
            continue; 
        }
        
        Boolean hasInvalidChange = false;

        
        for (SObjectField field : SBQQ__Quote__c.SObjectType.getDescribe().fields.getMap().values()) {
            String fieldName = field.getDescribe().getName();

           
            if (fieldName.endsWith('Id') 
                || fieldName == 'CreatedDate' 
                || fieldName == 'LastModifiedDate' 
                || fieldName == 'LastModifiedById' 
                || fieldName == 'CreatedById') {
                continue;
            }

          
        /*    if (fieldName == 'PMC_CPQ_ContractStageName__c' || allowedEditableFields.contains(fieldName)) {
                continue;
            }*/

           if (fieldName == 'PMC_CPQ_ContractStageName__c')
		   {
			  continue;
		   }
		    Boolean isAllowed = false; 
               if (allowedEditableFields.contains(fieldName) && fieldName != 'PMC_CPQ_ContractShippingInstructions__c') 
                     { isAllowed = true; } 

					  if (fieldName == 'PMC_CPQ_ContractShippingInstructions__c') 
					  {
						   if(newRec.PMC_CPQ_Region__c == 'Brazil')
						   {
							  isAllowed=true;
						   }
					  }if (isAllowed) { continue; } 

            Object oldVal = oldRec.get(fieldName);
            Object newVal = newRec.get(fieldName);

            
            if ((oldVal == null && newVal != null) || (oldVal != null && !oldVal.equals(newVal))) {
                hasInvalidChange = true;
                break;
            }
        }

        if (hasInvalidChange) {
           // newRec.addError('You cannot edit these fields when Contract Stage is set.');
		    newRec.addError(System.Label.PMC_CPQ_ContractSetValue);
        }
    }


}
	// Track processed quotes to prevent infinite loops
	private static Set<Id> processedQuotes = new Set<Id>();

	/**
	 * @description Constructor method to initialize class level variables and store the trigger collections and add the max loop count of trigger
	 */
	public PMC_CPQ_QuoteTriggerHandler() {
		//Instantiating local class variables from trigger variables
		this.lstNewQuotes = Trigger.new;
		this.mapNewQuotes = (Map<Id, SBQQ__Quote__c>) Trigger.newMap;
		this.lstOldQuotes = Trigger.old;
		this.mapOldQuotes = (Map<Id, SBQQ__Quote__c>) Trigger.oldMap;

		//Set the maximum calls allowed for the class
		this.setMaxLoopCount(32);
	}

	/**
	 * @description This method will perform the operation for before insert trigger
	 */
	public override void beforeInsert() {
		if (BOOL_BYPASS_BEFORE_INSERT || boolBypassTriggerLogic) {
			return;
		}
	}

	/**
	 * @description This method will perform the operation for before update trigger
	 */
	public override void beforeUpdate() {
		if (BOOL_BYPASS_BEFORE_UPDATE || boolBypassTriggerLogic) {
			return;
		}
		PMC_CPQ_QuoteTriggerHelper.validateQuoteExpiration(lstNewQuotes, mapOldQuotes);
        
           
		//added by Monika   
		enforceFieldLock(lstNewQuotes, mapOldQuotes);
	}

	/**
	 * @description This method will perform the operation for before delete trigger
	 */
	public override void beforeDelete() {
		if (BOOL_BYPASS_BEFORE_DELETE || boolBypassTriggerLogic) {
			return;
		}
	}

	/**
	 * @description This method will perform the operation for after insert trigger
	 */
	public override void afterInsert() {
		if (BOOL_BYPASS_AFTER_INSERT || boolBypassTriggerLogic) {
			return;
		}
	}

	/**
	 * @description This method will perform the operation for after update trigger
	 */
	public override void afterUpdate() {
		if (BOOL_BYPASS_AFTER_UPDATE || boolBypassTriggerLogic) {
			return;
		}
		Set<Id> approvedQuotes = new Set<Id>();
		Set<Id> contractStageChangedIds = new Set<Id>();
		for (SBQQ__Quote__c quoteRecord : lstNewQuotes) {
			if (RecordValidator.isFieldChanged(quoteRecord, mapOldQuotes, 'SBQQ__Status__c', 'Approved')) {
				approvedQuotes.add(quoteRecord.Id);
			}
			if (RecordValidator.isFieldChanged(quoteRecord, mapOldQuotes, 'PMC_CPQ_ContractStageName__c')) {
				contractStageChangedIds.add(quoteRecord.Id);
			}
			if (RecordValidator.isFieldChanged(quoteRecord, mapOldQuotes, 'PMC_CPQ_ContractStageName__c', 'Accepted')) {
				PMC_CPQ_QuoteTriggerHelper.validateProductsEntitlementPoliciesAfterAccepted(quoteRecord.Id);
			}
		}
		if (!approvedQuotes.isEmpty() && !System.isFuture() && !System.isBatch()) {
			PMC_CPQ_QuoteTriggerHelper.deleteZeroQuantityLinesAfterApproval(approvedQuotes);
		}

		Set<Id> quotesWithVCOQuotationChanges = new Set<Id>();

		// Identify quotes where the checkbox field PMC_CPQ_VCOQuotation__c actually changed.
		for (SBQQ__Quote__c quoteRecord : lstNewQuotes) {
			SBQQ__Quote__c oldQuote = mapOldQuotes.get(quoteRecord.Id);
			if (
				quoteRecord.PMC_CPQ_RecordTypeName__c == 'Domestic SA' &&
				(quoteRecord.PMC_CPQ_VCOQuotation__c != oldQuote.PMC_CPQ_VCOQuotation__c && !processedQuotes.contains(quoteRecord.Id))
			) {
				quotesWithVCOQuotationChanges.add(quoteRecord.Id);
			}
		}

		if (!quotesWithVCOQuotationChanges.isEmpty()) {
			PMC_CPQ_QuoteTriggerHelper.updateQuoteItemsVCO(quotesWithVCOQuotationChanges, lstNewQuotes);
			// Mark these quotes as processed to prevent infinite loops
			processedQuotes.addAll(quotesWithVCOQuotationChanges);
		}

		if (!approvedQuotes.isEmpty() && !System.isFuture() && !System.isBatch()) {
			PMC_CPQ_QuoteTriggerHelper.setMassContractUpdateApprovalFinishedStep(approvedQuotes);
		}

		if (!contractStageChangedIds.isEmpty() && !System.isFuture() && !System.isBatch()) {
			PMC_CPQ_QuoteTriggerHelper.setMassContractUpdateGenDocumentStatus(contractStageChangedIds);
		}
	}

	/**
	 * @description This method will perform the operation for after delete trigger
	 */
	public override void afterDelete() {
		if (BOOL_BYPASS_AFTER_DELETE || boolBypassTriggerLogic) {
			return;
		}
	}

	/**
	 * @description This method will perform the operation for after undelete trigger
	 */
	public override void afterUndelete() {
		if (BOOL_BYPASS_AFTER_UNDELETE || boolBypassTriggerLogic) {
			return;
		}
	}
}