force-app/main/default/objects/Account/recordTypes/PMC_SS_Customer.recordType-meta.xml
<RecordType>
    <fullName>PMC_SS_Customer</fullName>
    <active>true</active>
    <description>This record type will be used to create Account records of Customer record types</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/PMC_SS_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>PMC_SS_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Opportunity Process</businessProcess>
    <description>Default Opportunity Record Type</description>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/Order/fields/isMosaicDirect__c.field-meta.xml
<CustomField>
    <fullName>isMosaicDirect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Mosaic Direct?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_OrderIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderIntegrationStatus__c</fullName>
    <description>The staus of a callout made to an external system.</description>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PMC_CPQ_SAPOrderNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderNumber__c</fullName>
    <description>This field captures the order number in SAP.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference Order Number in SAP.</inlineHelpText>
    <label>SAP Order Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_LinePONumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_LinePONumber__c</fullName>
    <description>This field will be used to capture the PO Number at a order line level - leveraged in the Contract Document forms for North America</description>
    <label>Customer Purchase Order #</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_RequestedShipDate__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RequestedShipDate__c</fullName>
    <description>This field captures the Requested ship date of the order product.</description>
    <inlineHelpText>This field captures the Requested ship date of the order product.</inlineHelpText>
    <label>Requested Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_SAPOrderLineID__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SAPOrderLineID__c</fullName>
    <description>This Field is used to capture the relevant Order Line ID in SAP System.</description>
    <externalId>true</externalId>
    <inlineHelpText>Order Line ID in SAP System</inlineHelpText>
    <label>SAP Order Line ID</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_ShippingType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShippingType__c</fullName>
    <label>Shipping Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_UnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_UnitOfMeasure__c</fullName>
    <label>Unit Of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/PMC_CPQ_Brazil.recordType-meta.xml
<RecordType>
    <fullName>PMC_CPQ_Brazil</fullName>
    <active>false</active>
    <description>This Record Type was created as a part of story to have different functionalities for different Record Types</description>
    <label>Brazil</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ShippingType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShippingType__c</fullName>
    <label>Shipping Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PMC_CPQ_ModeOfTransportation__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>100-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>105-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>110-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>112-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>25-Car Block</fullName>
            </value>
            <value>
                <fullName>33-Car Block</fullName>
            </value>
            <value>
                <fullName>35-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>50-Car Block</fullName>
            </value>
            <value>
                <fullName>64-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>65-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>70-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>75-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>85-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>90-Car Unit Train</fullName>
            </value>
            <value>
                <fullName>Covered Hopper Car</fullName>
            </value>
            <value>
                <fullName>Open Hopper</fullName>
            </value>
            <value>
                <fullName>Pneumatic Rail Car</fullName>
            </value>
            <value>
                <fullName>Port Dump</fullName>
            </value>
            <value>
                <fullName>Hopper Truck</fullName>
            </value>
            <value>
                <fullName>Ocean Vessel</fullName>
            </value>
            <value>
                <fullName>Box Barge</fullName>
            </value>
            <value>
                <fullName>Container-Rail</fullName>
            </value>
            <value>
                <fullName>Customer Truck</fullName>
            </value>
            <value>
                <fullName>Pneumatic Truck</fullName>
            </value>
            <value>
                <fullName>Bag Truck</fullName>
            </value>
            <value>
                <fullName>Dump Truck</fullName>
            </value>
            <value>
                <fullName>Tank Truck</fullName>
            </value>
            <value>
                <fullName>Less than Truckload</fullName>
            </value>
            <value>
                <fullName>Intermodal Truck</fullName>
            </value>
            <value>
                <fullName>Control Dump Truck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_UnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_UnitOfMeasure__c</fullName>
    <label>Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_SS_UnitOfMeasure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMC_SS_UnitOfMeasure.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MTN</fullName>
    </customValue>
    <customValue>
        <fullName>STN</fullName>
    </customValue>
    <customValue>
        <fullName>WMT</fullName>
    </customValue>
    <customValue>
        <fullName>L</fullName>
    </customValue>
    <customValue>
        <fullName>LTN</fullName>
    </customValue>
    <customValue>
        <fullName>TON</fullName>
    </customValue>
    <masterLabel>Unit Of Measure</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MosaicDirectOrderTriggerTest.cls
@IsTest
private class MosaicDirectOrderTriggerTest {

    @TestSetup
    static void setup() {
        Account acc = PMC_TestUtilityClass.createAccount('Test Account', 'PMC_SS_Customer');
        
        List<Contact> contacts = PMC_TestUtilityClass.createContact(1, 'Master');
        Contact cont = contacts[0];
        cont.AccountId = acc.Id;
        cont.Email = 'test.contact@example.com';
        update cont;
        
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Mosaic Direct Partner Community' LIMIT 1];
        List<User> testUsers = PMC_TestUtilityClass.createPortalUser(1, profile);
        
        User tempUser = new User();
        tempUser.FirstName = 'Test Portal';
        tempUser.LastName = 'Test Doe ';
        tempUser.Alias = 'tPorDoe';
        tempUser.Email='portal.doe123@mosaicco.com';
        tempUser.Username = tempUser.Email+'.teste';
        tempUser.LanguageLocaleKey='en_US';
        tempUser.EmailEncodingKey='UTF-8';
        tempUser.LocaleSidKey='en_US';
        tempUser.TimeZoneSidKey='America/Los_Angeles';
        tempUser.ContactId = cont.Id;
        tempUser.ProfileId = profile.Id;
        tempUser.isActive = true;

        insert tempUser;

        testUsers.add(tempUser);

        List<Product2> products = PMC_TestUtilityClass.createProduct(5, 'PMC_CPQ_Brazil');
        Product2 prod = new Product2(Name='OCS PB Prod'); 
        insert prod;
        products.add(prod);

        List<PricebookEntry> pbes = PMC_TestUtilityClass.createPriceBookEntry(
            products, 
            Test.getStandardPricebookId()
        );

        List<Opportunity> opps = PMC_TestUtilityClass.createOpportunity(1, 'PMC_SS_Opportunity');
        Opportunity opp = opps[0];

        List<Contract> contracts = PMC_TestUtilityClass.createContract(
            new List<Account>{acc}, 
            new List<Opportunity>{opp}
        );
        Contract ctr = contracts[0];
        ctr.Status = 'Activated';
        update ctr;

        List<SBQQ__Quote__c> quotes = PMC_TestUtilityClass.createCPQQuotes(
            1, 
            new List<Opportunity>{opp}, 
            new List<Contact>{cont}
        );
        SBQQ__Quote__c quote = quotes[0];

        EmailTemplate success = new EmailTemplate(
            DeveloperName = 'Mosaic_Direct_Order_Notification', 
            FolderId = UserInfo.getUserId(),
            TemplateType = 'custom', 
            Name = 'Success', 
            IsActive = true, 
            HtmlValue = '<html><body>{!CustomerName}<div>{!tableContent}</div></body></html>'
        );

        EmailTemplate error = new EmailTemplate(
            DeveloperName = 'Mosaic_Direct_Order_Error_Notification', 
            FolderId = UserInfo.getUserId(),
            TemplateType = 'custom', 
            Name = 'Error', 
            IsActive = true, 
            HtmlValue = '<html><body>{!CustomerName} {!quoteName} {!ErrorMessage}</body></html>'
        );

        System.runAs(new User(Id = UserInfo.getUserId())) { 
            insert new List<EmailTemplate>{success, error}; 
        }

        AccountTeamMember atm = new AccountTeamMember(
            AccountId = acc.Id,
            UserId = tempUser.Id,
            TeamMemberRole = 'Sales Rep'
        );
        insert atm;
    }

    @IsTest
    static void testTriggerAndEmailSenderSuccessPath() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id = :prod.Id LIMIT 1];
        Contract ctr = [SELECT Id FROM Contract WHERE AccountId = :acc.Id LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];
        User testUser = [SELECT Id, ContactId FROM User WHERE Email LIKE '%mosaicco.com' LIMIT 1];

        Test.startTest();

        Order ord;
        
        List<Order> orders = PMC_TestUtilityClass.createOrders(1, new List<Account>{acc});
        ord = orders[0];
        
        ord.ContractId = ctr.Id;
        ord.SBQQ__Quote__c = quote.Id;
        ord.IsMosaicDirect__c = true;
        update ord;

        List<OrderItem> orderItems = PMC_TestUtilityClass.createOrderProducts(
            1, 
            new List<Order>{ord}
        );
        OrderItem oi = orderItems[0];
        
        oi.PMC_CPQ_SAPOrderLineID__c = 'SO123456_001';
        oi.PMC_CPQ_RequestedShipDate__c = Date.today().addDays(10);
        oi.PMC_CPQ_LinePONumber__c = 'PO123';
        oi.PMC_CPQ_UnitOfMeasure__c = 'TON';
        oi.PMC_CPQ_ShippingType__c = 'Truck';
        update oi;

        ord.PMC_CPQ_SAPOrderNumber__c = 'SO123456';
        ord.PMC_CPQ_OrderIntegrationStatus__c = 'Success';
        update ord;

        MosaicDirectOrderEmailSender.generateEmailBody(new List<Order>{ord}, 'Yago', '15521');

        Test.stopTest();

        Order updatedOrder = [SELECT Id, PMC_CPQ_SAPOrderNumber__c, PMC_CPQ_OrderIntegrationStatus__c 
                             FROM Order WHERE Id = :ord.Id];
        System.assertEquals('SO123456', updatedOrder.PMC_CPQ_SAPOrderNumber__c);
    }

    @IsTest
    static void testTriggerAndEmailSenderErrorPath() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id = :prod.Id LIMIT 1];
        Contract ctr = [SELECT Id FROM Contract WHERE AccountId = :acc.Id LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        Test.startTest();

        Order ord;
        
        List<Order> orders = PMC_TestUtilityClass.createOrders(1, new List<Account>{acc});
        ord = orders[0];
        
        ord.ContractId = ctr.Id;
        ord.SBQQ__Quote__c = quote.Id;
        ord.IsMosaicDirect__c = true;
        update ord;

        List<OrderItem> orderItems = PMC_TestUtilityClass.createOrderProducts(
            1, 
            new List<Order>{ord}
        );

        ord.PMC_CPQ_OrderIntegrationStatus__c = 'Error';
        update ord;

        Test.stopTest();

        Order updatedOrder = [SELECT Id, PMC_CPQ_OrderIntegrationStatus__c FROM Order WHERE Id = :ord.Id];
        System.assertEquals('Error', updatedOrder.PMC_CPQ_OrderIntegrationStatus__c);
    }

    @IsTest
    static void testEmailSenderMethodsDirectly() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        User testUser = [SELECT Id, Contact.Email, Contact.Name FROM User WHERE Email LIKE '%mosaicco.com' LIMIT 1];
        
        List<Order> testOrders = PMC_TestUtilityClass.createOrders(2, new List<Account>{acc});
        
        for (Order ord : testOrders) {
            ord.IsMosaicDirect__c = true;
        }
        update testOrders;

        Test.startTest();

        MosaicDirectOrderEmailSender.sendOrderConfirmationEmail(
            testOrders, 
            testUser.Contact.Email, 
            testUser.Contact.Name, 
            'Test-Quote-001',
            new List<String>{testUser.Contact.Email}
        );

        MosaicDirectOrderEmailSender.sendOrderErrorEmail(
            testOrders, 
            testUser.Contact.Email, 
            testUser.Contact.Name, 
            'Test-Quote-001',
            new List<String>{testUser.Contact.Email},
            'Test error message'
        );

        MosaicDirectOrderEmailSender.handleOrderSubmission(JSON.serialize(testOrders));

        Test.stopTest();

        System.assert(true, 'Email methods should execute without errors');
    }

    @IsTest
    static void testEmailTemplateNotFound() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        
        List<Order> testOrders = PMC_TestUtilityClass.createOrders(1, new List<Account>{acc});
        
        for (Order ord : testOrders) {
            ord.IsMosaicDirect__c = true;
        }
        update testOrders;

        Test.startTest();
        
        try {
            MosaicDirectOrderEmailSender.sendOrderConfirmationEmail(
                testOrders, 
                'test@example.com', 
                'Test Customer', 
                'Test-Quote',
                new List<String>()
            );
        } catch (Exception e) {
        }

        Test.stopTest();

        System.assert(true, 'Method should handle missing template gracefully');
    }

    @IsTest
    static void testTriggerAllPaths() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id = :prod.Id LIMIT 1];
        Contract ctr = [SELECT Id FROM Contract WHERE AccountId = :acc.Id LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        List<Order> orders = PMC_TestUtilityClass.createOrders(3, new List<Account>{acc});
        
        Order successOrder = orders[0];
        Order errorOrder = orders[1];
        Order warningToErrorOrder = orders[2];
        
        for (Order ord : orders) {
            ord.ContractId = ctr.Id;
            ord.SBQQ__Quote__c = quote.Id;
            ord.IsMosaicDirect__c = true;
        }
        warningToErrorOrder.PMC_CPQ_OrderIntegrationStatus__c = 'Warning';
        update orders;

        List<OrderItem> items = PMC_TestUtilityClass.createOrderProducts(3, orders);

        Test.startTest();
        
        successOrder.PMC_CPQ_SAPOrderNumber__c = 'SO123456';
        successOrder.PMC_CPQ_OrderIntegrationStatus__c = 'Success';
        
        errorOrder.PMC_CPQ_OrderIntegrationStatus__c = 'Error';
        
        warningToErrorOrder.PMC_CPQ_OrderIntegrationStatus__c = 'Error';
        
        update new List<Order>{successOrder, errorOrder, warningToErrorOrder};

        Test.stopTest();

        List<Order> updatedOrders = [SELECT Id, PMC_CPQ_SAPOrderNumber__c, PMC_CPQ_OrderIntegrationStatus__c 
                                    FROM Order WHERE Id IN :new List<Id>{successOrder.Id, errorOrder.Id, warningToErrorOrder.Id}];
        System.assertEquals(3, updatedOrders.size());
    }

    @IsTest
    static void testBulkOperations() {
        Account acc = [SELECT Id FROM Account WHERE Name = 'Test Account' LIMIT 1];
        Contract ctr = [SELECT Id FROM Contract WHERE AccountId = :acc.Id LIMIT 1];
        SBQQ__Quote__c quote = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

        List<Order> bulkOrders = PMC_TestUtilityClass.createOrders(10, new List<Account>{acc});

        for (Order ord : bulkOrders) {
            ord.ContractId = ctr.Id;
            ord.SBQQ__Quote__c = quote.Id;
            ord.IsMosaicDirect__c = true;
        }
        update bulkOrders;

        Test.startTest();
        
        for (Order ord : bulkOrders) {
            ord.PMC_CPQ_SAPOrderNumber__c = 'BULK_' + ord.Id;
            ord.PMC_CPQ_OrderIntegrationStatus__c = 'Success';
        }
        update bulkOrders;

        Test.stopTest();

        List<Order> updatedOrders = [SELECT Id, PMC_CPQ_SAPOrderNumber__c FROM Order WHERE Id IN :bulkOrders];
        System.assertEquals(10, updatedOrders.size());
    }
}