force-app/main/default/objects/Product2/fields/PMC_CPQ_Region__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Region__c</fullName>
    <description>To identify which product belongs to which region so that the product selection can be done accurately. Avoiding cross-region sales. etc,</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_AccountCountry__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_AccountCountry__c</fullName>
    <description>Field to store Account Country</description>
    <label>Account Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractEnd__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractEnd__c</fullName>
    <description>If Master contract exists - then formula to pull the date from Contract reference</description>
    <inlineHelpText>Quote End Date</inlineHelpText>
    <label>Contract Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractShippingInstructions__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractShippingInstructions__c</fullName>
    <description>Shipping Instructions</description>
    <label>Shipping Instructions</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractStageName__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractStageName__c</fullName>
    <description>This field helps to denote the current stage of the contract document</description>
    <label>Contract Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Signature</fullName>
            </value>
            <value>
                <fullName>Partially Executed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>A</fullName>
                <isActive>false</isActive>
                <label>A</label>
            </value>
            <value>
                <fullName>Accept</fullName>
                <isActive>false</isActive>
                <label>Accept</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Executed / Signed</fullName>
                <isActive>false</isActive>
                <label>Executed / Signed</label>
            </value>
            <value>
                <fullName>Full Executed</fullName>
                <isActive>false</isActive>
                <label>Full Executed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Pending Signatures</fullName>
                <isActive>false</isActive>
                <label>Pending Signatures</label>
            </value>
            <value>
                <fullName>Signed</fullName>
                <isActive>false</isActive>
                <label>Signed</label>
            </value>
            <value>
                <fullName>\</fullName>
                <isActive>false</isActive>
                <label>\</label>
            </value>
            <value>
                <fullName>hello</fullName>
                <isActive>false</isActive>
                <label>hello</label>
            </value>
            <value>
                <fullName>test</fullName>
                <isActive>false</isActive>
                <label>test</label>
            </value>
            <value>
                <fullName>yfgfgfc</fullName>
                <isActive>false</isActive>
                <label>yfgfgfc</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractStart__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractStart__c</fullName>
    <description>If Master contract exists - then formula to pull the date from Contract reference</description>
    <inlineHelpText>Quote Start Date</inlineHelpText>
    <label>Contract Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ExpiresOn__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ExpiresOn__c</fullName>
    <description>This field captures the Date and Time this quote will be expired</description>
    <inlineHelpText>Indicates the Date and Time this Quote will expire</inlineHelpText>
    <label>Expiration Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is to capture the Primary Contact associated with the quote.</description>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CPQ Quotes (Primary Contact1)</relationshipLabel>
    <relationshipName>CPQ_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_QuoteApproved__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_QuoteApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify already approved quote via approval process</description>
    <label>Quote Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RecordTypeName__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_Region__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Region__c</fullName>
    <description>Set region based on Account Manager/SSR</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_VCOQuotation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_VCOQuotation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>check box indicator for VCO quotation</description>
    <label>VCO Quotation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
    <inlineHelpText>Account for which this quote has been created.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_VCOQuotation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_VCOQuotation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VCO Quotation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>North Brazil</fullName>
        <isActive>false</isActive>
        <label>North Brazil</label>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
        <isActive>false</isActive>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>Paraguay</fullName>
        <isActive>false</isActive>
        <label>Paraguay</label>
    </customValue>
    <customValue>
        <fullName>Peru</fullName>
        <isActive>false</isActive>
        <label>Peru</label>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
        <isActive>false</isActive>
        <label>Argentina</label>
    </customValue>
    <customValue>
        <fullName>South Brazil</fullName>
        <isActive>false</isActive>
        <label>South Brazil</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <description>This Global Value Set stores/handles values of Region</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMC_CPQ_QuoteTriggerHandlerTest.cls
/**
 * @description This test class will be used to cover all the methods of PMC_CPQ_QuoteTriggerHandler and PMC_CPQ_QuoteTriggerHelper.
 * @author Jaswanth
 * @storynumber GDASF-8944
 */

@isTest(seeAllData=false)
public with sharing class PMC_CPQ_QuoteTriggerHandlerTest {
	/**
	 * @description This Method will be used to setup the data for the test class execution.
	 * @modified by Jaswanth Vaithiswaran part of Test class optimization to run in sales user context.
	 */
	@testSetup
	private static void setup() {
		

		List<String> lstProfileNames = new List<String>{ 'System Administrator', 'Sales User' };
		List<String> lstPermissionNames = new List<String>{ 'PMC_Administrator_Permission_Set_Group', 'PMC_SLS_Permission_Set_Group' };
		Map<String, Id> mapOfProfiles = PMC_TestUtilityClass.getProfiles(lstProfileNames);
		Map<String, PermissionSetGroup> mapOfPermissionGrp = PMC_TestUtilityClass.getPemissionsetGroups(lstPermissionNames);
		Integer intuserCount = 0;
		User objSystemAdminUser;
		User objSalesUser;
		List<User> lstUser = PMC_TestUtilityClass.createUser(2);
		for (User objUser : lstUser) {
			if (intuserCount == 0) {
				objUser.LastName = 'Admin User Test';
				objUser.ProfileId = mapOfProfiles.get('System Administrator');
				objUser.FederationIdentifier = objUser.Username + 'Admin';
			} else if (intuserCount == 1) {
				objUser.LastName = 'Sales User Test';
				objUser.ProfileId = mapOfProfiles.get('Sales User');
				objUser.FederationIdentifier = objUser.Username + 'Sales';
			}
			objUser.isActive = true;
			objUser.MobilePhone = '1234567890';
			objUser.UserPermissionsKnowledgeUser = true;
			objUser.LanguageLocaleKey = 'en_US';
			intuserCount = intuserCount + 1;
		}
		insert lstUser;
		objSystemAdminUser = lstUser[0];
		objSalesUser = lstUser[1];
		PMC_TestUtilityClass.assignPermissionSetGroupToUsers(
			new List<User>{ objSystemAdminUser },
			mapOfPermissionGrp.get('PMC_Administrator_Permission_Set_Group')
		);
		PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{ objSalesUser }, mapOfPermissionGrp.get('PMC_SLS_Permission_Set_Group'));

		System.runAs(objSalesUser) {
			Account objAcc = new Account();
			objAcc.Name = 'Test Account Quote Trigger';
			objAcc.PMC_SS_SAPCustomerNumber__c = 'ijklmnop';
			objAcc.BillingCountry = 'United States';
			objAcc.BillingState = 'California';
			objAcc.BillingStreet = 'fsvc';
			objAcc.BillingCity = 'San Francisco';
			objAcc.BillingPostalCode = '94001';
			insert objAcc;
			Contact testContact = new Contact();
			testContact.FirstName = 'test Jane';
			testContact.LastName = 'test Doe';
			insert testContact;
			Date dateStartDate = System.today();
			dateStartDate = dateStartDate.addDays(2);
			Date dateEndDate = dateStartDate.addDays(35);
			SBQQ__Quote__c objQuote;
			objQuote = new SBQQ__Quote__c();
			objQuote.SBQQ__Account__c = objAcc.Id;
			objQuote.PMC_CPQ_ContractStart__c = dateStartDate;
			objQuote.PMC_CPQ_ContractEnd__c = dateEndDate;
			objQuote.PMC_CPQ_PrimaryContact__c = testContact.id;
			objQuote.SBQQ__Primary__c = true;
			objQuote.SBQQ__Status__c = 'Expired';
			objQuote.PMC_CPQ_ExpiresOn__c = Datetime.now().adddays(-10);
			insert objQuote;
		}

	}
	/**
	 * @description This method will be used to test the scenario where Quote is expired and try to edit the quote.
	 * @modified by Jaswanth Vaithiswaran part of Test class optimization to run in sales user context.
	 */
	@istest
	private static void validateQuoteExpirationTest() {
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [
				SELECT id, SBQQ__Status__c, PMC_CPQ_AccountCountry__c
				FROM SBQQ__Quote__c
				WHERE SBQQ__Status__c = 'Expired'
				LIMIT 1
			];
			cpqQuote.PMC_CPQ_AccountCountry__c = 'India';
			String errorMsg = '';
			try {
				update cpqQuote;
			} catch (EXCEPTION e) {
				errorMsg = e.getMessage();
			}

			Assert.isTrue(errorMsg.contains(System.Label.PMC_CPQ_QuoteExpirationValidationMessage), 'Expiration validation not thrown');
		}
		Test.stopTest();
	}
	/**
	 * @description This method will be used to test the scenario where Query return exception
	 */
	@isTest
	private static void validateQuoteExpirationCatchBlockTest() {
		PMC_CPQ_QuoteTriggerHelper.testException = true;
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [
				SELECT id, SBQQ__Status__c, PMC_CPQ_AccountCountry__c
				FROM SBQQ__Quote__c
				WHERE SBQQ__Status__c = 'Expired'
				LIMIT 1
			];
			update cpqQuote;

			Assert.isTrue(cpqQuote != null, 'Exception not thrown');
		}

		Test.stopTest();
	}

	/**
	 * @description This method is a test method for Quote delete operation.
	 * @modified by Jaswanth Vaithiswaran part of Test class optimization to run in sales user context.
	 */
	@istest
	private static void testQuoteDelete() {
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [SELECT id, PMC_CPQ_ExpiresOn__c, SBQQ__Primary__c FROM SBQQ__Quote__c WITH SECURITY_ENFORCED LIMIT 1];
			Database.delete(cpqQuote.Id);
			List<SBQQ__Quote__c> deletedQuotes = [SELECT Id FROM SBQQ__Quote__c WHERE Id = :cpqQuote.Id WITH SECURITY_ENFORCED];
			Assert.areEqual(0, deletedQuotes.size(), 'Quote was not deleted');
		}
		Test.stopTest();
	}
	/**
	 * @description This method is a test method for Quote undelete operation.
	 * @modified by Jaswanth Vaithiswaran part of Test class optimization to run in sales user context.
	 */
	@istest
	private static void testQuoteUnDelete() {
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [SELECT id, PMC_CPQ_ExpiresOn__c, SBQQ__Primary__c FROM SBQQ__Quote__c WITH SECURITY_ENFORCED LIMIT 1];
			Database.delete(cpqQuote.Id);
			Database.undelete(cpqQuote.Id);
			List<SBQQ__Quote__c> deletedQuotes = [SELECT Id FROM SBQQ__Quote__c WHERE Id = :cpqQuote.Id WITH SECURITY_ENFORCED];
			Assert.areEqual(1, deletedQuotes.size(), 'Quote was not restored');
		}
		Test.stopTest();
	}
	/**
	 * @description This method is a test bypass insert method of the trigger.
	 * @modified by Jaswanth Vaithiswaran part of Test class optimization to run in sales user context.
	 */
	@istest
	private static void testBypassQuoteInsertOperation() {
		PMC_CPQ_QuoteTriggerHandler.boolBypassTriggerLogic = true;
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [
				SELECT id, PMC_CPQ_PrimaryContact__c, PMC_CPQ_ContractStart__c, PMC_CPQ_ContractEnd__c, SBQQ__Account__c
				FROM SBQQ__Quote__c
				WITH SECURITY_ENFORCED
				LIMIT 1
			];
			SBQQ__Quote__c quoteTwo = new SBQQ__Quote__c();
			quoteTwo.PMC_CPQ_PrimaryContact__c = cpqQuote.PMC_CPQ_PrimaryContact__c;
			quoteTwo.PMC_CPQ_ContractStart__c = cpqQuote.PMC_CPQ_ContractStart__c;
			quoteTwo.PMC_CPQ_ContractEnd__c = cpqQuote.PMC_CPQ_ContractEnd__c;
			quoteTwo.SBQQ__Account__c = cpqQuote.SBQQ__Account__c;
			Database.insert(quoteTwo);
			List<SBQQ__Quote__c> lstQuotes = [SELECT id FROM SBQQ__Quote__c WITH SECURITY_ENFORCED];
			Assert.areEqual(2, lstQuotes.size(), 'Quote was not inserted');
		}
		Test.stopTest();
	}
	/**
	 * @description This method is a test bypass update method of the trigger.
	 * @modified by Jaswanth Vaithiswaran part of Test class optimization to run in sales user context.
	 */
	@istest
	private static void testBypassQuoteUpdateOperation() {
		PMC_CPQ_QuoteTriggerHandler.boolBypassTriggerLogic = true;
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [SELECT Id, PMC_CPQ_AccountCountry__c FROM SBQQ__Quote__c WITH SECURITY_ENFORCED LIMIT 1];
			cpqQuote.PMC_CPQ_AccountCountry__c = 'North America';
			Database.update(cpqQuote);
			SBQQ__Quote__c quoteTwo = [SELECT Id, PMC_CPQ_AccountCountry__c FROM SBQQ__Quote__c WITH SECURITY_ENFORCED LIMIT 1];
			Assert.areEqual('North America', quoteTwo.PMC_CPQ_AccountCountry__c, 'Quote was not updated');
		}
		Test.stopTest();
	}
	/**
	 * @description This method is a test bypass delete method of the trigger.
	 */
	@istest
	private static void testBypassQuoteDeleteOperation() {
		PMC_CPQ_QuoteTriggerHandler.boolBypassTriggerLogic = true;
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [SELECT id, PMC_CPQ_ExpiresOn__c, SBQQ__Primary__c FROM SBQQ__Quote__c WITH SECURITY_ENFORCED LIMIT 1];
			Database.delete(cpqQuote.Id);
			List<SBQQ__Quote__c> deletedQuotes = [SELECT Id FROM SBQQ__Quote__c WHERE Id = :cpqQuote.Id WITH SECURITY_ENFORCED];
			Assert.areEqual(0, deletedQuotes.size(), 'Quote was not deleted');
		}
		Test.stopTest();
	}
	/**
	 * @description This method is a test bypass undelete method of the trigger.
	 * @modified by Jaswanth Vaithiswaran part of Test class optimization to run in sales user context.
	 *
	 */
	@istest
	private static void testBypassQuoteUnDeleteOperation() {
		PMC_CPQ_QuoteTriggerHandler.boolBypassTriggerLogic = true;
		Test.startTest();
		User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
		System.runAs(salesUser) {
			SBQQ__Quote__c cpqQuote = [SELECT id, PMC_CPQ_ExpiresOn__c, SBQQ__Primary__c FROM SBQQ__Quote__c WITH SECURITY_ENFORCED LIMIT 1];
			Database.delete(cpqQuote.Id);
			Database.undelete(cpqQuote.Id);
			List<SBQQ__Quote__c> deletedQuotes = [SELECT Id FROM SBQQ__Quote__c WHERE Id = :cpqQuote.Id WITH SECURITY_ENFORCED];
			Assert.areEqual(1, deletedQuotes.size(), 'Quote was not restored');
		}
		Test.stopTest();
	}
	/**
	 * @description Test method for afterUpdate trigger when quote is approved
	 */
	@isTest
	private static void testAfterUpdateQuoteApproval() {
		// Create test account
		Account testAccount = PMC_DH_TestDataFactoryClass.createTestAccount();

		// Create test contact
		Contact testContact = PMC_DH_TestDataFactoryClass.createTestContact(testAccount.Id);

		// Create test opportunity
		Opportunity testOpp = PMC_DH_TestDataFactoryClass.createOpportunity(testAccount);
        testOpp.CurrencyIsoCode = 'USD';
        update testOpp;

		// Create test quote
		SBQQ__Quote__c testQuote = PMC_DH_TestDataFactoryClass.createQuote(testAccount, testContact.Id, testOpp);
		testQuote.SBQQ__Status__c = 'Draft';
		testQuote.PMC_CPQ_ContractStageName__c = 'Accepted';
		update testQuote;

		// Create test product
		Product2 testProduct = PMC_DH_TestDataFactoryClass.createProduct();
		insert testProduct;

		// Create test quote line
		SBQQ__QuoteLine__c testQuoteLine = PMC_DH_TestDataFactoryClass.creatQuoteLine(testQuote, testProduct);

		testQuoteLine.SBQQ__Quantity__c = 0;
		update testQuoteLine;


		Test.startTest();
		// Now approve the quote
		testQuote.PMC_CPQ_QuoteApproved__c = true;
		update testQuote;
		Test.stopTest();
	}
  /*  @isTest
private static void testEnforceFieldLock_RegionBrazil_NoError() {
    User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];

    System.runAs(salesUser) {
        SBQQ__Quote__c quote = [SELECT Id, PMC_CPQ_Region__c, PMC_CPQ_ContractStageName__c, 
                                       PMC_CPQ_ContractShippingInstructions__c 
                                FROM SBQQ__Quote__c LIMIT 1];

        quote.PMC_CPQ_ContractStageName__c = 'Accepted'; 
        quote.PMC_CPQ_Region__c = 'Brazil'; 
        quote.PMC_CPQ_ContractShippingInstructions__c = 'Updated Shipping';
        

        Test.startTest();
        update quote; // Should NOT throw error
        Test.stopTest();
    }
}   */
    @isTest
private static void testAfterUpdate_VCOQuotationChange() {
    User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];

    System.runAs(salesUser) {
        // Create quote with 'Domestic SA' record type
        RecordType recType = [SELECT Id FROM RecordType 
                              WHERE SObjectType = 'SBQQ__Quote__c' 
                              AND Name = 'Domestic SA' 
                              LIMIT 1];

        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            
            SBQQ__Account__c = [SELECT Id FROM Account LIMIT 1].Id,
            PMC_CPQ_ContractStart__c = Date.today().addDays(1),
            PMC_CPQ_ContractEnd__c = Date.today().addDays(40),
            RecordTypeId = recType.Id,
           // PMC_CPQ_RecordTypeName__c = 'Domestic SA',
            SBQQ__Primary__c = true,
            SBQQ__Status__c = 'Draft',
            PMC_CPQ_VCOQuotation__c = false
        );
        insert quote;

        quote.PMC_CPQ_VCOQuotation__c = true;

        Test.startTest();
        update quote;
        Test.stopTest();
    }
}
    /*
@isTest
private static void testAfterUpdateTriggerHandlerLogic() {
    // Arrange test user context
    User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];

    System.runAs(salesUser) {
        // Get existing quote created in @testSetup
        SBQQ__Quote__c existingQuote = [
            SELECT Id, SBQQ__Status__c, PMC_CPQ_ContractStageName__c, 
                   PMC_CPQ_VCOQuotation__c, RecordTypeId
            FROM SBQQ__Quote__c
            LIMIT 1
        ];

        // Fetch Domestic SA record type
        RecordType domesticSA = [
            SELECT Id 
            FROM RecordType 
            WHERE SObjectType = 'SBQQ__Quote__c' AND Name = 'Domestic SA' 
            LIMIT 1
        ];

        // Set up all three trigger conditions
        existingQuote.SBQQ__Status__c = 'Approved'; // Approved path
        existingQuote.PMC_CPQ_ContractStageName__c = 'Accepted'; // Accepted path
        existingQuote.PMC_CPQ_VCOQuotation__c = true; // VCO checkbox path
        existingQuote.RecordTypeId = domesticSA.Id; // Set correct RecordType
         existingQuote.PMC_CPQ_ContractStart__c = Date.today();
        existingQuote.PMC_CPQ_ContractEnd__c = Date.today().addMonths(2);
         existingQuote.PMC_CPQ_ExpiresOn__c = DateTime.now().addDays(50);
        existingQuote.SBQQ__ExpirationDate__c = Date.today().addDays(30);
        
        Test.startTest();
        update existingQuote;
        Test.stopTest();
    }
} */
@isTest
private static void testFieldLockValidationFails() {

    User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];
    
    System.runAs(salesUser) {
        // Create a new Account and Contact
        Account testAccount = new Account(Name = 'Test Lock Account', PMC_SS_SAPCustomerNumber__c = '999999');
        
			testAccount.BillingCountry = 'United States';
			testAccount.BillingState = 'California';
			testAccount.BillingStreet = 'fsvc';
			testAccount.BillingCity = 'San Francisco';
			testAccount.BillingPostalCode = '94001';
        insert testAccount;

        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact');
        insert testContact;

        // Create a new Quote with future expiration and ContractStage set
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        quote.SBQQ__Account__c = testAccount.Id;
        quote.PMC_CPQ_PrimaryContact__c = testContact.Id;
        quote.PMC_CPQ_ContractStart__c = Date.today();
        quote.PMC_CPQ_ContractEnd__c = Date.today().addMonths(1);
        quote.PMC_CPQ_ContractStageName__c = 'Accepted'; // Triggers field lock
        quote.SBQQ__Status__c = 'Draft';
        quote.PMC_CPQ_ExpiresOn__c = DateTime.now().addDays(10); // NOT expired
        quote.PMC_CPQ_Region__c = 'North America';
        insert quote;

        // Clone the quote for update
        SBQQ__Quote__c quoteToUpdate = quote.clone(false, true, false, false);
        quoteToUpdate.Id = quote.Id;

        // Change a restricted field (e.g., Status)
        quoteToUpdate.SBQQ__Status__c = 'Approved'; // Should be blocked by field lock

        Test.startTest();
        String errorMsg = '';
        try {
            update quoteToUpdate;
        } catch (Exception e) {
            errorMsg = e.getMessage();
        }
        Test.stopTest();

        System.assert(
            errorMsg.contains(Label.PMC_CPQ_ContractSetValue), 
            'Expected field-lock error message was not thrown.'
        );
    }
}
 /*   @isTest
private static void testEnforceFieldLock_AllowsUnlockedField() {
    User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];
    System.runAs(salesUser) {
        Account acc = new Account(Name='FieldLockAllow');
        acc.PMC_SS_SAPCustomerNumber__c = 'ijklmnopq';
			acc.BillingCountry = 'United States';
			acc.BillingState = 'California';
			acc.BillingStreet = 'fsvc';
			acc.BillingCity = 'San Francisco';
			acc.BillingPostalCode = '94001';
        insert acc;
        Contact con = new Contact(FirstName='Allow', LastName='FieldLock');
        insert con;
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Account__c = acc.Id,
            PMC_CPQ_PrimaryContact__c = con.Id,
            PMC_CPQ_ContractStageName__c = 'Accepted',
           PMC_CPQ_ExpiresOn__c = DateTime.now().addDays(40),
           SBQQ__Status__c = 'Draft'
        );
        insert quote;

        // Change a field NOT locked (e.g. PMC_CPQ_ContractShippingInstructions__c)
        quote.PMC_CPQ_ContractShippingInstructions__c = 'Some instructions';
        Test.startTest();
        update quote; // Should NOT throw error
        Test.stopTest();
    }
}

*/

@isTest
private static void testAfterUndeleteLogic() {
    User salesUser = [SELECT Id FROM User WHERE LastName = 'Sales User Test' LIMIT 1];
    System.runAs(salesUser) {
        Account acc = new Account(Name='FieldLockAllow');
        acc.PMC_SS_SAPCustomerNumber__c = 'ijklmnopq';
			acc.BillingCountry = 'United States';
			acc.BillingState = 'California';
			acc.BillingStreet = 'fsvc';
			acc.BillingCity = 'San Francisco';
			acc.BillingPostalCode = '94001';
        insert acc;
        Contact con = new Contact(FirstName='Allow', LastName='FieldLock');
        insert con;
        SBQQ__Quote__c quote = new SBQQ__Quote__c(
            SBQQ__Account__c = acc.Id,
            PMC_CPQ_PrimaryContact__c = con.Id,
            PMC_CPQ_ContractStageName__c = 'Accepted',
           PMC_CPQ_ExpiresOn__c = DateTime.now().addDays(40),
           SBQQ__Status__c = 'Draft'
        );
        insert quote;


    // Step 2: Delete the record
    delete quote;

    // Step 3: Undelete the record
    undelete quote;

    // Assertions (optional, depending on what afterUndelete does)
    SBQQ__Quote__c undeletedObj = [SELECT Id, Name FROM SBQQ__Quote__c WHERE Id = :quote.Id];
    System.assertNotEquals(null, undeletedObj);

}
}
}