force-app/main/default/objects/OrderItem/fields/PMC_CPQ_FPDPricefromPriceFx__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FPDPricefromPriceFx__c</fullName>
    <description>Created as part of GDASF-9360. This field captures the FPD price from Price Fx.</description>
    <inlineHelpText>The FPD List Price for the Order Product is only relevant when the contract type of the product is specified as FPD</inlineHelpText>
    <label>FPD List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>This field captures the integration status of the Order product</description>
    <inlineHelpText>This field captures the integration status of the Order product</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_OrderItemIntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderItemIntegrationMessage__c</fullName>
    <description>The Integration message of external callout.</description>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PMC_CPQ_OrderItemIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderItemIntegrationStatus__c</fullName>
    <description>This field captures the integration status of the Order product</description>
    <inlineHelpText>This field captures the integration status of the Order product</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_CPQ_FPDPriceFx__e/PMC_CPQ_FPDPriceFx__e.object-meta.xml
<CustomObject>
    <description>This platform event is to publish and subscribe events from Pricefx system.</description>
    <label>FPD from PriceFx</label>
    <pluralLabel>FPD from PriceFxs</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_FPDPriceFx__e/fields/PMC_CPQ_FPDPrice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FPDPrice__c</fullName>
    <description>The FPD Price received from PriceFX</description>
    <label>FPD Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_FPDPriceFx__e/fields/PMC_CPQ_IntegrationStatusMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatusMessage__c</fullName>
    <description>This field is to store the error message from the callout.</description>
    <label>Integration Status Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_FPDPriceFx__e/fields/PMC_CPQ_InterfaceURL__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_InterfaceURL__c</fullName>
    <label>Interface URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_FPDPriceFx__e/fields/PMC_CPQ_OrderItemId__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderItemId__c</fullName>
    <description>Field to hold the identify the id of the order product record</description>
    <label>Order Item Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_FPDPriceFx__e/fields/PMC_CPQ_OrderLineIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderLineIntegrationStatus__c</fullName>
    <label>Integration Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/PMC_CPQ_Integration_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/fields/PMC_CPQ_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Endpoint__c</fullName>
    <description>This is used to store the Integration endpoint.</description>
    <label>Endpoint</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/PMC_CPQ_TransactionLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>This will show the status of the response of the external callout.</description>
    <label>Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_InterfaceURL__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_InterfaceURL__c</fullName>
    <description>This is the endpoint that was hit during the transaction.</description>
    <label>Interface URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RequestBody__c</fullName>
    <description>This is the request body sent to the external system.</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ResponseBody__c</fullName>
    <description>This field stores the response body of the request made to the external system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PMC_CPQ_SendPriceFPDResponseParsing.cls
/** @description Response Parsing Class for Send Final Price to SAP on Order Detail Page
 *  @creator Prakhar
 *  @storynumber GDASF-12490
 */

public without sharing class PMC_CPQ_SendPriceFPDResponseParsing {
	static final String STRING_INTEGRATIONSTATUSERROR = 'Error';
	// static final String STRING_INTEGRATIONSTATUSSUCCESS = 'Success';
	static final String STRING_INTEGRATIONSTATUS_WAITING = 'Syncing...';
	static final String STRING_INTEGRATIONPREFIXMESSAGE = 'FPD Final Price to SAP';
	static final Integer INT_STATUSCODE200 = 200;
	static final Integer INT_STATUSCODE201 = 201;
	static final List<Integer> LISTINT_SUCCESSCODES = new List<Integer>{ INT_STATUSCODE200, INT_STATUSCODE201 };
	static final List<String> STRING_SUCCESSCODES = new List<String>{ 'S', 'W' };
	static List<PMC_CPQ_TransactionLog__c> lstTransactionLogs;
	static String strStatusTransactionLog;
	static string strEndpoint;

	/** @description Method to parse Success response from SAP.
	 *  @param lstId - List of Order Item records
	 *  @param response - Response from SAP
	 *  @param fromMassFPDUI - boolean variable to check if called from detail page/massfpdUI
	 */
	public static void parseSAPDetail(List<OrderItem> lstId, HttpResponse response, Boolean fromMassFPDUI) {
		String strInterface = 'SendFPD';
		PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface);
		strEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;
		String body = String.valueOf(response.getBody());
		Boolean isSimpleSuccessBody = body == '200 Ok';
		Boolean isHttpSuccess = LISTINT_SUCCESSCODES.contains(response.getStatusCode());
		strStatusTransactionLog = STRING_INTEGRATIONSTATUSERROR; // default until proven success

		for (OrderItem oi : lstId) {
			try {
				if (isHttpSuccess && isSimpleSuccessBody) {
					oi.put('PMC_CPQ_OrderItemIntegrationStatus__c', 'Success');
					oi.put(
						'PMC_CPQ_OrderItemIntegrationMessage__c',
						STRING_INTEGRATIONPREFIXMESSAGE + ': ' + STRING_INTEGRATIONSTATUS_WAITING
					);
				} else {
					oi.put('PMC_CPQ_OrderItemIntegrationStatus__c', 'Error');
					oi.put(
						'PMC_CPQ_OrderItemIntegrationMessage__c',
						STRING_INTEGRATIONPREFIXMESSAGE + ': ' + STRING_INTEGRATIONSTATUSERROR
					);
				}
			} catch (Exception e) {
				oi.put('PMC_CPQ_OrderItemIntegrationMessage__c', STRING_INTEGRATIONPREFIXMESSAGE + ': ' + e.getMessage().abbreviate(230));
			}
		}

		if (isHttpSuccess && isSimpleSuccessBody) {
			strStatusTransactionLog = 'Success';
		} else {
			// If mixed future logic needed, could differentiate Partial Success; currently treat all as Error.
			strStatusTransactionLog = 'Error';
		}
		update lstId;
		createTransactionLog(response);
	}

	/** @description Method to parse Error response from SAP.
	 *  @param lstId - List of Order Item records
	 *  @param response - Response from SAP
	 *  @param fromMassFPDUI - boolean variable to check if called from detail page/massfpdUI
	 */
	public static void parseSAPErrorDetail(List<OrderItem> lstId, HttpResponse response, Boolean fromMassFPDUI) {
		String strInterface = 'SendFPD';
		PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(strInterface);
		strEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;

		strStatusTransactionLog = STRING_INTEGRATIONSTATUSERROR;
		for (OrderItem ordIT : lstId) {
			// map of order line
			ordIT.put('PMC_CPQ_OrderItemIntegrationStatus__c', 'Error');
			ordIT.put('PMC_CPQ_OrderItemIntegrationMessage__c', STRING_INTEGRATIONPREFIXMESSAGE + ': ' + STRING_INTEGRATIONSTATUSERROR);
		}
		update lstId;
		createTransactionLog(response);
		if (fromMassFPDUI) {
			publishToFPDPlatformEvent(lstId, strStatusTransactionLog, strEndpoint);
		}
	}
	/** @description Method to return orderitem object mapped to id.
	 *  @param lstId - List of Order Item records
	 * 	@return mapOrderItem - map of string id and order item object
	 */
	public static Map<String, OrderItem> genOrderItemMap(List<OrderItem> lstId) {
		Map<String, OrderItem> mapOrderItem = new Map<String, OrderItem>();
		for (OrderItem ordIt : lstId) {
			mapOrderItem.put(('' + ordIt.Id), ordIt);
		}
		return mapOrderItem;
	}
	/**
	 * @description this method publishes the fpd price and callout status in the fpd platform event
	 * @param lstOrderLines - List of order lines
	 * @param strTLStatus - status of the callout
	 * @param strTLMessage - response of the callout
	 */
	public static void publishToFPDPlatformEvent(List<OrderItem> lstOrderLines, String strTLStatus, String strTLMessage) {
		//Start Changes for Publishing Platform event
		// Publish a platform event
		if (!lstOrderLines.isEmpty()) {
			List<PMC_CPQ_FPDPriceFx__e> platformEventFPD = new List<PMC_CPQ_FPDPriceFx__e>();
			for (OrderItem op : lstOrderLines) {
				PMC_CPQ_FPDPriceFx__e testEvent = new PMC_CPQ_FPDPriceFx__e();
				testEvent.PMC_CPQ_OrderLineIntegrationStatus__c = strTLStatus;
				testEvent.PMC_CPQ_IntegrationStatusMessage__c = op.PMC_CPQ_OrderItemIntegrationMessage__c;
				testEvent.PMC_CPQ_InterfaceURL__c = strTLMessage;
				testEvent.PMC_CPQ_OrderItemId__c = op.Id;
				try {
					testEvent.PMC_CPQ_FPDPrice__c = op.PMC_CPQ_FPDPricefromPriceFx__c;
				} catch (Exception e) {
				}
				platformEventFPD.add(testEvent);
			}
			// Call method to publish events
			EventBus.publish(platformEventFPD);
			//End Changes for Publishing Platform event
		}
	}
	/**
	 * @description this method updates Integration Status and Integration Message of Order Lines and Transaction Log during Exception
	 * @param lstOrderLines - List of order lines
	 */
	public static void updateLinesOnException(List<OrderItem> lstOrderLines) {
		for (OrderItem ol : lstOrderLines) {
			ol.PMC_CPQ_OrderItemIntegrationStatus__c = 'Error';
			ol.PMC_CPQ_OrderItemIntegrationMessage__c =
				STRING_INTEGRATIONPREFIXMESSAGE +
				': ' +
				PMC_CPQ_CPIRemoteCalloutUtilityClass.strExceptionMsg.abbreviate(225);
		}
		update lstOrderLines;
	}
	/**
	 * @description this method creates Transaction log for the callout
	 * @param response - the http response received
	 */
	public static void createTransactionLog(HttpResponse response) {
		Map<String, String> mapTransactionLogFields = new Map<String, String>();
		mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c', strStatusTransactionLog);
		mapTransactionLogFields.put('PMC_CPQ_InterfaceURL__c', strEndpoint);
		mapTransactionLogFields.put('PMC_CPQ_RequestBody__c', PMC_CPQ_CPIRemoteCalloutUtilityClass.request.getBody());
		mapTransactionLogFields.put('PMC_CPQ_ResponseBody__c', response.getBody().abbreviate(131060));

		lstTransactionLogs = PMC_CPQ_TransactionLogUtilityClass.addTransactionLog(mapTransactionLogFields);
		PMC_CPQ_TransactionLogUtilityClass.insertTransactionLogs(lstTransactionLogs);
	}
}