force-app/main/default/objects/Get_Price_Response__e/Get_Price_Response__e.object-meta.xml
<CustomObject>
    <label>Get Price Response</label>
    <pluralLabel>Get Price Responses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Get_Price_Response__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Get_Price_Response__e/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Get_Price_Response__e/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/MassUpdateExecutionLine__c.object-meta.xml
<CustomObject>
    <label>Mass Update Execution Line</label>
    <nameField>
        <displayFormat>EXL-{0000}</displayFormat>
        <label>Execution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Execution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/CheckEligibilityStatus__c.field-meta.xml
<CustomField>
    <fullName>CheckEligibilityStatus__c</fullName>
    <label>Check Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/CreatedQuote__c.field-meta.xml
<CustomField>
    <fullName>CreatedQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Mass Update Execution Lines</relationshipLabel>
    <relationshipName>MassUpdateExecutionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_CPQ_ErrorMessageSettings__mdt/PMC_CPQ_ErrorMessageSettings__mdt.object-meta.xml
<CustomObject>
    <description>These error messages settings will be applicable for the Get Price Interface.</description>
    <label>Integration Error Message Settings</label>
    <pluralLabel>PMC_CPQ_IntegrationErrorMessageSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_ErrorMessageSettings__mdt/fields/PMC_CPQ_ConvertedErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ConvertedErrorMessage__c</fullName>
    <description>The transformed/converted error message will be displayed here.</description>
    <label>Converted Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_ErrorMessageSettings__mdt/fields/PMC_CPQ_RegexExpression__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RegexExpression__c</fullName>
    <description>The LIKE Expression should be entered here.</description>
    <label>Regex Expression</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/PMC_CPQ_TransactionLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Error_Message__c</fullName>
    <description>The first error message from the integration response if there are more than 1 errors</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>This will show the status of the response of the external callout.</description>
    <label>Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_InterfaceURL__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_InterfaceURL__c</fullName>
    <description>This is the endpoint that was hit during the transaction.</description>
    <label>Interface URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_Quote__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related quote on which the integration is performed</description>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Transaction Logs</relationshipLabel>
    <relationshipName>Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RequestBody__c</fullName>
    <description>This is the request body sent to the external system.</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ResponseBody__c</fullName>
    <description>This field stores the response body of the request made to the external system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Get_Prices_Status__c.field-meta.xml
<CustomField>
    <fullName>Get_Prices_Status__c</fullName>
    <label>Get Prices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Elegible</fullName>
                <isActive>false</isActive>
                <label>Elegible</label>
            </value>
            <value>
                <fullName>Not Elegible</fullName>
                <isActive>false</isActive>
                <label>Not Elegible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_GetPriceCallComplete__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_GetPriceCallComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Created as part of GDASF-6229. The field is to identify the Get Price callout is completed on the cloned quote and to remove the banner message asking AM / CSR to make the Get Price callout.</description>
    <label>Get Price Call Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationMessage__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the integration response message</description>
    <inlineHelpText>receives the Integration response message</inlineHelpText>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the overall integration status.</description>
    <inlineHelpText>Indicates the over all integration status</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_LastPricedDate__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_LastPricedDate__c</fullName>
    <label>Last Priced Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_Region__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Region__c</fullName>
    <description>Set region based on Account Manager/SSR</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.(New,Amend,Renew)</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
                <default>true</default>
                <label>Quote</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_FinalPricePerTon__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FinalPricePerTon__c</fullName>
    <label>Final Price Per Ton (Original)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_FinalPricePerTonne__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_FinalPricePerTonne__c</fullName>
    <description>The Overall Final Price Per Tonne</description>
    <label>Final Price Per Tonne</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_LastPricedDate__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_LastPricedDate__c</fullName>
    <label>Last Priced Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>North America</fullName>
    </customValue>
    <customValue>
        <fullName>North Brazil</fullName>
        <isActive>false</isActive>
        <label>North Brazil</label>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
        <isActive>false</isActive>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>Paraguay</fullName>
        <isActive>false</isActive>
        <label>Paraguay</label>
    </customValue>
    <customValue>
        <fullName>Peru</fullName>
        <isActive>false</isActive>
        <label>Peru</label>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
        <isActive>false</isActive>
        <label>Argentina</label>
    </customValue>
    <customValue>
        <fullName>South Brazil</fullName>
        <isActive>false</isActive>
        <label>South Brazil</label>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <isActive>false</isActive>
        <label>US</label>
    </customValue>
    <description>This Global Value Set stores/handles values of Region</description>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMC_CPQ_SetPriceResource.cls
@RestResource(urlMapping='/quote/setprices')
global without sharing class PMC_CPQ_SetPriceResource {
	static final String STRING_INTEGRATIONSTATUSERROR = 'Error';
	static final String STRING_INTEGRATIONSTATUSSUCCESS = 'Success';
	static final String STRING_GETPRICEPREFIX = 'Get Price: ';
	static String errorMsg = '';

	@HttpPost
	global static void savePrice() {
		Boolean isSuccess = false;
		RestRequest req = RestContext.request;
		RestResponse res = RestContext.response;
		SBQQ__Quote__c quoteRecord;
		String quoteNumber;
		Map<String, Object> jsonResponse;
		String reqBody = req.requestBody.toString();
		String resBody = '';
		PMC_CPQ_TransactionLog__c transactionLog = new PMC_CPQ_TransactionLog__c();
		transactionLog.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
		transactionLog.PMC_CPQ_InterfaceURL__c = '/services/apexrest/quote/setprices';

		try {
			Map<String, Object> untypedResponse = (Map<String, Object>) JSON.deserializeUntyped(reqBody);
			Integer reqBodyMaxLength = PMC_CPQ_TransactionLog__c.PMC_CPQ_RequestBody__c.getDescribe().getLength();
			transactionLog.PMC_CPQ_RequestBody__c = reqBody.length() > reqBodyMaxLength ? reqBody.substring(0, reqBodyMaxLength) : reqBody;
			errorMsg = untypedResponse.get('error') != null ? (String) untypedResponse.get('error') : '';

			if (String.isNotBlank(errorMsg)) {
				String quoteName = 'Q-' + (String) untypedResponse.get('Ztransid');
				List<SBQQ__Quote__c> quotes = [
					SELECT Id, Get_Prices_Status__c, PMC_CPQ_IntegrationStatus__c, PMC_CPQ_IntegrationMessage__c, PMC_CPQ_GetPriceCallComplete__c
					FROM SBQQ__Quote__c
					WHERE Name = :quoteName
					LIMIT 1
				];
				if (quotes.isEmpty()) {
					throw new CustomException('Quote not found!');
				}                
				quoteRecord = quotes[0];
				Integer errorMsgMaxLength = SBQQ__Quote__c.PMC_CPQ_IntegrationMessage__c.getDescribe().getLength();
				quoteRecord.PMC_CPQ_IntegrationMessage__c = errorMsg.length() > errorMsgMaxLength
					? errorMsg.substring(0, errorMsgMaxLength)
					: errorMsg;
				quoteRecord.Get_Prices_Status__c = 'Failed';
				quoteRecord.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
				quoteRecord.PMC_CPQ_GetPriceCallComplete__c = ((quoteRecord.PMC_CPQ_GetPriceCallComplete__c != true) ? false : true);
				res.statusCode = 200;
				resBody = '{"error":"Price fetch failed","details":"' + errorMsg + '","quoteId":"' + quoteRecord.Id + '"}';
				fireGetPriceResponseEvent(quoteRecord.Id, 400, resBody);
                String convErrMsg;
                Boolean matchFound=false;
                List<String> errMsgs = errorMsg.split('\\|',-2);
                transactionLog.PMC_CPQ_Quote__c = quotes[0].Id;
                for(PMC_CPQ_ErrorMessageSettings__mdt objErrorMsg: PMC_CPQ_ErrorMessageSettings__mdt.getAll().values()){
                    if(errMsgs[0].contains(objErrorMsg.PMC_CPQ_RegexExpression__c)){
                        convErrMsg = objErrorMsg.PMC_CPQ_ConvertedErrorMessage__c;
            			matchFound=true;
            			break;
        			}
    			}
                if(!matchFound){                    
                    convErrMsg = errMsgs[0];
                }
                Integer tlerrorMsgMaxLength = PMC_CPQ_TransactionLog__c.PMC_CPQ_Error_Message__c.getDescribe().getLength();
                transactionLog.PMC_CPQ_Error_Message__c = convErrMsg.length() > tlerrorMsgMaxLength ? convErrMsg.substring(0, tlerrorMsgMaxLength): convErrMsg;
			} else {
				System.Debug('Payload:'+untypedResponse);
				jsonResponse = (Map<String, Object>) ((Map<String, Object>) (untypedResponse).get('HeaderSet')).get('Header');

				List<Object> priceCondSet = (List<Object>) jsonResponse.get('Price_CondSet');
				if (!priceCondSet.isEmpty()) {
					Map<String, Object> firstCondSet = (Map<String, Object>) priceCondSet[0];
					List<Object> priceCond = (List<Object>) firstCondSet.get('Price_Cond');

					if (!priceCond.isEmpty()) {
						Map<String, Object> firstCond = (Map<String, Object>) priceCond[0];
						quoteNumber = (String) firstCond.get('Ztransid');
					}
					System.debug('quoteNumber: ' + quoteNumber);
					if (String.isNotBlank(quoteNumber)) {
						quoteNumber = 'Q-' + quoteNumber;
						List<SBQQ__QuoteLine__c> lstQuoteLines = [
							SELECT
								Id,
								Name,
								SBQQ__ListPrice__c,
								PMC_CPQ_FinalPricePerTon__c,
								PMC_CPQ_FinalPricePerTonne__c,
								SBQQ__Number__c,
								SBQQ__Quote__c,
								PMC_CPQ_LastPricedDate__c,
								SBQQ__UpgradedSubscription__c,
								SBQQ__Quote__r.SBQQ__Type__c,
								SBQQ__Quote__r.PMC_CPQ_Region__c,
								SBQQ__Quote__r.PMC_CPQ_GetPriceCallComplete__c
							FROM SBQQ__QuoteLine__c
							WHERE SBQQ__Quote__r.Name = :quoteNumber
						];

						quoteRecord = new SBQQ__Quote__c(
							Id = lstQuoteLines[0].SBQQ__Quote__c,
							PMC_CPQ_GetPriceCallComplete__c = lstQuoteLines[0].SBQQ__Quote__r.PMC_CPQ_GetPriceCallComplete__c
						);
						PMC_CPQ_GetPriceResponseParsing.responseProcess(quoteRecord, untypedResponse);

						quoteRecord.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSSUCCESS;
						quoteRecord.PMC_CPQ_IntegrationMessage__c = STRING_GETPRICEPREFIX + STRING_INTEGRATIONSTATUSSUCCESS;
						quoteRecord.PMC_CPQ_GetPriceCallComplete__c = true;
						res.statusCode = 200;
						resBody = '{"message":"Success!","quoteId":"' + quoteRecord.Id + '"}';
						transactionLog.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSSUCCESS;

						List<SBQQ__QuoteLine__c> linesToUpdate = [
							SELECT Id, 
								PMC_CPQ_FinalPricePerTon__c,
								PMC_CPQ_FinalPricePerTonne__c
							FROM SBQQ__QuoteLine__c
							WHERE SBQQ__Quote__r.Name = :quoteNumber AND SBQQ__Quote__r.Get_Prices_Status__c != 'Approval In Progress'
						];
						if(!linesToUpdate.isEmpty()){
							for (SBQQ__QuoteLine__c quoteLine : linesToUpdate) {
								quoteLine.PMC_CPQ_FinalPricePerTon__c = quoteLine.PMC_CPQ_FinalPricePerTonne__c;
							}
							SBQQ.TriggerControl.disable();
							try {
								Database.update(linesToUpdate, false);
							} finally {
								SBQQ.TriggerControl.enable();
							}
						}

						quoteRecord.Get_Prices_Status__c = 'Completed';
						isSuccess = true;
					} else {
						res.statusCode = 500;
						quoteRecord.Get_Prices_Status__c = 'Failed';
						resBody = '{"error":"Invalid JSON, Ztransid (quoteNumber) not found."}';
					}
				} else {
					quoteRecord.Get_Prices_Status__c = 'Failed';
					res.statusCode = 500;
					resBody = '{"error":"Invalid JSON, Ztransid (quoteNumber) not found."}';
				}
				// On SUCCESS, the event is published by PMC_CPQ_QuoteCalcCallback after
				// the Calculate Quote API finishes (see block after the quoteRecord update).
				// Only fire the event here for parsing/payload failure paths.
				if (!isSuccess) {
					fireGetPriceResponseEvent(quoteRecord.Id, res.statusCode, resBody);
				}
			}
		} catch (CustomException ex) {
			System.debug(ex.getMessage());
			res.statusCode = 500;
			if (quoteRecord != null) {
				quoteRecord.Get_Prices_Status__c = 'Failed';
				quoteRecord.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
				quoteRecord.PMC_CPQ_IntegrationMessage__c = ex.getMessage();
				quoteRecord.PMC_CPQ_GetPriceCallComplete__c = ((quoteRecord.PMC_CPQ_GetPriceCallComplete__c != true) ? false : true);
				resBody = '{"error":"Internal Server Error","details":"' + ex.getMessage() + '","quoteId":"' + quoteRecord.Id + '"}';
				fireGetPriceResponseEvent(quoteRecord.Id, res.statusCode, resBody);
				// Fire Platform Event for exception case
			} else {
				resBody = '{"error":"Internal Server Error","details":"' + ex.getMessage() + '","quoteId":""}';
			}
		}
		if (quoteRecord != null) {
			try {
				SBQQ.TriggerControl.disable();
				try {
					update quoteRecord;
				} finally {
					SBQQ.TriggerControl.enable();
				}

				if (isSuccess) {
					// Trigger the single calculation via the CPQ Calculate Quote API.
					// The callback (PMC_CPQ_QuoteCalcCallback) persists the calculated
					// model and publishes Get_Price_Response__e, guaranteeing that
					// subscribers only receive the signal AFTER the calculation completes.
					PMC_CPQ_QuoteCalcService.recalculate(quoteRecord.Id);
				} else {
					updateExecutionLinesAsync(String.valueOf(quoteRecord.Id));
				}
			} catch (Exception ex) {
				System.Debug('exception::'+ex.getMessage());
				res.statusCode = 500;
				resBody = '{"error":"Internal Server Error","details":"' + ex.getMessage() + '","quoteId":"' + quoteRecord.Id + '"}';
				fireGetPriceResponseEvent(quoteRecord.Id, res.statusCode, resBody);
			}
		}
		res.responseBody = Blob.valueOf(resBody);
		transactionLog.PMC_CPQ_ResponseBody__c = resBody;
		insert transactionLog;
	}

	@future(callout=false)
	private static void updateExecutionLinesAsync(String quoteRecordId) {
		List<MassUpdateExecutionLine__c> execLines = [
			SELECT Id, Status__c, CheckEligibilityStatus__c, Message__c
			FROM MassUpdateExecutionLine__c
			WHERE CreatedQuote__c = :quoteRecordId
		];
		if (execLines.isEmpty()) {
			return;
		}
		for (MassUpdateExecutionLine__c line : execLines) {
			line.Status__c = 'Error';
			line.CheckEligibilityStatus__c = 'Error';
			line.Message__c = String.isNotBlank(errorMsg) ? errorMsg : line.Message__c;
		}
		update execLines;
	}

	private static void fireGetPriceResponseEvent(String quoteId, Decimal statusCode, String message) {
		Get_Price_Response__e event = new Get_Price_Response__e(Quote__c = quoteId, StatusCode__c = statusCode, Message__c = message);

		// Publish the event
		Database.SaveResult sr = EventBus.publish(event);
		if (!sr.isSuccess()) {
			for (Database.Error err : sr.getErrors()) {
				System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
			}
		}
	}
}