force-app/main/default/objects/MassUpdateExecution__c/MassUpdateExecution__c.object-meta.xml
<CustomObject>
    <label>Mass Update Execution</label>
    <nameField>
        <displayFormat>MUE-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MassUpdateExecution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed With Errors</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/MassUpdateExecutionLine__c.object-meta.xml
<CustomObject>
    <label>Mass Update Execution Line</label>
    <nameField>
        <displayFormat>EXL-{0000}</displayFormat>
        <label>Execution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Execution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/MassUpdateExecution__c.field-meta.xml
<CustomField>
    <fullName>MassUpdateExecution__c</fullName>
    <label>Mass Update Execution</label>
    <referenceTo>MassUpdateExecution__c</referenceTo>
    <relationshipLabel>Mass Update Execution Lines</relationshipLabel>
    <relationshipName>ExecutionLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/NewValues__c.field-meta.xml
<CustomField>
    <fullName>NewValues__c</fullName>
    <label>New Values</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_AccountManager__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_AccountManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field captures the Account manager for each quote</description>
    <inlineHelpText>Indicates the Account manager for the Quote</inlineHelpText>
    <label>Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesOffice__c</fullName>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PMC_CPQ_SalesAreaCombination__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_SalesOfficeCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PMC_CPQ_SalesOffice__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SalesOffice__c</fullName>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_SalesOfficeCodes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/PMC_SS_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>PMC_SS_Profile_Name__c</fullName>
    <formula>Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profile Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_SalesOfficeCodes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR BA B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Canais MT  B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Espec Agricolas B</fullName>
    </customValue>
    <customValue>
        <fullName>BR Espec Industriais</fullName>
    </customValue>
    <customValue>
        <fullName>BR FEED B2B</fullName>
    </customValue>
    <customValue>
        <fullName>BR FOSPAR</fullName>
    </customValue>
    <customValue>
        <fullName>BR GO B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Mega Farmer B</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Retail Norte</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Retail Sul B2</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Trader GO+MT</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Trader INT B2</fullName>
    </customValue>
    <customValue>
        <fullName>BR KAM Trader MS B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Matopipa B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MG Norte B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MG Sul B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MOS OPERAÇÕES B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MS B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MT Norte B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MT Oeste B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR MT SUL B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR Pastagem B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR PR/SC 1 B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR PR/SC 2 B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR RS B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR SP Norte B2C</fullName>
    </customValue>
    <customValue>
        <fullName>BR  Fertilizer B2B1</fullName>
    </customValue>
    <customValue>
        <fullName>BR  Fertilizer B2B2</fullName>
    </customValue>
    <customValue>
        <fullName>CA All Canpotex</fullName>
    </customValue>
    <customValue>
        <fullName>CA All Services</fullName>
    </customValue>
    <masterLabel>Sales Office Codes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteUpdateContractsQueueableTest.cls
/**
 * @description Test class for QuoteUpdateContractsQueueable.
 * This class sets up the necessary test data and context for testing the QuoteUpdateContractsQueueable class,
 * which is responsible for updating contracts in SAP via CPI when quotes are updated in Salesforce.
 * The test class uses the QuoteUpdateTestUtils utility class to create the required data, such as users, accounts, contacts, quotes, contracts, and MassUpdateExecution records.
 * It is important to note that this test class does not contain actual test methods, but rather focuses on the setup of test data.
 * The actual test methods should be implemented to assert the expected behavior of the QuoteUpdateContractsQueueable class when executed with the created test data.
 *
 * @author Sergio Umlauf
 */
@IsTest
public class QuoteUpdateContractsQueueableTest {
    @TestSetup
    static void setupData() {
        // Create a test user
        String strSandboxName = UserInfo.getUserName().substringAfterLast('.');
        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name = 'Sales User'];

        // Creating 2 users to test the scenario where there are multiple quotes with different account managers.
        List<User> users = QuoteUpdateTestUtils.createSalesUsers(2);

        // Create a test account
        Account account = QuoteUpdateTestUtils.createAccount();

        // Create a test contact
        Contact contact = QuoteUpdateTestUtils.createContact();

        // Create a few quotes
        List<SBQQ__Quote__c> quotes = QuoteUpdateTestUtils.createQuotes(3, account, contact, users);

        // Create contracts related to the quotes
        SBQQ.TriggerControl.disable();
        List<Contract> contracts = QuoteUpdateTestUtils.createContracts(quotes, account);
        SBQQ.TriggerControl.enable();

        // Create dummy MassUpdateExecution__c
        MassUpdateExecution__c exec = QuoteUpdateTestUtils.createMassUpdateExecution();

        // Create MassUpdateExecutionLine__c records related to the contracts and the execution
        MassUpdateExecutionLine__c line = QuoteUpdateTestUtils.createMassUpdateExecutionLine(exec, contracts[0]);
    }

    @IsTest
    static void testQuoteUpdateContractsQueueable() {
        MassUpdateExecutionLine__c lineBefore = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c LIMIT 1];
        MassUpdateExecution__c exec = [SELECT Id FROM MassUpdateExecution__c LIMIT 1];
        Test.startTest();
        System.enqueueJob(new QuoteUpdateContractsQueueable(lineBefore.Id, exec.Id));
        Test.stopTest();
        MassUpdateExecutionLine__c lineAfter = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c WHERE Id = :lineBefore.Id LIMIT 1];
        System.assert(
            lineAfter.Status__c.contains('Queued') || lineAfter.Status__c.contains('Error'),
            'Execution line status should be Queued or Error after processing.'
        );
    }

    @IsTest
    static void testQuoteUpdateContractsQueueableWithNullExecution() {
        MassUpdateExecutionLine__c lineBefore = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c LIMIT 1];
        MassUpdateExecution__c exec = [SELECT Id FROM MassUpdateExecution__c LIMIT 1];
        Test.startTest();
        System.enqueueJob(new QuoteUpdateContractsQueueable(null, exec.Id));
        Test.stopTest();
        MassUpdateExecutionLine__c lineAfter = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c WHERE Id = :lineBefore.Id LIMIT 1];
        System.assert(lineAfter.Status__c == lineBefore.Status__c, 'The status should not have changed when executionLineId is null.');
    }

    @IsTest
    static void testQuoteUpdateContractsQueueableWithInvalidLineId() {
        MassUpdateExecutionLine__c lineBefore = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c LIMIT 1];
        MassUpdateExecution__c exec = [SELECT Id FROM MassUpdateExecution__c LIMIT 1];

        MassUpdateExecutionLine__c dummyLine = new MassUpdateExecutionLine__c(MassUpdateExecution__c = exec.Id, Status__c = 'Success');
        insert dummyLine;

        Test.startTest();
        System.enqueueJob(new QuoteUpdateContractsQueueable(dummyLine.Id, exec.Id));
        Test.stopTest();
        MassUpdateExecutionLine__c lineAfter = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c WHERE Id = :lineBefore.Id LIMIT 1];
        System.assertEquals('Success', lineAfter.Status__c, 'Execution line status should be still Success after processing and generating the Contract JSON fails.');
    }

    @IsTest
    static void testQuoteUpdateContractsQueueableChangeAccountManager() {
        Contract contract = [SELECT Id, SBQQ__Quote__c FROM Contract LIMIT 1];
        MassUpdateExecution__c exec = [SELECT Id FROM MassUpdateExecution__c LIMIT 1];
        MassUpdateExecutionLine__c lineBefore = QuoteUpdateTestUtils.createMassUpdateExecutionLine(exec, contract);

        User user = [SELECT Id FROM User WHERE PMC_SS_Profile_Name__c = 'Sales User' LIMIT 1];
        lineBefore.NewValues__c = JSON.serialize(new Map<String, Object>{ 'PMC_CPQ_AccountManager__c' => user.Id });
        update lineBefore;

        Test.startTest();
        System.enqueueJob(new QuoteUpdateContractsQueueable(lineBefore.Id, lineBefore.MassUpdateExecution__c));
        Test.stopTest();
        MassUpdateExecutionLine__c lineAfter = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c WHERE Id = :lineBefore.Id LIMIT 1];
        System.assert(
            lineAfter.Status__c.contains('Queued') || lineAfter.Status__c.contains('Error'),
            'Execution line status should be Queued or Error after processing.'
        );
    }

    @IsTest
    static void testQuoteUpdateContractsQueueableChangeSalesOffice() {
        Contract contract = [SELECT Id, SBQQ__Quote__r.PMC_CPQ_SalesOffice__c FROM Contract LIMIT 1];
        MassUpdateExecution__c exec = [SELECT Id FROM MassUpdateExecution__c LIMIT 1];
        MassUpdateExecutionLine__c lineBefore = QuoteUpdateTestUtils.createMassUpdateExecutionLine(exec, contract);

        lineBefore.NewValues__c = JSON.serialize(new Map<String, Object>{ 'PMC_CPQ_SalesOffice__c' => contract.SBQQ__Quote__r.PMC_CPQ_SalesOffice__c });
        update lineBefore;

        Test.startTest();
        System.enqueueJob(new QuoteUpdateContractsQueueable(lineBefore.Id, lineBefore.MassUpdateExecution__c));
        Test.stopTest();
        MassUpdateExecutionLine__c lineAfter = [SELECT Id, Status__c FROM MassUpdateExecutionLine__c WHERE Id = :lineBefore.Id LIMIT 1];
        System.assert(
            lineAfter.Status__c.contains('Queued') || lineAfter.Status__c.contains('Error'),
            'Execution line status should be Queued or Error after processing.'
        );
    }
}