force-app/main/default/objects/MassUpdateExecutionLine__c/MassUpdateExecutionLine__c.object-meta.xml
<CustomObject>
    <label>Mass Update Execution Line</label>
    <nameField>
        <displayFormat>EXL-{0000}</displayFormat>
        <label>Execution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Execution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/CreatedQuote__c.field-meta.xml
<CustomField>
    <fullName>CreatedQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Mass Update Execution Lines</relationshipLabel>
    <relationshipName>MassUpdateExecutionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractEnd__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractEnd__c</fullName>
    <description>If Master contract exists - then formula to pull the date from Contract reference</description>
    <inlineHelpText>Quote End Date</inlineHelpText>
    <label>Contract Valid To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractStart__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractStart__c</fullName>
    <description>If Master contract exists - then formula to pull the date from Contract reference</description>
    <inlineHelpText>Quote Start Date</inlineHelpText>
    <label>Contract Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PMC_CPQ_ContractDateAmenderFlowHandler.cls
public without sharing class PMC_CPQ_ContractDateAmenderFlowHandler {
	@InvocableMethod(label='Amendment Quote Creation Background Process' description='Amendment Quote Creation Background Process')
	public static List<AmendContractResponse> amendContract(List<AmendContractRequest> requestList) {
		List<AmendContractResponse> responseList = new List<AmendContractResponse>();
		List<SBQQ__Quote__c> quotesToUpdate = new List<SBQQ__Quote__c>();
		List<MassUpdateExecutionLine__c> executionLinesToUpdate = new List<MassUpdateExecutionLine__c>();
		Map<Id, Id> mapReqAmendId = new Map<Id, Id>();

		for (AmendContractRequest request : requestList) {
			String contractId = request.uid;
			// Load the contract and perform amendments
			QuoteModel quote = LoadContract(request.uid);
			mapReqAmendId.put(request.uid, quote?.record?.id);
		}
		Map<Id, SBQQ__Quote__c> mapAmendQuotes = new Map<Id, SBQQ__Quote__c>(
			[SELECT Id, PMC_CPQ_ContractStart__c, PMC_CPQ_ContractEnd__c FROM SBQQ__Quote__c WHERE Id IN :mapReqAmendId.values()]
		);
		for (AmendContractRequest request : requestList) {
			String contractId = request.uid;
			String quoteId = mapReqAmendId.get(contractId);
			SBQQ__Quote__c amendQuote = mapAmendQuotes.get(quoteId);
			String contractDates = request.newDates;

			if (amendQuote != null && !String.isBlank(contractDates)) {
				ContractDatesClass newDates = (ContractDatesClass) JSON.deserialize(contractDates, ContractDatesClass.class);
				amendQuote.PMC_CPQ_ContractStart__c = newDates.PMC_CPQ_ContractStart != null
					? newDates.PMC_CPQ_ContractStart
					: amendQuote.PMC_CPQ_ContractStart__c;
				amendQuote.PMC_CPQ_ContractEnd__c = newDates.PMC_CPQ_ContractEnd != null
					? newDates.PMC_CPQ_ContractEnd
					: amendQuote.PMC_CPQ_ContractEnd__c;
				quotesToUpdate.add(amendQuote);
				executionLinesToUpdate.add(new MassUpdateExecutionLine__c(
					Id = request.executionLineId,
					Status__c = 'Success',
					CreatedQuote__c = quoteId,
					Message__c = null
				));
			}

			AmendContractResponse response = new AmendContractResponse();
			response.QuoteId = mapReqAmendId.get(contractId);
			responseList.add(response);
		}
		try {
			if (!quotesToUpdate.isEmpty()) {
				SBQQ.TriggerControl.disable();
				update quotesToUpdate;
				SBQQ.TriggerControl.enable();
			}
			if (!executionLinesToUpdate.isEmpty()) {
				update executionLinesToUpdate;
			}
		} catch (Exception ex) {
			PMC_ErrorLogClass.processException(ex);
		}
		return responseList;
	}

	public static QuoteModel LoadContract(String contractId) {
		String quoteJSON = SBQQ.ServiceRouter.load('SBQQ.ContractManipulationAPI.ContractAmender', contractId, null);
		return (QuoteModel) JSON.deserialize(quoteJSON, QuoteModel.class);
	}

	public class AmendContractRequest {
		@InvocableVariable(label='Contract ID' description='The Salesforce Contract ID to amend')
		public String uid;
		@InvocableVariable(label='New Date Values' description='The new contract start date & end date')
		public String newDates;
		@InvocableVariable(label='Execution Line ID' description='The ID of the execution line context')
		public String executionLineId;
	}

	public class AmendContractResponse {
		@InvocableVariable(label='Amended Quote' description='The amended quote data')
		//public QuoteModel quote;
		public ID QuoteId;
	}

	public class ContractDatesClass {
		public Date PMC_CPQ_ContractStart;
		public Date PMC_CPQ_ContractEnd;
	}

}