force-app/main/default/objects/MassUpdateExecutionLine__c/MassUpdateExecutionLine__c.object-meta.xml
<CustomObject>
    <label>Mass Update Execution Line</label>
    <nameField>
        <displayFormat>EXL-{0000}</displayFormat>
        <label>Execution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Execution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check Eligibility</fullName>
            </value>
            <value>
                <fullName>Generate Amendments</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Generate Contracts</fullName>
            </value>
            <value>
                <fullName>Update Quotes</fullName>
            </value>
            <value>
                <fullName>Check Elegibility</fullName>
                <isActive>false</isActive>
                <label>Check Elegibility</label>
            </value>
            <value>
                <fullName>Generate Contract</fullName>
                <isActive>false</isActive>
                <label>Generate Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteUpdateContractsCalloutQueueable.cls
/**
 * @description Queueable class to handle callouts for updating contracts in S4 via CPI.
 * @author Sergio Umlauf
 * @storynumber GCPM-2771
 */
public with sharing class QuoteUpdateContractsCalloutQueueable implements Queueable, Database.AllowsCallouts {
    private String contractJson;
    private Id executionLineId;
    private Id executionId;

    public QuoteUpdateContractsCalloutQueueable(String contractJson, Id executionLineId, Id executionId) {
        this.contractJson = contractJson;
        this.executionLineId = executionLineId;
        this.executionId = executionId;
    }

    public void execute(QueueableContext context) {
        if (executionLineId == null) {
            System.debug('Execution Line ID is null. Aborting callout.');
            return;
        }
        QuoteUpdateContractsService.CPIResponse cpiResponse = QuoteUpdateContractsService.sendContracts(contractJson);
        updateExecutionWithCPIResult(executionLineId, cpiResponse);
    }

    private void updateExecutionWithCPIResult(Id executionLineId, QuoteUpdateContractsService.CPIResponse cpiResponse) {
        Boolean isSuccess = false;
        String message;

        if (cpiResponse != null && !String.isBlank(cpiResponse.message)) {
            if (cpiResponse.isSuccess && cpiResponse.message.toUpperCase() == '200 OK') {
                isSuccess = true;
                message = 'Contract Sales Office/Account Manager update enqueued.';
            } else {
                message = cpiResponse.message;
            }
        } else {
            message = 'No response from CPI';
        }

        // Update the records with the CPI result
        if (executionLineId != null) {
            updateExecutionLine(executionLineId, isSuccess, message);
        }
    }

    // Update the execution line record with the CPI result
    private void updateExecutionLine(Id executionLineId, Boolean isSuccess, String message) {
        try {
            MassUpdateExecutionLine__c line = [
                SELECT Id, Status__c, Step__c, Message__c
                FROM MassUpdateExecutionLine__c
                WHERE Id = :executionLineId
                LIMIT 1
            ];
            line.Status__c = (isSuccess ? 'In Progress' : 'Error');
            line.Step__c = 'Update Quotes';
            line.Message__c = message;
            update line;
        } catch (Exception ex3) {
            System.debug('Failed to update execution line after CPI callout: ' + ex3.getMessage());
        }
    }
}