force-app/main/default/objects/MassUpdateExecutionLine__c/MassUpdateExecutionLine__c.object-meta.xml
<CustomObject>
    <label>Mass Update Execution Line</label>
    <nameField>
        <displayFormat>EXL-{0000}</displayFormat>
        <label>Execution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Update Execution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/CreatedQuote__c.field-meta.xml
<CustomField>
    <fullName>CreatedQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Mass Update Execution Lines</relationshipLabel>
    <relationshipName>MassUpdateExecutionLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/FinishedSteps__c.field-meta.xml
<CustomField>
    <fullName>FinishedSteps__c</fullName>
    <label>FinishedSteps</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Generate Amendments</fullName>
            </value>
            <value>
                <fullName>Check Eligibility</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Generate Contracts</fullName>
            </value>
            <value>
                <fullName>Update Quotes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MassUpdateExecutionLine__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Check Eligibility</fullName>
            </value>
            <value>
                <fullName>Generate Amendments</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Generate Contracts</fullName>
            </value>
            <value>
                <fullName>Update Quotes</fullName>
            </value>
            <value>
                <fullName>Check Elegibility</fullName>
                <isActive>false</isActive>
                <label>Check Elegibility</label>
            </value>
            <value>
                <fullName>Generate Contract</fullName>
                <isActive>false</isActive>
                <label>Generate Contract</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/PMC_CPQ_Integration_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>This is used to store all External endpoints.</description>
    <label>Integration Endpoint</label>
    <pluralLabel>Integration Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_Integration_Endpoint__mdt/fields/PMC_CPQ_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Endpoint__c</fullName>
    <description>This is used to store the Integration endpoint.</description>
    <label>Endpoint</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/PMC_CPQ_TransactionLog__c.object-meta.xml
<CustomObject>
    <description>This object is used to store transactions details based on SF intergation with external systems.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TRL-{0000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>This will show the status of the response of the external callout.</description>
    <label>Integration Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_InterfaceURL__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_InterfaceURL__c</fullName>
    <description>This is the endpoint that was hit during the transaction.</description>
    <label>Interface URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_RequestBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_RequestBody__c</fullName>
    <description>This is the request body sent to the external system.</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_TransactionLog__c/fields/PMC_CPQ_ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ResponseBody__c</fullName>
    <description>This field stores the response body of the request made to the external system.</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Get_Prices_Status__c.field-meta.xml
<CustomField>
    <fullName>Get_Prices_Status__c</fullName>
    <label>Get Prices Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>Elegible</fullName>
                <isActive>false</isActive>
                <label>Elegible</label>
            </value>
            <value>
                <fullName>Not Elegible</fullName>
                <isActive>false</isActive>
                <label>Not Elegible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationMessage__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationMessage__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the integration response message</description>
    <inlineHelpText>receives the Integration response message</inlineHelpText>
    <label>Integration Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_IntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_IntegrationStatus__c</fullName>
    <description>Created as part of GDASF-5842. This field will capture the overall integration status.</description>
    <inlineHelpText>Indicates the over all integration status</inlineHelpText>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PMC_CPQ_ContractUpdatePublishClass.cls
/** @description This class will be used to publish quote amend event to SAP Event Mesh. 
 *  @author 
 *  @storynumber -SIR-26
 */
public class PMC_CPQ_ContractUpdatePublishClass implements Queueable, Database.AllowsCallouts{
    
    public List<SBQQ__Quote__c> lstQuotes;
    public List<Id> lstIds;
    static final String STRING_INTEGRATIONSTATUSERROR = 'Error';
    static final String STRING_INTEGRATIONSTATUSSUCCESS = 'Success';
	static final String STRING_INTERFACE = 'PublishContractUpdate';    
    static final String STRING_NAMEDCREDENTIALS = 'callout:PMC_CPQ_EDANamedCredential';
    static final String STRING_METHOD = 'POST';
    static final Integer INT_STATUSCODE204 = 204; 
    static final String STRING_PREFIX = 'Contract Update: ';
    static List<PMC_CPQ_TransactionLog__c> lstTransactionLogs = new List<PMC_CPQ_TransactionLog__c>();
     /** 
     * @description Constructor of the class. 
     * @param lstQuotes - list of quotes sent from the flow.
     * @param lstIds - lists of ids
     */
    public PMC_CPQ_ContractUpdatePublishClass(List<SBQQ__Quote__c> lstQuotes, List<Id> lstIds)
    {
        this.lstQuotes = lstQuotes; 
        this.lstIds = lstIds;
    }
    
    /** 
     * @description This is the apex action that will be invoked from the flow.
     * @param lstQuotes - list of quotes sent from the flow.
     */
	@InvocableMethod(label='Contract Update Event Publishing Action' description='Publishes the Amended quotes to Event Mesh to update contract records in SAP' category='SBQQ__Quote__c')
  	public static void postInfoToCPI(List<SBQQ__Quote__c> lstQuotes) {
        List<Id> lstIds = new List<Id>();
        
        for(SBQQ__Quote__c objQuote: lstQuotes)
        {
            lstIds.add(objQuote.Id);
        }
       System.enqueueJob(new PMC_CPQ_ContractUpdatePublishClass(lstQuotes,lstIds));
    }
    
    /** 
     * @description Makes a rerquest to callout class.
     * @param context - Receives the context of the flow. In this case it is the list of quotes.
     */
    public void execute(QueueableContext context)
    {
        PMC_CPQ_Integration_Endpoint__mdt strIntegrationEndpointRecord = PMC_CPQ_Integration_Endpoint__mdt.getInstance(STRING_INTERFACE); 
        String strEndpoint = strIntegrationEndpointRecord.PMC_CPQ_Endpoint__c;
        String strCalloutEndpoint = STRING_NAMEDCREDENTIALS+strEndpoint;
        
        Map<Id, MassUpdateExecutionLine__c> mapExecutionLinesByCreatedQuote = new Map<Id, MassUpdateExecutionLine__c>();
        for(MassUpdateExecutionLine__c line: [
            SELECT Id, CreatedQuote__c, FinishedSteps__c
            FROM MassUpdateExecutionLine__c 
            WHERE CreatedQuote__c IN :lstIds
        ]) {
            mapExecutionLinesByCreatedQuote.put(line.CreatedQuote__c, line);
        }
        String strSerializedBody = PMC_CPQ_CPIRemoteCalloutUtilityClass.createMinimalPayload(lstIds);
        HttpResponse response = PMC_CPQ_CPIRemoteCalloutUtilityClass.sendCalloutRequest(STRING_METHOD, strCalloutEndpoint, strSerializedBody);

        if(response != null){
			
            Map<String, String> mapTransactionLogFields = new Map<String, String>();
			mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c', STRING_INTEGRATIONSTATUSERROR);
			mapTransactionLogFields.put('PMC_CPQ_InterfaceURL__c', strEndpoint);
			mapTransactionLogFields.put('PMC_CPQ_RequestBody__c', strSerializedBody);
			mapTransactionLogFields.put('PMC_CPQ_ResponseBody__c',response.getStatusCode() + ' '+response.getBody());            
            
            for(SBQQ__Quote__c amendedQuote: lstQuotes){
                MassUpdateExecutionLine__c executionLine = mapExecutionLinesByCreatedQuote.get(amendedQuote.Id);
                if(response.getStatusCode() == INT_STATUSCODE204){
                    amendedQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSSUCCESS;
                    // GCPM-5314
                    // amendedQuote.Get_Prices_Status__c = 'In Progress';
                    amendedQuote.PMC_CPQ_IntegrationMessage__c = STRING_PREFIX + 'Published to Event Mesh';
                    if(executionLine != null){
                        mapExecutionLinesByCreatedQuote.put(amendedQuote.Id, new MassUpdateExecutionLine__c(
                            Id = executionLine.Id,
                            Status__c = 'Success',
                            Step__c = 'Generate Contracts',
                            FinishedSteps__c = StringUtils.addPicklistValueToMultiSelect(mapExecutionLinesByCreatedQuote.get(amendedQuote.Id).FinishedSteps__c, 'Generate Contracts')
                        ));
                    }
					mapTransactionLogFields.put('PMC_CPQ_IntegrationStatus__c', STRING_INTEGRATIONSTATUSSUCCESS);                    
                }
                else{
                    amendedQuote.PMC_CPQ_IntegrationStatus__c = STRING_INTEGRATIONSTATUSERROR;
                    // GCPM-5314
                    // amendedQuote.Get_Prices_Status__c = 'Failed';
                    amendedQuote.PMC_CPQ_IntegrationMessage__c = STRING_PREFIX + STRING_INTEGRATIONSTATUSERROR;                    
                    if(executionLine != null){
                        mapExecutionLinesByCreatedQuote.put(amendedQuote.Id, new MassUpdateExecutionLine__c(
                            Id = executionLine.Id,
                            Status__c = 'Error',
                            Step__c = 'Generate Contracts'
                        ));
                    }
                }
                
            }
            update (mapExecutionLinesByCreatedQuote.values());
            update lstQuotes;
            
            lstTransactionLogs = PMC_CPQ_TransactionLogUtilityClass.addTransactionLog(mapTransactionLogFields);
			PMC_CPQ_TransactionLogUtilityClass.insertTransactionLogs(lstTransactionLogs);
            
        } else {
            Boolean boolRetry = PMC_CPQ_CPIRemoteCalloutUtilityClass.autoRetryQueueableApex(AsyncInfo.getCurrentQueueableStackDepth(),PMC_CPQ_CPIRemoteCalloutUtilityClass.strExceptionMsg);
            if(boolRetry) {
                System.enqueueJob(new PMC_CPQ_ContractUpdatePublishClass(lstQuotes,lstIds), 1);
            }
            for(Id quoteId : lstIds) {
                if(mapExecutionLinesByCreatedQuote.size()>0 && mapExecutionLinesByCreatedQuote.get(quoteId)!=null){
                    mapExecutionLinesByCreatedQuote.put(quoteId, new MassUpdateExecutionLine__c(
                        Id = mapExecutionLinesByCreatedQuote.get(quoteId).Id,
                        Status__c = 'Error',
                        Step__c = 'Generate Contracts'
                    ));
                }
            }
            PMC_CPQ_CPIQuoteContractIntegrationClass.updateQuoteExceptionStatusMsg(lstQuotes,strEndpoint);
        }
    }

}