force-app/main/default/objects/PMC_CPQ_RawMaterial__c/PMC_CPQ_RawMaterial__c.object-meta.xml
<CustomObject>
    <description>This Object is to store the details of the Blended Components.</description>
    <label>Raw Material</label>
    <nameField>
        <displayFormat>RM-{0000000000}</displayFormat>
        <label>Raw Material Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Raw Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_RawMaterial__c/fields/PMC_CPQ_Product__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Raw Materials</relationshipLabel>
    <relationshipName>Raw_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_RawMaterial__c/fields/PMC_CPQ_Quote__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is to store the Quote associated with the record.</description>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Raw Materials</relationshipLabel>
    <relationshipName>Raw_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_RawMaterial__c/fields/PMC_CPQ_QuoteLine__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_QuoteLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is to store the respective Quote Line.</description>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Raw Materials</relationshipLabel>
    <relationshipName>Raw_Materials1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMC_CPQ_RawMaterial__c/fields/PMC_CPQ_SoldCFR__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_SoldCFR__c</fullName>
    <description>This field is to store the Sold CFR</description>
    <label>Sold CFR (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PMC_CPQ_CropType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CropType__c</fullName>
    <description>This field captures the crop type for each product record.</description>
    <inlineHelpText>This field captures the crop type for each product record</inlineHelpText>
    <label>Crop Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corn</fullName>
            </value>
            <value>
                <fullName>Wheat</fullName>
            </value>
            <value>
                <fullName>Barley</fullName>
            </value>
            <value>
                <fullName>Soy</fullName>
            </value>
            <value>
                <fullName>Corn Safrinha</fullName>
            </value>
            <value>
                <fullName>Coffee</fullName>
            </value>
            <value>
                <fullName>Cane</fullName>
            </value>
            <value>
                <fullName>Pineapple</fullName>
            </value>
            <value>
                <fullName>Pumpkin</fullName>
            </value>
            <value>
                <fullName>Alfalfa</fullName>
            </value>
            <value>
                <fullName>Cotton</fullName>
            </value>
            <value>
                <fullName>Cotton-Irrigant</fullName>
            </value>
            <value>
                <fullName>Garlic</fullName>
            </value>
            <value>
                <fullName>Peanut</fullName>
            </value>
            <value>
                <fullName>Mulberry</fullName>
            </value>
            <value>
                <fullName>Rice</fullName>
            </value>
            <value>
                <fullName>Rice-Irrigant</fullName>
            </value>
            <value>
                <fullName>Banana</fullName>
            </value>
            <value>
                <fullName>Potato</fullName>
            </value>
            <value>
                <fullName>Potato-Irrigant</fullName>
            </value>
            <value>
                <fullName>Sweet Potato</fullName>
            </value>
            <value>
                <fullName>Cocoa</fullName>
            </value>
            <value>
                <fullName>Coffee-Irrigant</fullName>
            </value>
            <value>
                <fullName>Sugarcane-Plant</fullName>
            </value>
            <value>
                <fullName>Soca Cane</fullName>
            </value>
            <value>
                <fullName>Persimmon</fullName>
            </value>
            <value>
                <fullName>Onion</fullName>
            </value>
            <value>
                <fullName>Carrot</fullName>
            </value>
            <value>
                <fullName>Tea</fullName>
            </value>
            <value>
                <fullName>Citrus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/PMC_CPQ_Nitrogen__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Nitrogen__c</fullName>
    <description>This field captures the Nitrogen % for the product.</description>
    <inlineHelpText>This field captures the Nitrogen % for the product.</inlineHelpText>
    <label>Nitrogen %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/PMC_CPQ_NA.recordType-meta.xml
<RecordType>
    <fullName>PMC_CPQ_NA</fullName>
    <active>true</active>
    <description>Products</description>
    <label>Products</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_AccountCountry__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_AccountCountry__c</fullName>
    <description>Field to store Account Country</description>
    <label>Account Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_ContractType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractType__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Annual</fullName>
                <isActive>false</isActive>
                <label>Annual</label>
            </value>
            <value>
                <fullName>CCC</fullName>
            </value>
            <value>
                <fullName>FPD</fullName>
            </value>
            <value>
                <fullName>FPD Ex-Space</fullName>
                <isActive>false</isActive>
                <label>FPD Ex-Space</label>
            </value>
            <value>
                <fullName>Priced</fullName>
            </value>
            <value>
                <fullName>Priced Ex-Space</fullName>
                <isActive>false</isActive>
                <label>Priced Ex-Space</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_CropType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CropType__c</fullName>
    <description>Crop type is used in mass update section for quote lines in quote line editor</description>
    <label>Crop Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_CropType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_Product__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Product__c</fullName>
    <description>Field to store product information</description>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/PMC_CPQ_VCOQuotation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_VCOQuotation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>check box indicator for VCO quotation</description>
    <label>VCO Quotation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_ContractType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ContractType__c</fullName>
    <description>This field is created  to check the contract type associated to the SBQQ Quote line item.</description>
    <inlineHelpText>This field captures the Contract Type</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PMC_CPQ_QuoteRecordType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCC</fullName>
            </value>
            <value>
                <fullName>FPD</fullName>
            </value>
            <value>
                <fullName>Priced</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
                <isActive>false</isActive>
                <label>Annual</label>
            </value>
            <value>
                <fullName>FPD Ex-Space</fullName>
                <isActive>false</isActive>
                <label>FPD Ex-Space</label>
            </value>
            <value>
                <fullName>Priced Ex-Space</fullName>
                <isActive>false</isActive>
                <label>Priced Ex-Space</label>
            </value>
            <value>
                <fullName>Provisional Pricing</fullName>
                <isActive>false</isActive>
                <label>Provisional Pricing</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_CropType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_CropType__c</fullName>
    <label>Crop Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alfalfa</fullName>
            </value>
            <value>
                <fullName>Artichoke</fullName>
            </value>
            <value>
                <fullName>Banana</fullName>
            </value>
            <value>
                <fullName>Barley</fullName>
            </value>
            <value>
                <fullName>Bean</fullName>
            </value>
            <value>
                <fullName>Beans Safrinha</fullName>
            </value>
            <value>
                <fullName>Cane</fullName>
            </value>
            <value>
                <fullName>Carrot</fullName>
            </value>
            <value>
                <fullName>Cassava</fullName>
            </value>
            <value>
                <fullName>Cassava Watermelon</fullName>
                <isActive>false</isActive>
                <label>Cassava Watermelon</label>
            </value>
            <value>
                <fullName>Castor bean</fullName>
            </value>
            <value>
                <fullName>Citrus</fullName>
            </value>
            <value>
                <fullName>Cocoa</fullName>
            </value>
            <value>
                <fullName>Coconut</fullName>
            </value>
            <value>
                <fullName>Coffee</fullName>
            </value>
            <value>
                <fullName>Coffee-Irrigant</fullName>
            </value>
            <value>
                <fullName>Corn</fullName>
            </value>
            <value>
                <fullName>Corn-Irrigant</fullName>
            </value>
            <value>
                <fullName>Corn Safrinha</fullName>
            </value>
            <value>
                <fullName>Corn silage</fullName>
            </value>
            <value>
                <fullName>Corn silage Strawberry</fullName>
                <isActive>false</isActive>
                <label>Corn silage Strawberry</label>
            </value>
            <value>
                <fullName>Cotton</fullName>
            </value>
            <value>
                <fullName>Cotton-Irrigant</fullName>
            </value>
            <value>
                <fullName>Cucumber</fullName>
            </value>
            <value>
                <fullName>Eucalyptus</fullName>
            </value>
            <value>
                <fullName>Frijoles-Riego</fullName>
            </value>
            <value>
                <fullName>Fruits</fullName>
            </value>
            <value>
                <fullName>Garlic</fullName>
            </value>
            <value>
                <fullName>Grape</fullName>
            </value>
            <value>
                <fullName>Millet silage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_Nitrogen__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_Nitrogen__c</fullName>
    <label>Nitrogen %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_QuoteRecordType__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_QuoteRecordType__c</fullName>
    <description>This picklist will hold the record type of Quote and will be used as a controlling field for many other picklist fields.</description>
    <label>Quote Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic NA</fullName>
            </value>
            <value>
                <fullName>Domestic SA</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>International Distribution</fullName>
            </value>
            <value>
                <fullName>Domestic BR</fullName>
                <isActive>false</isActive>
                <label>Domestic BR</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_VCOQuotation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_VCOQuotation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VCO Quotation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_CropType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alfalfa</fullName>
    </customValue>
    <customValue>
        <fullName>Artichoke</fullName>
    </customValue>
    <customValue>
        <fullName>Banana</fullName>
    </customValue>
    <customValue>
        <fullName>Barley</fullName>
    </customValue>
    <customValue>
        <fullName>Bean</fullName>
    </customValue>
    <customValue>
        <fullName>Beans Safrinha</fullName>
    </customValue>
    <customValue>
        <fullName>Cane</fullName>
    </customValue>
    <customValue>
        <fullName>Carrot</fullName>
    </customValue>
    <customValue>
        <fullName>Cassava</fullName>
    </customValue>
    <customValue>
        <fullName>Castor bean</fullName>
    </customValue>
    <customValue>
        <fullName>Citrus</fullName>
    </customValue>
    <customValue>
        <fullName>Cocoa</fullName>
    </customValue>
    <customValue>
        <fullName>Coconut</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee-Irrigant</fullName>
    </customValue>
    <customValue>
        <fullName>Corn</fullName>
    </customValue>
    <customValue>
        <fullName>Corn-Irrigant</fullName>
    </customValue>
    <customValue>
        <fullName>Corn Safrinha</fullName>
    </customValue>
    <customValue>
        <fullName>Corn silage</fullName>
    </customValue>
    <customValue>
        <fullName>Cotton</fullName>
    </customValue>
    <customValue>
        <fullName>Cotton-Irrigant</fullName>
    </customValue>
    <customValue>
        <fullName>Cucumber</fullName>
    </customValue>
    <customValue>
        <fullName>Eucalyptus</fullName>
    </customValue>
    <customValue>
        <fullName>Frijoles-Riego</fullName>
    </customValue>
    <customValue>
        <fullName>Fruits</fullName>
    </customValue>
    <customValue>
        <fullName>Garlic</fullName>
    </customValue>
    <customValue>
        <fullName>Grape</fullName>
    </customValue>
    <customValue>
        <fullName>Millet silage</fullName>
    </customValue>
    <customValue>
        <fullName>Mulberry</fullName>
    </customValue>
    <customValue>
        <fullName>NA-Beef cattle</fullName>
    </customValue>
    <description>Crop type of products</description>
    <masterLabel>Crop Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PMC_CPQ_ApprovalRequestEmailTempTest.cls
/*
 * This class is the test class for PMC_CPQ_ApprovalRequestEmailTempClass.
 * @author Jeyanthi Muthaiah
 * @storynumber GDASF-3258
 */

@isTest(seeAllData=false)
public with sharing class PMC_CPQ_ApprovalRequestEmailTempTest {
  
    @TestSetup
    private static void setup(){
        List<String>lstProfileNames = New List<String>{'System Administrator','Sales User'};
        List<String>lstPermissionNames = New List<String>{'PMC_Administrator_Permission_Set_Group','PMC_SLS_Permission_Set_Group'};
        Map<String,Id>mapOfProfiles = PMC_TestUtilityClass.getProfiles(lstProfileNames);
        Map<String,PermissionSetGroup>mapOfPermissionGrp = PMC_TestUtilityClass.getPemissionsetGroups(lstPermissionNames);
        Integer intuserCount =0;
        User objSystemAdminUser;  
        User objSalesUser;
        List<User> lstUser = PMC_TestUtilityClass.createUser(2);
            for(User objUser : lstUser) {
                If(intuserCount==0){
                   objUser.LastName = 'Admin User Test';
                   objUser.ProfileId = mapOfProfiles.get('System Administrator'); 
                   objUser.FederationIdentifier = objUser.Username + 'Admin';
                }else if(intuserCount==1){
                    objUser.LastName = 'Sales User Test';
                    objUser.ProfileId = mapOfProfiles.get('Sales User'); 
                   objUser.FederationIdentifier = objUser.Username + 'Sales';
                }
                objUser.isActive = true;                
                objUser.MobilePhone = '1234567890';
                objUser.UserPermissionsKnowledgeUser =true;
                objUser.LanguageLocaleKey = 'en_US';
                intuserCount = intuserCount + 1;
            }            
            insert lstUser;
            objSystemAdminUser = lstUser[0];
            objSalesUser =lstUser[1];
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSystemAdminUser}, mapOfPermissionGrp.get('PMC_Administrator_Permission_Set_Group'));
        PMC_TestUtilityClass.assignPermissionSetGroupToUsers(new List<User>{objSalesUser}, mapOfPermissionGrp.get('PMC_SLS_Permission_Set_Group'));
        System.runas(objSystemAdminUser){
         List <Product2> lstProducts; 
         lstProducts = PMC_TestUtilityClass.CreateProduct(2,'PMC_CPQ_NA');
        }
        System.runas(objSalesUser){
        List<Opportunity> lstOpportunities;
        lstOpportunities = PMC_TestUtilityClass.createOpportunity(2,'Master');
        List<Contact> lstContacts;
        lstContacts = PMC_TestUtilityClass.createContact(1,'Master');
    }
        
    }
    
   
 @isTest 
public static void testGetQuoteInfoAndQuoteLines() {
       Test.startTest();
        List<User> lstUser = [SELECT Id FROM User WHERE LastName ='Sales User Test' WITH SECURITY_ENFORCED LIMIT 1];
        
        System.runAs(lstUser.get(0)){    
         List<Opportunity> lstOppty = [select Id, AccountId from Opportunity LIMIT 1 ];
            
         List<Account> lstAccount = [select Id,PMC_SS_CustomerType__c,PMC_SS_SAPCustomerNumber__c from Account where Id =:lstOppty.get(0).AccountId];
         lstAccount.get(0).PMC_SS_SAPCustomerNumber__c='0805';
         update lstAccount; 
            
         List<Contact> lstCont = [select Id from Contact LIMIT 1];
         lstCont.get(0).AccountId = lstAccount.get(0).Id;
         update lstCont;  
 
        List<SBQQ__Quote__c> testQuotes = PMC_TestUtilityClass.createCPQQuotes(1,lstOppty,lstCont);
        testQuotes[0].PMC_CPQ_AccountCountry__c='United States' ;
        update testQuotes;
        List<Product2> lstProducts = new List<Product2>{ new Product2(Name = 'Test Product 1'), new Product2(Name = 'Test Product 2') };
		insert lstProducts;
         SBQQ__QuoteLine__c testQuoteLine1 = new SBQQ__QuoteLine__c(
				SBQQ__Quote__c = testQuotes.get(0).Id,
				SBQQ__Product__c = lstProducts.get(0).Id,
				PMC_CPQ_Nitrogen__c = 9,
				PMC_CPQ_ContractType__c = 'Priced',
				PMC_CPQ_CropType__c = 'Alfalfa',
				PMC_CPQ_VCOQuotation__c = true,
				PMC_CPQ_QuoteRecordType__c = 'Domestic SA');
		insert testQuoteLine1;
            
       PMC_CPQ_RawMaterial__c testRawMaterial = new PMC_CPQ_RawMaterial__c(PMC_CPQ_Quote__c=testQuotes.get(0).id, PMC_CPQ_QuoteLine__c=testQuoteLine1.id,PMC_CPQ_Product__c =lstProducts.get(1).Id,PMC_CPQ_SoldCFR__c=3,PMC_CPQ_ListCFR__c=5,PMC_CPQ_Quantity__c=5);
       insert testRawMaterial;
        
       PMC_CPQ_ApprovalRequestEmailTempClass controller = new PMC_CPQ_ApprovalRequestEmailTempClass();
        controller.quoteId = testQuotes[0].Id;
        
       
        SBQQ__Quote__c quoteInfo = controller.getQuoteInfo();        
        
        List<SBQQ__QuoteLine__c> qLines = controller.qLines;
        System.assertEquals(testQuotes[0].PMC_CPQ_AccountCountry__c, quoteInfo.PMC_CPQ_AccountCountry__c,'Account doesnot match.');
        System.assertEquals(1, qLines.size(),'Quote Line count is not matching.');
       
 
    }
    Test.stopTest();
    }
}