force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CLM_QuoteLineNumber__c.field-meta.xml
<CustomField>
    <fullName>PMC_CLM_QuoteLineNumber__c</fullName>
    <formula>IF	(
	TEXT(SBQQ__Quote__r.SBQQ__Type__c) &lt;&gt; &apos;Amendment&apos;,
		SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(Name,&quot;QL-&quot;,&quot;&quot;),
		IF	(
				ISNULL(SBQQ__UpgradedSubscription__c) ||  ISBLANK(SBQQ__UpgradedSubscription__c),
				SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__AmendedContract__r.SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(Name,&quot;QL-&quot;,&quot;&quot;),
				SBQQ__UpgradedSubscription__r.SBQQ__QuoteLine__r.SBQQ__Quote__r.PMC_CLM_DocumentNumber__c &amp; &quot;-&quot; &amp; SUBSTITUTE(SBQQ__UpgradedSubscription__r.SBQQ__QuoteLine__r.Name ,&quot;QL-&quot;,&quot;&quot;) 	
			)
	)</formula>
    <label>Quote Line Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/PMC_CPQ_ShipTo__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShipTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created  to check the shipping address value of the line item.</description>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quote Lines (Ship To)</relationshipLabel>
    <relationshipName>Quote_Lines2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PMC_CPQ_LatestSubscription__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_LatestSubscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created as part of XYZ. This will store the value of the latest / newest subscription record created from its current version.</description>
    <label>Latest Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Subscriptions (Latest Subscription)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PMC_CPQ_ShipTo__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShipTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created to check the shipping address value</description>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (Ship To)</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PMC_CPQ_TotalAvailableQuantity__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_TotalAvailableQuantity__c</fullName>
    <description>This field will store the value corresponding to the quantities available to order for a line item</description>
    <label>Total Available Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Subscription__c/fields/PMC_CPQ_TotalOrderedQuantity__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_TotalOrderedQuantity__c</fullName>
    <description>This field will store the  summation of quantities of the several order lines created for a particular line item.</description>
    <label>Total Ordered Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PMC_DH_ContractItemSelectionTest.cls
/**
* @description : Test class for the contract item selection used by Contract Details and Request to Deliver
* @userStory   : GMDP-2743
**/
@isTest
public with sharing class PMC_DH_ContractItemSelectionTest {
    private static final Id CONTRACT_ID = Id.valueOf('800000000000001');
    private static final Id ORIGINAL_LINE_ONE_ID = Id.valueOf('a3O000000000001');
    private static final Id REVERSAL_LINE_ONE_ID = Id.valueOf('a3O000000000002');
    private static final Id ORIGINAL_LINE_TWO_ID = Id.valueOf('a3O000000000003');
    private static final Id ADDED_LINE_TWO_ID = Id.valueOf('a3O000000000004');
    private static final Datetime ORIGINAL_CREATED_DATE = Datetime.newInstanceGmt(2026, 7, 14, 14, 6, 31);
    private static final Datetime AMENDMENT_CREATED_DATE = Datetime.newInstanceGmt(2026, 7, 17, 18, 18, 6);

    @isTest
    static void amendmentReversalIsNeverSelectedAsContractItem(){
        Contract objContract = buildContract(new List<Object>{
            buildSubscription(REVERSAL_LINE_ONE_ID, -500, AMENDMENT_CREATED_DATE, ORIGINAL_LINE_ONE_ID, null),
            buildSubscription(ADDED_LINE_TWO_ID, 500, AMENDMENT_CREATED_DATE, null, null),
            buildSubscription(ORIGINAL_LINE_ONE_ID, 1000, ORIGINAL_CREATED_DATE, null, null),
            buildSubscription(ORIGINAL_LINE_TWO_ID, 1000, ORIGINAL_CREATED_DATE, null, null)
        });

        Test.startTest();
        Map<String, Id> mapUniqueSubscriptionIds = PMC_DH_ContractManagementController.getMapOfSubscriptionIds(new List<Contract>{objContract});
        Test.stopTest();

        Set<Id> setSelectedSubscriptionIds = new Set<Id>(mapUniqueSubscriptionIds.values());
        System.assert(!setSelectedSubscriptionIds.contains(REVERSAL_LINE_ONE_ID), 'A linha de estorno do amendment nao pode virar item de contrato');
        System.assert(setSelectedSubscriptionIds.contains(ORIGINAL_LINE_ONE_ID), 'A linha original deve substituir o estorno no mesmo item de contrato');
        System.assert(setSelectedSubscriptionIds.contains(ADDED_LINE_TWO_ID), 'O item incluido pelo amendment deve ficar disponivel');
        System.assertEquals(3, setSelectedSubscriptionIds.size(), 'Cada linha de contrato deve gerar exatamente um item');
    }

    @isTest
    static void latestSubscriptionWinsForSameContractLineNumber(){
        Contract objContract = buildContract(new List<Object>{
            buildSubscription(ADDED_LINE_TWO_ID, 500, AMENDMENT_CREATED_DATE, null, '1'),
            buildSubscription(ORIGINAL_LINE_ONE_ID, 1000, ORIGINAL_CREATED_DATE, null, '1')
        });

        Test.startTest();
        Map<String, Id> mapUniqueSubscriptionIds = PMC_DH_ContractManagementController.getMapOfSubscriptionIds(new List<Contract>{objContract});
        Test.stopTest();

        System.assertEquals(1, mapUniqueSubscriptionIds.size(), 'O numero de linha do contrato deve agrupar as subscriptions');
        System.assertEquals(ADDED_LINE_TWO_ID, mapUniqueSubscriptionIds.values()[0], 'A subscription mais recente deve representar a linha de contrato');
    }

    @isTest
    static void identicalCreatedDateIsResolvedDeterministically(){
        Contract objContract = buildContract(new List<Object>{
            buildSubscription(ORIGINAL_LINE_ONE_ID, 1000, AMENDMENT_CREATED_DATE, null, '1'),
            buildSubscription(ADDED_LINE_TWO_ID, 500, AMENDMENT_CREATED_DATE, null, '1')
        });
        Contract objContractReversedOrder = buildContract(new List<Object>{
            buildSubscription(ADDED_LINE_TWO_ID, 500, AMENDMENT_CREATED_DATE, null, '1'),
            buildSubscription(ORIGINAL_LINE_ONE_ID, 1000, AMENDMENT_CREATED_DATE, null, '1')
        });

        Test.startTest();
        Map<String, Id> mapUniqueSubscriptionIds = PMC_DH_ContractManagementController.getMapOfSubscriptionIds(new List<Contract>{objContract});
        Map<String, Id> mapReversedOrderSubscriptionIds = PMC_DH_ContractManagementController.getMapOfSubscriptionIds(new List<Contract>{objContractReversedOrder});
        Test.stopTest();

        System.assertEquals(ADDED_LINE_TWO_ID, mapUniqueSubscriptionIds.values()[0], 'O empate de CreatedDate deve ser resolvido pelo maior Id');
        System.assertEquals(mapUniqueSubscriptionIds.values()[0], mapReversedOrderSubscriptionIds.values()[0], 'A ordem retornada pela query nao pode alterar o item escolhido');
    }

    @isTest
    static void contractLinesWithoutNumberAreNotCollapsed(){
        Contract objContract = buildContract(new List<Object>{
            buildSubscription(ORIGINAL_LINE_ONE_ID, 1000, ORIGINAL_CREATED_DATE, null, null),
            buildSubscription(ORIGINAL_LINE_TWO_ID, 1000, ORIGINAL_CREATED_DATE, null, null)
        });

        Test.startTest();
        Map<String, Id> mapUniqueSubscriptionIds = PMC_DH_ContractManagementController.getMapOfSubscriptionIds(new List<Contract>{objContract});
        Test.stopTest();

        System.assertEquals(2, mapUniqueSubscriptionIds.size(), 'Linhas de contrato distintas sem numero de linha nao podem colapsar numa unica chave');
    }

    @isTest
    static void amendmentWrapperResolvesContractItemWithSharedKey(){
        SBQQ__Subscription__c objSubscription = (SBQQ__Subscription__c) JSON.deserialize(
            JSON.serialize(buildSubscription(ORIGINAL_LINE_ONE_ID, 1000, ORIGINAL_CREATED_DATE, null, '1')), SBQQ__Subscription__c.class);
        SBQQ__QuoteLine__c objQuoteLine = (SBQQ__QuoteLine__c) JSON.deserialize(JSON.serialize(buildQuoteLine('1')), SBQQ__QuoteLine__c.class);
        Map<String, Id> mapUniqueSubscriptionIds = new Map<String, Id>{
            PMC_DH_ContractManagementController.buildSubscriptionKey(CONTRACT_ID, objSubscription, null) => ORIGINAL_LINE_ONE_ID
        };

        Test.startTest();
        PMC_DH_RequestForQuoteWrapper.ContractItemsWrapper objContractItem = PMC_DH_ContractAmendmentController.getQuoteSubscriptionDetailsMap(
            objQuoteLine, objSubscription, mapUniqueSubscriptionIds, new Map<Id, SBQQ__Subscription__c>{objSubscription.Id => objSubscription});
        Test.stopTest();

        System.assertEquals(ORIGINAL_LINE_ONE_ID, objContractItem.strContractItemId, 'A tela de amendment deve resolver o item pela mesma chave do dedupe');
    }

    private static Contract buildContract(List<Object> lstSubscriptions){
        Map<String, Object> mapContract = new Map<String, Object>{
            'attributes' => new Map<String, Object>{'type' => 'Contract'},
            'Id' => CONTRACT_ID,
            'SBQQ__Subscriptions__r' => new Map<String, Object>{
                'totalSize' => lstSubscriptions.size(),
                'done' => true,
                'records' => lstSubscriptions
            }
        };
        return (Contract) JSON.deserialize(JSON.serialize(mapContract), Contract.class);
    }

    private static Map<String, Object> buildSubscription(Id subscriptionId, Decimal quantity, Datetime createdDate, Id revisedSubscriptionId, String contractLineNumber){
        return new Map<String, Object>{
            'attributes' => new Map<String, Object>{'type' => 'SBQQ__Subscription__c'},
            'Id' => subscriptionId,
            'CreatedDate' => createdDate,
            'SBQQ__Quantity__c' => quantity,
            'SBQQ__contract__c' => CONTRACT_ID,
            'SBQQ__RevisedSubscription__c' => revisedSubscriptionId,
            'PMC_CPQ_TotalOrderedQuantity__c' => 0,
            'PMC_CPQ_TotalAvailableQuantity__c' => quantity,
            'SBQQ__QuoteLine__r' => buildQuoteLine(contractLineNumber)
        };
    }

    private static Map<String, Object> buildQuoteLine(String contractLineNumber){
        return new Map<String, Object>{
            'attributes' => new Map<String, Object>{'type' => 'SBQQ__QuoteLine__c'},
            'Id' => Id.valueOf('a38000000000001'),
            'SBQQ__Number__c' => 1,
            'SBQQ__Quantity__c' => 1000,
            'PMC_CLM_QuoteLineNumber__c' => contractLineNumber,
            'PMC_CPQ_ShipTo__c' => Id.valueOf('001000000000001'),
            'PMC_CPQ_ShipTo__r' => new Map<String, Object>{
                'attributes' => new Map<String, Object>{'type' => 'Account'},
                'Id' => Id.valueOf('001000000000001'),
                'Name' => 'Ship To Teste',
                'ShippingStreet' => 'Rua Teste',
                'ShippingCity' => 'Uberaba',
                'ShippingState' => 'MG',
                'ShippingPostalCode' => '38000000'
            }
        };
    }
}