force-app/main/default/objects/Shipment/fields/PMC_CPQ_ShippedDate__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShippedDate__c</fullName>
    <description>This field captures the shipped  Date.</description>
    <label>Shipped Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ShipmentItem/fields/isFPD__c.field-meta.xml
<CustomField>
    <fullName>isFPD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isFPD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ShipmentItem/fields/PMC_CPQ_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field captures the order Order Item.</description>
    <label>Order Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Delivery Items</relationshipLabel>
    <relationshipName>Delivery_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShipmentItem/fields/PMC_CPQ_ShippedDate__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ShippedDate__c</fullName>
    <description>This field captures the shipped  Date.</description>
    <label>Shipped Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ShipmentItem/fields/PMC_CPQ_VehicleID__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_VehicleID__c</fullName>
    <description>This field captures the vehicle Vehicle ID.</description>
    <label>Vehicle ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/md_reportOrdersControllerHelper.cls
public class md_reportOrdersControllerHelper {

    public static List<md_reportOrdersWrapper.ShipmentSummary> mapShipmentsToSummaries(
        List<ShipmentItem> shipments
    ) {

        Map<Id, ShipmentItem> selectedShipmentByOrderItem = new Map<Id, ShipmentItem>();

        for (ShipmentItem shipm : shipments) {

            if (shipm.PMC_CPQ_OrderProduct__c == null) continue;

            Id orderItemId = shipm.PMC_CPQ_OrderProduct__c;
            if (!selectedShipmentByOrderItem.containsKey(orderItemId)) {
                selectedShipmentByOrderItem.put(orderItemId, shipm);
                continue;
            }

            ShipmentItem currentSelected = selectedShipmentByOrderItem.get(orderItemId);

            if (shipm.isFPD__c == true && currentSelected.isFPD__c != true) {
                selectedShipmentByOrderItem.put(orderItemId, shipm);
            }
        }

        List<md_reportOrdersWrapper.ShipmentSummary> result =
            new List<md_reportOrdersWrapper.ShipmentSummary>();

        for (ShipmentItem shipm : selectedShipmentByOrderItem.values()) {

            md_reportOrdersWrapper.ShipmentSummary summary = new md_reportOrdersWrapper.ShipmentSummary();
            summary.orderItemId = String.valueOf(shipm.PMC_CPQ_OrderProduct__c);
            summary.vehicleID = shipm.Shipment.PMC_CPQ_VehicleID__c;
            summary.ShippedDate = shipm.Shipment.PMC_CPQ_ShippedDate__c != null ? String.valueOf(shipm.Shipment.PMC_CPQ_ShippedDate__c) : null;

            result.add(summary);
        }

        return result;
    }
}