force-app/main/default/objects/PMC_CPQ_InvoiceItem__c/PMC_CPQ_InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>INV ITEM-{0000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMC_CPQ_InvoiceItem__c/fields/PMC_CPQ_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/Insp_Lot_Usage_Decision__c.field-meta.xml
<CustomField>
    <fullName>Insp_Lot_Usage_Decision__c</fullName>
    <description>Insp. Lot Usage Decision</description>
    <inlineHelpText>Only CoA approved records must be displayed</inlineHelpText>
    <label>Insp. Lot Usage Decision</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_DeliveryStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_DeliveryStatus__c</fullName>
    <description>This field captures the delivery Delivery Status.</description>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not yet Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Completely Shipped</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment/fields/PMC_CPQ_ModeofTransportation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
    <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively.</inlineHelpText>
    <label>MOT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_MoT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShipmentItem/fields/PMC_CPQ_DeliveryStatus__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_DeliveryStatus__c</fullName>
    <description>This field captures the delivery Delivery  Status.</description>
    <label>Delivery Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Shipped</fullName>
            </value>
            <value>
                <fullName>Partially Shipped</fullName>
            </value>
            <value>
                <fullName>Completely Shipped</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
                <isActive>false</isActive>
                <label>Delivered</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>Picked</fullName>
                <isActive>false</isActive>
                <label>Picked</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <isActive>false</isActive>
                <label>Shipped</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShipmentItem/fields/PMC_CPQ_ModeofTransportation__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_ModeofTransportation__c</fullName>
    <inlineHelpText>Select the appropriate mode from the available options to track and manage logistics effectively</inlineHelpText>
    <label>MOT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMC_CPQ_MoT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ShipmentItem/fields/PMC_CPQ_OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>PMC_CPQ_OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field captures the order Order Item.</description>
    <label>Order Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Delivery Items</relationshipLabel>
    <relationshipName>Delivery_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/PMC_CPQ_MoT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barge</fullName>
    </customValue>
    <customValue>
        <fullName>Container</fullName>
    </customValue>
    <customValue>
        <fullName>Rail</fullName>
    </customValue>
    <customValue>
        <fullName>Truck</fullName>
    </customValue>
    <customValue>
        <fullName>Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>No Transport  Req</fullName>
    </customValue>
    <customValue>
        <fullName>Inventory Transfer</fullName>
        <isActive>false</isActive>
        <label>Inventory Transfer</label>
    </customValue>
    <customValue>
        <fullName>Purchase in Place</fullName>
        <isActive>false</isActive>
        <label>Purchase in Place</label>
    </customValue>
    <description>This is created to hold mode of Transportation value sets</description>
    <masterLabel>MoT</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MosaicDirectDocumentCheckAvailability.cls
public without sharing class MosaicDirectDocumentCheckAvailability {
    @AuraEnabled
    public static String checkDocumentButtons(String rawShipmentItems) {
        try {
            List<Object> rawItems = (List<Object>) JSON.deserializeUntyped(rawShipmentItems);
            List<Map<String, Object>> shipmentItems = new List<Map<String, Object>>();

            for (Object item : rawItems) {
                if (item instanceof Map<String, Object>) {
                    shipmentItems.add((Map<String, Object>) item);
                } else {
                    System.debug('Item inválido encontrado: ' + item);
                }
            }

            if (shipmentItems.isEmpty()) {
                throw new AuraHandledException('Nenhum item válido encontrado no JSON.');
            }

            Set<Id> orderIds = new Set<Id>();
            for (Map<String, Object> ship : shipmentItems) {
                Object orderProduct = ship.get('PMC_CPQ_OrderProduct__c');
                if (orderProduct != null) {
                    orderIds.add(String.valueOf(orderProduct));
                }
            }

            Map<Id, PMC_CPQ_InvoiceItem__c> orderInvoiceItems = new Map<Id, PMC_CPQ_InvoiceItem__c>();
            Map<Id, ShipmentItem> bolItems = new Map<Id, ShipmentItem>();
            Map<Id, ShipmentItem> coaItems = new Map<Id, ShipmentItem>();

            if (!orderIds.isEmpty()) {
                for (PMC_CPQ_InvoiceItem__c invoiceItem : [
                    SELECT Id, PMC_CPQ_OrderProduct__c 
                    FROM PMC_CPQ_InvoiceItem__c 
                    WHERE PMC_CPQ_OrderProduct__c IN :orderIds
                ]) {
                    orderInvoiceItems.put(invoiceItem.PMC_CPQ_OrderProduct__c, invoiceItem);
                }

                for (ShipmentItem shipmentItem : [
                    SELECT Id, PMC_CPQ_ModeofTransportation__c, PMC_CPQ_OrderProduct__c, Shipment.Insp_Lot_Usage_Decision__c
                    FROM ShipmentItem 
                    WHERE PMC_CPQ_OrderProduct__c IN :orderIds AND Shipment.Status != 'Delivery Deleted' AND Shipment.PMC_CPQ_DeliveryStatus__c = 'Completely Shipped'
                ]) {
                    if (shipmentItem.PMC_CPQ_ModeofTransportation__c == 'Barge') continue; // GMDP-2127

                    bolItems.put(shipmentItem.PMC_CPQ_OrderProduct__c, shipmentItem);
                    if (shipmentItem.Shipment.Insp_Lot_Usage_Decision__c == 'Approved') coaItems.put(shipmentItem.PMC_CPQ_OrderProduct__c, shipmentItem);
                }
            }

            for (Map<String, Object> ship : shipmentItems) {
                Object orderProduct = ship.get('PMC_CPQ_OrderProduct__c');
                String orderItemId = orderProduct != null ? String.valueOf(orderProduct) : null;

                ship.put('invoiceFounded', orderInvoiceItems.get(orderItemId) != null);
                ship.put('bolFounded', bolItems.get(orderItemId) != null);
                ship.put('coaFounded', coaItems.get(orderItemId) != null);
            }

            return JSON.serialize(shipmentItems);
        } catch (Exception e) {
            throw new AuraHandledException('Erro ao processar documentos: ' + e.getMessage());
        }
    }
}